/**
 * Java block state → **Bedrock Edition** block name + states.
 *
 * This is the quality-critical half of the Bedrock export, and the exact place a
 * Java→Bedrock converter degrades a build. The failure modes are all silent:
 *
 *   • an id that does not exist in Bedrock (`minecraft:bricks`,
 *     `minecraft:nether_bricks`, `minecraft:snow_block`) → the structure loader
 *     cannot resolve it and the cell becomes AIR: holes in the model;
 *   • an id that exists in BOTH editions meaning DIFFERENT blocks —
 *     `minecraft:stone_stairs` is *cobblestone* stairs in Bedrock, whose stone
 *     stairs are `normal_stone_stairs` — → the wrong material, no error;
 *   • a state name that does not exist (`facing`, `type`, `half`) → the block
 *     falls back to its DEFAULT permutation: every stair faces one way, every
 *     top slab drops to the floor, `type=double` becomes a half block.
 *
 * So the mapping is DATA, verified against Mojang's own published Bedrock block
 * registry rather than typed from memory: `bedrock-block-states.json` is
 * generated by `scripts/gen-bedrock-blocks.mjs` from
 * `Mojang/bedrock-samples metadata/vanilladata_modules/mojang-blocks.json`
 * (every Bedrock block id, its state names, and each state's allowed values).
 * `test/bedrock-blocks.test.ts` asserts that EVERY id our palette can emit —
 * the whole of `mc-block-registry.json` — has a mapping, so a new entry in a
 * colour table or a shape pass fails the suite instead of exporting holes.
 *
 * There is deliberately NO silent fallback: `toBedrockBlock` returns null for an
 * unmapped id and the caller must decide (the encoder throws, so a gap is a
 * failed export with a named block, not a build full of dirt).
 */

import DATA from './bedrock-block-states.json';

/** A resolved Bedrock block: full id and a COMPLETE state compound. */
export interface BedrockBlock {
  /** Namespaced Bedrock id, e.g. `minecraft:normal_stone_stairs`. */
  name: string;
  /** Every state the block has, typed as Bedrock expects it. */
  states: Record<string, string | number | boolean>;
}

interface PropertyDef {
  type: string;
  default: string | number | boolean;
  values: ReadonlyArray<string | number | boolean>;
}

const PROPERTIES = DATA.properties as unknown as Record<string, PropertyDef>;
const BLOCKS = DATA.blocks as unknown as Record<string, readonly string[]>;
const DOUBLE_SLABS = DATA.doubleSlabs as unknown as Record<string, string>;

/**
 * Java id → Bedrock id, for the ids where the two editions genuinely differ.
 *
 * Every entry is a real difference confirmed against Mojang's registry (the
 * generator fails if a target does not exist), NOT a guess. Ids absent from this
 * table are identical in both editions — which, in modern Bedrock, is 377 of the
 * 392 ids we can emit; the flattening did most of the work.
 */
export const JAVA_TO_BEDROCK_ID: Readonly<Record<string, string>> = {
  // "…bricks" (Java, plural) is "…brick" or a legacy stem in Bedrock.
  bricks: 'brick_block',
  nether_bricks: 'nether_brick',
  red_nether_bricks: 'red_nether_brick',
  end_stone_bricks: 'end_bricks',
  end_stone_brick_stairs: 'end_brick_stairs',
  // Bedrock's prismarine brick stairs keep the plural stem — the one stair id in
  // the game where "brick" is not singularized.
  prismarine_brick_stairs: 'prismarine_bricks_stairs',
  // Stone slabs/stairs: the pair below is the single most damaging mistake
  // available here, because both names EXIST in both editions with different
  // materials. Bedrock inherited `stone_stairs` from the pre-flattening numeric
  // id for COBBLESTONE stairs, and named the stone ones `normal_stone_*`.
  stone_slab: 'normal_stone_slab',
  stone_stairs: 'normal_stone_stairs',
  cobblestone_stairs: 'stone_stairs',
  // Blocks Bedrock never renamed to the Java flattening.
  jack_o_lantern: 'lit_pumpkin',
  light_gray_glazed_terracotta: 'silver_glazed_terracotta',
  magma_block: 'magma',
  rooted_dirt: 'dirt_with_roots',
  slime_block: 'slime',
  // Java `snow_block` is the full block and `snow` the layer; Bedrock is the
  // other way round (`snow` = block, `snow_layer` = layer). Two ids swapping
  // meaning, so this needs the explicit entry even though "snow" looks fine.
  snow_block: 'snow',
  terracotta: 'hardened_clay',
  wall_torch: 'torch',
  stone_bricks_slab: 'stone_brick_slab',
  water_cauldron: 'cauldron',
  armor_stand: 'oak_fence',
  stonecutter: 'stonecutter_block',
  oak_wall_sign: 'wall_sign',
  oak_sign: 'standing_sign',
};

function renamedId(id: string): string {
  if (/^potted_/.test(id)) return 'flower_pot';
  if (/^(white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_bed$/.test(id)) return 'bed';
  if (/^(white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_banner$/.test(id)) return 'standing_banner';
  if (/^(white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_wall_banner$/.test(id)) return 'wall_banner';
  return JAVA_TO_BEDROCK_ID[id] ?? id;
}

/**
 * Java `facing` → Bedrock `facing_direction` int.
 *
 * Both editions inherited these numbers from the pre-1.13 block metadata that
 * Java and Bedrock shared, which is why the mapping is exact rather than
 * conventional: 0 down, 1 up, 2 north, 3 south, 4 west, 5 east.
 */
export const FACING_DIRECTION: Readonly<Record<string, number>> = {
  down: 0, up: 1, north: 2, south: 3, west: 4, east: 5,
};

/**
 * Java stair `facing` → Bedrock `weirdo_direction`.
 *
 * Also the shared legacy metadata: a stair's low two data bits were
 * 0 east, 1 west, 2 south, 3 north, and Bedrock exposes them under that name.
 * (Corroborated by HotSchem's own in-game-validated placement script.)
 */
export const WEIRDO_DIRECTION: Readonly<Record<string, number>> = {
  east: 0, west: 1, south: 2, north: 3,
};

/**
 * Java wall connection → Bedrock `wall_connection_type_*`.
 * Same three states, one different word: Java's "low" is Bedrock's "short".
 */
const WALL_CONNECTION: Readonly<Record<string, string>> = {
  none: 'none', low: 'short', tall: 'tall',
};

/** Split `minecraft:oak_stairs[facing=north,half=top]` into id + properties. */
export function parseJavaState(entry: string): { id: string; props: Record<string, string> } {
  const withoutNs = entry.startsWith('minecraft:') ? entry.slice('minecraft:'.length) : entry;
  const bracket = withoutNs.indexOf('[');
  if (bracket < 0) return { id: withoutNs, props: {} };
  const id = withoutNs.slice(0, bracket);
  const props: Record<string, string> = {};
  const tail = withoutNs.slice(bracket + 1).replace(/]$/, '');
  for (const pair of tail.split(',')) {
    const eq = pair.indexOf('=');
    if (eq > 0) props[pair.slice(0, eq)] = pair.slice(eq + 1);
  }
  return { id, props };
}

/** True when the Bedrock registry knows this id (used by the lint test). */
export function isBedrockBlock(bedrockId: string): boolean {
  return Object.prototype.hasOwnProperty.call(BLOCKS, bedrockId);
}

/** The state names a Bedrock block carries, or null for an unknown id. */
export function bedrockStateNames(bedrockId: string): readonly string[] | null {
  return isBedrockBlock(bedrockId) ? BLOCKS[bedrockId]! : null;
}

/**
 * Build the COMPLETE default state compound for a Bedrock block.
 *
 * Bedrock matches a *permutation*, so a partial state set leans on the loader's
 * legacy fallback; emitting every state removes that dependency. Two defaults
 * are overridden from the registry's own first-listed value because the vanilla
 * default is not the sane one for a converted build:
 *   • `facing_direction` defaults to 0 (down), which is not a legal orientation
 *     for the horizontal-only blocks that carry it here (glazed terracotta) —
 *     use 2 (north);
 *   • `huge_mushroom_bits` defaults to 0, which is the all-pores inside face —
 *     a mushroom block placed with it looks like a mistake;
 *   • `persistent_bit` defaults to false, and non-persistent leaves with no log
 *     nearby DECAY — a placed tree would lose its canopy minutes later.
 */
function defaultStates(bedrockId: string): Record<string, string | number | boolean> {
  const names = BLOCKS[bedrockId] ?? [];
  const states: Record<string, string | number | boolean> = {};
  for (const name of names) {
    const def = PROPERTIES[name];
    if (!def) continue;
    if (name === 'facing_direction') { states[name] = FACING_DIRECTION['north']!; continue; }
    if (name === 'huge_mushroom_bits') {
      // 14 = cap on all faces, 15 = stem on all faces (shared legacy data values).
      states[name] = bedrockId === 'mushroom_stem' ? 15 : 14;
      continue;
    }
    if (name === 'persistent_bit') { states[name] = true; continue; }
    states[name] = def.default;
  }
  return states;
}

/**
 * Translate one Java palette entry to Bedrock.
 *
 * Returns null when the id has no Bedrock mapping — deliberately, so a gap
 * surfaces as a failed export naming the block rather than as silent air.
 */
export function toBedrockBlock(javaEntry: string): BedrockBlock | null {
  const { id, props } = parseJavaState(javaEntry);
  let bedrockId = renamedId(id);

  // A double slab is a different BLOCK in Bedrock, not a slab state. Resolve it
  // before the state pass so the state pass sees the right block's schema.
  if (props['type'] === 'double') {
    const dbl = DOUBLE_SLABS[bedrockId];
    if (dbl) bedrockId = dbl;
  }
  if (!isBedrockBlock(bedrockId)) return null;

  const states = defaultStates(bedrockId);
  const has = (name: string) => Object.prototype.hasOwnProperty.call(states, name);

  // ── Slabs: Java `type=top|bottom|double` → `minecraft:vertical_half` ────────
  // `double` already became its own block above; its vertical_half stays bottom.
  if (has('minecraft:vertical_half') && props['type'] && props['type'] !== 'double') {
    states['minecraft:vertical_half'] = props['type'] === 'top' ? 'top' : 'bottom';
  }

  // ── Stairs: `facing`/`half` → `weirdo_direction`/`upside_down_bit` ──────────
  if (has('weirdo_direction')) {
    const w = props['facing'] ? WEIRDO_DIRECTION[props['facing']] : undefined;
    if (w !== undefined) states['weirdo_direction'] = w;
    if (props['half']) states['upside_down_bit'] = props['half'] === 'top';
  }

  // ── Ladders, glazed terracotta: `facing` → `facing_direction` int ───────────
  if (has('facing_direction') && props['facing']) {
    const f = FACING_DIRECTION[props['facing']];
    if (f !== undefined) states['facing_direction'] = f;
  }

  if (has('minecraft:cardinal_direction') && props['facing'] && /^(north|south|east|west)$/.test(props['facing'])) {
    states['minecraft:cardinal_direction'] = props['facing'];
  }

  // Legacy horizontal direction: south=0, west=1, north=2, east=3.
  if (has('direction') && props['facing']) {
    const d: Record<string, number> = { south: 0, west: 1, north: 2, east: 3 };
    if (d[props['facing']] !== undefined) states['direction'] = d[props['facing']]!;
  }
  if (has('torch_facing_direction') && props['facing']) states['torch_facing_direction'] = props['facing'] === 'up' ? 'top' : props['facing'];
  if (has('open_bit') && props['open']) states['open_bit'] = props['open'] === 'true';
  if (has('door_hinge_bit') && props['hinge']) states['door_hinge_bit'] = props['hinge'] === 'right';
  if (has('upper_block_bit') && props['half']) states['upper_block_bit'] = props['half'] === 'upper';
  if (has('head_piece_bit') && props['part']) states['head_piece_bit'] = props['part'] === 'head';
  if (has('upside_down_bit') && props['half'] && !has('weirdo_direction')) states['upside_down_bit'] = props['half'] === 'top';
  if (has('lit') && props['lit']) states['lit'] = props['lit'] === 'true';
  if (has('extinguished') && props['lit']) states['extinguished'] = props['lit'] !== 'true';
  if (has('candles') && props['candles']) states['candles'] = Math.max(0, Math.min(3, Number(props['candles']) - 1));
  if (has('cauldron_liquid') && id === 'water_cauldron') states['cauldron_liquid'] = 'water';
  if (has('fill_level') && props['level']) states['fill_level'] = Math.max(0, Math.min(6, Number(props['level']) * 2));
  if (has('composter_fill_level') && props['level']) states['composter_fill_level'] = Math.max(0, Math.min(8, Number(props['level'])));
  if (has('ground_sign_direction') && props['rotation']) states['ground_sign_direction'] = Math.max(0, Math.min(15, Number(props['rotation'])));

  // ── Walls: per-side connection, with Java's "low" spelled "short" ──────────
  for (const side of ['north', 'south', 'east', 'west'] as const) {
    const key = `wall_connection_type_${side}`;
    if (!has(key)) continue;
    const v = props[side];
    if (v && WALL_CONNECTION[v]) states[key] = WALL_CONNECTION[v]!;
  }
  if (has('wall_post_bit') && props['up']) states['wall_post_bit'] = props['up'] === 'true';

  // ── Pillars / logs: `axis` → `pillar_axis` ────────────────────────────────
  if (has('pillar_axis') && props['axis']) {
    const a = props['axis'];
    if (a === 'x' || a === 'y' || a === 'z') states['pillar_axis'] = a;
  }

  // ── Lanterns: `hanging` is a bool in both editions, same name ─────────────
  if (has('hanging') && props['hanging']) states['hanging'] = props['hanging'] === 'true';

  // ── Leaves: Java `persistent` → `persistent_bit` ──────────────────────────
  if (has('persistent_bit') && props['persistent']) {
    states['persistent_bit'] = props['persistent'] === 'true';
  }

  // ── Fluids: Java `level` → `liquid_depth` (same 0-15 meaning) ─────────────
  if (has('liquid_depth') && props['level']) {
    const lvl = Number(props['level']);
    if (Number.isInteger(lvl) && lvl >= 0 && lvl <= 15) states['liquid_depth'] = lvl;
  }

  // Java's pane / iron-bars / fence connection states (north/south/east/west)
  // are deliberately DROPPED: those blocks carry no such states in Bedrock,
  // which recomputes connections from the neighbours when the structure is
  // placed. Passing them through would make every permutation unresolvable.

  return { name: `minecraft:${bedrockId}`, states };
}

/**
 * Translate a whole palette, reporting gaps instead of hiding them.
 * `unmapped` is the list of Java entries with no Bedrock block.
 */
export function toBedrockPalette(entries: readonly string[]): {
  blocks: BedrockBlock[];
  unmapped: string[];
} {
  const blocks: BedrockBlock[] = [];
  const unmapped: string[] = [];
  for (const entry of entries) {
    const b = toBedrockBlock(entry);
    if (b) blocks.push(b);
    else { unmapped.push(entry); blocks.push({ name: 'minecraft:air', states: {} }); }
  }
  return { blocks, unmapped };
}

/** The Bedrock registry snapshot this mapping was generated from. */
export const BEDROCK_DATA_SOURCE: string = DATA._source;
