/**
 * BRICK-BUILT doors, gates, flaps and mechanisms: an assembly of ordinary
 * bricks that moves because it hangs on a joint that turns.
 *
 * A moulded door is found by its description (`interactiveKindOf`); a door
 * built from plates and tiles on two clips, or a castle gate on hinge bricks,
 * has no description to read. What it has is a JOINT: a finger hinge (3937 +
 * 6134, click hinges 44301/60471), a swivel hinge brick or plate (3830/3831,
 * 2429/2430), a clip on a bar, a turntable ring, a Technic pin or axle in a
 * round hole. The rule (docs/bedrock-interactivity.md, "Brick-built doors,
 * gates and mechanisms"):
 *
 *   1. Every placement's TURNING connectors come from LDCad's shadow library
 *      (`hinge-joint-snaps.ts`, generated by scripts/gen-hinge-joint-snaps.py).
 *      Two placements whose connectors are compatible (finger to finger of the
 *      same group, a clip on a bar, a male cylinder in a female one of the
 *      same radius) and lie on one line are a JOINT about that line. An axle in
 *      an axle hole is a joint that does not turn: a rigid connection.
 *   2. The model's RIGID connections: a stud of one part standing inside the
 *      other's box (a stacked brick, a SNOT plate on a bracket), a stud-group
 *      part's top face under another part's bottom face, a small part embedded
 *      in another (a pin, a bar, a clip), and every joint that does not turn.
 *   3. All the turning joints on one line are cut together (a door hangs on
 *      two hinges on one line). If that splits off an assembly - one no other
 *      connection holds to the rest of the model - the assembly MOVES about the
 *      line, and its side of each joint moves with it.
 *   4. The assembly is classed by its shape against the line, and every class
 *      was tightened by a visual review of what it found over the 40
 *      favourites (docs/bedrock-interactivity.md, "Brick-built doors, gates
 *      and mechanisms"): a PANEL (its parts cover half its outline) beside a
 *      vertical line, standing on a floor, is a door (a lintel over it) or a
 *      gate (none); one under a lintel but not on a floor, or too tall for a
 *      doorway, is a door leaf or hinged panel that swings with its collider
 *      kept. A flat panel (a lid) or a standing one on a level line (a flap)
 *      moves only on a hinge proper. A thick section on hinge bricks or plates
 *      is a WING when it swings out into free air and could not swing in. A
 *      mechanism turns a step per tap only on a turntable. A bar in a tube or
 *      a hollow stud swings nothing (railings, ladders, lamp posts), and
 *      mostly-Technic assemblies are a mechanism's insides.
 *
 * Nothing here names a set. A rule that finds nothing reports why for every
 * joint line it cut (`BrickHingeDiagnostics`), so the next rule is written
 * from evidence.
 */

import type { ParsedBrick } from './ldraw-parser.js';
import type { LdrawPartMesh, Vec3 } from './ldraw-part-geometry.js';
import { partStem } from './part-id.js';
import { HINGE_JOINT_SNAPS } from './hinge-joint-snaps.js';
// Values only read inside functions: bedrock-interactives.ts never imports this module
// (the interactivity stage calls both), so there is no import cycle.
import { DOORWAY_MIN_HEIGHT_LDU, OPEN_DEG, type InteractiveKind, type LeafPlane, type SceneInteractive } from './bedrock-interactives.js';

// ─── Joint table ─────────────────────────────────────────────────────────────

/** A turning connector in a part's own frame (`hinge-joint-snaps.ts`). */
export interface JointSnap {
  /** `f` finger hinge, `c` clip, `y` cylinder (pin, bar, hole, axle, ring). */
  kind: 'f' | 'c' | 'y';
  /** `M` male, `F` female, `X` genderless (fingers and clips). */
  gender: string;
  /** A cylinder's section shapes: `R` round, `A` axle, `AR` both. */
  shapes: string;
  radius: number;
  /** Length along the axis, LDU (a cylinder runs from `p` along `a`; a centred clip straddles `p`). */
  length: number;
  p: Vec3;
  a: Vec3;
  slides: boolean;
  centred: boolean;
  /** A finger hinge's LDCad group: only the same group interlocks. */
  group: string;
}

const unpacked = new Map<string, JointSnap[]>();
function unpack(packed: string): JointSnap[] {
  return packed.split(';').map(s => {
    const t = s.split(' ');
    const n = (i: number): number => Number(t[i]);
    return {
      kind: t[0] as JointSnap['kind'], gender: t[1]!, shapes: t[2] === '-' ? '' : t[2]!, radius: n(3), length: n(4),
      p: [n(5), n(6), n(7)], a: [n(8), n(9), n(10)], slides: t[11]!.includes('S'), centred: t[11]!.includes('C'), group: t[12] === '-' ? '' : t[12]!,
    };
  });
}

/**
 * A part's turning connectors: its own row, else its base mould's (a printed
 * `3001pb12`, a BrickLink `bl_3830`, a lettered `4085c` fall back to `3001`,
 * `3830`, `4085`), the order the LDCad resolver uses.
 */
export function jointSnapsOf(part: string): readonly JointSnap[] {
  const stem = partStem(part);
  const cached = unpacked.get(stem);
  if (cached) return cached;
  const cands = [stem];
  const bare = stem.startsWith('bl_') ? stem.slice(3) : stem;
  if (bare !== stem) cands.push(bare);
  const m = /^(\d+)([a-z])?/.exec(bare);
  if (m) { if (m[2]) cands.push(m[1]! + m[2]); cands.push(m[1]!); }
  let out: JointSnap[] = [];
  for (const c of cands) { const row = HINGE_JOINT_SNAPS[c]; if (row) { out = unpack(row); break; } }
  unpacked.set(stem, out);
  return out;
}

// ─── Small vector helpers ────────────────────────────────────────────────────

const IDENTITY: readonly number[] = [1, 0, 0, 0, 1, 0, 0, 0, 1];
const apply = (m: readonly number[], v: Vec3): Vec3 => [m[0]! * v[0] + m[1]! * v[1] + m[2]! * v[2], m[3]! * v[0] + m[4]! * v[1] + m[5]! * v[2], m[6]! * v[0] + m[7]! * v[1] + m[8]! * v[2]];
const add = (a: Vec3, b: Vec3): Vec3 => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const sub = (a: Vec3, b: Vec3): Vec3 => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const scale = (a: Vec3, k: number): Vec3 => [a[0] * k, a[1] * k, a[2] * k];
const dot = (a: Vec3, b: Vec3): number => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const cross = (a: Vec3, b: Vec3): Vec3 => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const len = (a: Vec3): number => Math.hypot(a[0], a[1], a[2]);
const norm = (a: Vec3): Vec3 => { const l = len(a) || 1; return [a[0] / l, a[1] / l, a[2] / l]; };
const toWorld = (b: ParsedBrick, v: Vec3): Vec3 => add([b.x, b.y, b.z], apply(b.rot ?? IDENTITY, v));

export interface Box { min: Vec3; max: Vec3 }
const overlapOn = (a: Box, b: Box, i: number): number => Math.min(a.max[i]!, b.max[i]!) - Math.max(a.min[i]!, b.min[i]!);
const inBox = (p: Vec3, b: Box, pad: number): boolean =>
  p[0] > b.min[0] + pad && p[0] < b.max[0] - pad && p[1] > b.min[1] + pad && p[1] < b.max[1] - pad && p[2] > b.min[2] + pad && p[2] < b.max[2] - pad;
const volume = (b: Box): number => Math.max(0, b.max[0] - b.min[0]) * Math.max(0, b.max[1] - b.min[1]) * Math.max(0, b.max[2] - b.min[2]);

/** Right-handed rotation of `p` by `deg` about the line through `pivot` along unit `axis` (Rodrigues). */
function rotateAbout(p: Vec3, pivot: Vec3, axis: Vec3, deg: number): Vec3 {
  const r = deg * Math.PI / 180, c = Math.cos(r), s = Math.sin(r);
  const v = sub(p, pivot);
  return add(pivot, add(add(scale(v, c), scale(cross(axis, v), s)), scale(axis, dot(axis, v) * (1 - c))));
}

// ─── Joints ──────────────────────────────────────────────────────────────────

/** Tolerances, LDU: how far off one line two connectors may sit and still be one joint. */
const LINE_TOLERANCE = 1.6;
/** Two cylinders mate when their radii differ by at most this (a 4 LDU bar in a 4 LDU clip, a pin in a hole). */
const RADIUS_TOLERANCE = 1.1;
/** Axes this close to parallel (|cos|) share a line. */
const PARALLEL = 0.985;

interface WorldSnap { brick: ParsedBrick; snap: JointSnap; p: Vec3; a: Vec3; from: number; to: number }

/** A connection between two placements through their connectors, about one line. */
export interface HingeJoint {
  a: ParsedBrick;
  b: ParsedBrick;
  /** A point on the joint's line and its unit direction, LDraw. */
  point: Vec3;
  axis: Vec3;
  /** Finger hinge, clip on a bar, or cylinder in cylinder. */
  type: 'finger' | 'clip' | 'cylinder';
  /** It can turn (an axle in an axle hole cannot). */
  turns: boolean;
  /** The radius the joint turns on, LDU: 4 a bar, 6 a Technic pin or axle, 7 and up a turntable ring (0 for fingers and clips). */
  radius: number;
}

/** The span a connector covers along its own axis, measured from its position: a centred one straddles it. */
function spanOf(s: JointSnap): [number, number] {
  const l = Math.max(s.length, 1);
  // LDCad lays a snap's sections from its position toward its local -Y (63965's bar
  // runs from its stop at y 18 up to its tip at y -102.5), i.e. against `a`.
  return s.centred ? [-l / 2, l / 2] : [-l, 0];
}

/** Distance from `p` to the line through `q` along unit `a`. */
const lineDistance = (p: Vec3, q: Vec3, a: Vec3): number => { const v = sub(p, q); return len(sub(v, scale(a, dot(v, a)))); };

/**
 * Every joint between two placements (`bricks`): compatible connectors on one
 * line whose spans overlap. Uses a spatial hash over connector positions.
 */
export function findHingeJoints(bricks: readonly ParsedBrick[]): HingeJoint[] {
  const snaps: WorldSnap[] = [];
  for (const b of bricks) {
    for (const s of jointSnapsOf(b.part)) {
      const R = b.rot ?? IDENTITY;
      const a = norm(apply(R, s.a));
      const [f, t] = spanOf(s);
      snaps.push({ brick: b, snap: s, p: toWorld(b, s.p), a, from: f, to: t });
    }
  }
  const CELL = 24;
  const cells = new Map<string, WorldSnap[]>();
  const key = (x: number, y: number, z: number): string => `${x},${y},${z}`;
  for (const w of snaps) {
    // Register along the connector's whole span so a long bar meets a clip anywhere on it.
    const steps = Math.max(1, Math.ceil((w.to - w.from) / CELL));
    const seen = new Set<string>();
    for (let i = 0; i <= steps; i++) {
      const q = add(w.p, scale(w.a, w.from + (w.to - w.from) * i / steps));
      const k = key(Math.floor(q[0] / CELL), Math.floor(q[1] / CELL), Math.floor(q[2] / CELL));
      if (seen.has(k)) continue;
      seen.add(k);
      const l = cells.get(k) ?? []; l.push(w); cells.set(k, l);
    }
  }
  const joints: HingeJoint[] = [];
  const done = new Set<string>();
  const ids = new Map<ParsedBrick, number>();
  bricks.forEach((b, i) => ids.set(b, i));
  for (const list of cells.values()) {
    for (let i = 0; i < list.length; i++) for (let j = i + 1; j < list.length; j++) {
      const u = list[i]!, v = list[j]!;
      if (u.brick === v.brick) continue;
      const c = Math.abs(dot(u.a, v.a));
      if (c < PARALLEL) continue;
      const mated = mate(u, v);
      if (!mated) continue;
      const ia = ids.get(u.brick)!, ib = ids.get(v.brick)!;
      const k = ia < ib ? `${ia}|${ib}|${mated.type}` : `${ib}|${ia}|${mated.type}`;
      if (done.has(k)) continue;
      done.add(k);
      joints.push({ a: u.brick, b: v.brick, point: mated.point, axis: u.a, type: mated.type, turns: mated.turns, radius: mated.radius });
    }
  }
  return joints;
}

/** Whether two connectors on (near) one line mate, and how. */
function mate(u: WorldSnap, v: WorldSnap): { type: HingeJoint['type']; turns: boolean; point: Vec3; radius: number } | null {
  const ku = u.snap.kind, kv = v.snap.kind;
  // Spans along u's axis: u's own, and v's projected onto it.
  const along = (w: WorldSnap, t: number): number => dot(sub(add(w.p, scale(w.a, t)), u.p), u.a);
  const overlap = (w: WorldSnap, slack: number): boolean => {
    const a0 = Math.min(along(w, w.from), along(w, w.to)), a1 = Math.max(along(w, w.from), along(w, w.to));
    return Math.min(a1, u.to) - Math.max(a0, u.from) > -slack;
  };
  if (ku === 'f' && kv === 'f') {
    if (u.snap.group && v.snap.group && u.snap.group !== v.snap.group) return null;
    if (lineDistance(v.p, u.p, u.a) > LINE_TOLERANCE || !overlap(v, 1)) return null;
    return { type: 'finger', turns: true, point: u.p, radius: 0 };
  }
  if ((ku === 'c' && kv === 'y') || (ku === 'y' && kv === 'c')) {
    const clip = ku === 'c' ? u : v, bar = ku === 'c' ? v : u;
    // A clip grips a 4 LDU bar (the bar's male cylinder, or a bar tube's).
    if (bar.snap.gender !== 'M' || Math.abs(bar.snap.radius - 4) > RADIUS_TOLERANCE) return null;
    if (lineDistance(clip.p, bar.p, bar.a) > LINE_TOLERANCE + 0.5) return null;
    const t = dot(sub(clip.p, bar.p), bar.a);
    if (t < bar.from - 4 || t > bar.to + 4) return null;
    return { type: 'clip', turns: true, point: clip.p, radius: 0 };
  }
  if (ku === 'y' && kv === 'y') {
    const genders = u.snap.gender + v.snap.gender;
    if (genders !== 'MF' && genders !== 'FM') return null;
    if (Math.abs(u.snap.radius - v.snap.radius) > RADIUS_TOLERANCE) return null;
    if (lineDistance(v.p, u.p, u.a) > LINE_TOLERANCE || !overlap(v, -1)) return null;
    const male = u.snap.gender === 'M' ? u : v, female = male === u ? v : u;
    // An axle in an axle hole is locked; a round pin, or an axle in a round hole, turns.
    const turns = !(male.snap.shapes.includes('A') && female.snap.shapes.includes('A'));
    return { type: 'cylinder', turns, point: female.p, radius: Math.min(male.snap.radius, female.snap.radius) };
  }
  return null;
}

// ─── Rigid connectivity ──────────────────────────────────────────────────────

/** A part this small (every side at most this, LDU) embedded in another is held by it: a pin, a bar, a clip, a 1 x 1. */
const SMALL_PART_LDU = 24;
/** How deep (LDU, every axis) a small part must sit inside another to count as held. */
const EMBED_LDU = 2;

export interface RigidGraph {
  /** Neighbours by rigid connection, per placement index. */
  edges: Array<Set<number>>;
  /** The first rule that linked each pair (`"i|j"`, i < j): `stud`, `stud group`, `embedded`, `joint <type>` - the diagnostics' answer to "what holds this door shut". */
  why: Map<string, string>;
}

/**
 * The model's rigid connections, over placement indices of `bricks`
 * (see the module comment, rule 2). `boxes[i]` is placement i's world box.
 */
export function rigidConnections(bricks: readonly ParsedBrick[], boxes: readonly Box[], meshes: ReadonlyArray<LdrawPartMesh | null>, descriptions: readonly string[], joints: readonly HingeJoint[]): RigidGraph {
  const n = bricks.length;
  const edges: Array<Set<number>> = Array.from({ length: n }, () => new Set<number>());
  const why = new Map<string, string>();
  const link = (i: number, j: number, reason: string): void => { if (i === j) return; edges[i]!.add(j); edges[j]!.add(i); const k = i < j ? `${i}|${j}` : `${j}|${i}`; if (!why.has(k)) why.set(k, reason); };
  const CELL = 40;
  const grid = new Map<string, number[]>();
  boxes.forEach((b, i) => {
    for (let x = Math.floor(b.min[0] / CELL); x <= Math.floor(b.max[0] / CELL); x++)
      for (let y = Math.floor(b.min[1] / CELL); y <= Math.floor(b.max[1] / CELL); y++)
        for (let z = Math.floor(b.min[2] / CELL); z <= Math.floor(b.max[2] / CELL); z++) {
          const k = `${x},${y},${z}`; const l = grid.get(k) ?? []; l.push(i); grid.set(k, l);
        }
  });
  const near = (p: Vec3): number[] => grid.get(`${Math.floor(p[0] / CELL)},${Math.floor(p[1] / CELL)},${Math.floor(p[2] / CELL)}`) ?? [];
  const neighbours = (b: Box): Set<number> => {
    const out = new Set<number>();
    for (let x = Math.floor((b.min[0] - 1) / CELL); x <= Math.floor((b.max[0] + 1) / CELL); x++)
      for (let y = Math.floor((b.min[1] - 1) / CELL); y <= Math.floor((b.max[1] + 1) / CELL); y++)
        for (let z = Math.floor((b.min[2] - 1) / CELL); z <= Math.floor((b.max[2] + 1) / CELL); z++)
          for (const j of grid.get(`${x},${y},${z}`) ?? []) out.add(j);
    return out;
  };
  const isTile = (d: string): boolean => /^(Tile|Roof Tile)\b|\b(No Studs|without Studs|Smooth)\b/i.test(d.replace(/^[~=_]+\s*/, ''));
  /**
   * Whether two parts sit square to each other (their relative rotation is a
   * signed permutation). A stud only holds a part pressed onto it square: a
   * leaf the source left swung 19 degrees open stands on the floor's studs
   * but is not on them (10354's round door), and a turntable's load is not
   * square to its base. The one-stud round parts that do turn on a stud are
   * not hinges this detector moves.
   */
  const aligned = (i: number, j: number): boolean => {
    const A = bricks[i]!.rot ?? IDENTITY, B = bricks[j]!.rot ?? IDENTITY;
    for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) {
      // (A^T B)[r][c]
      const v = A[r]! * B[c]! + A[3 + r]! * B[3 + c]! + A[6 + r]! * B[6 + c]!;
      const a = Math.abs(v);
      if (a > 0.03 && Math.abs(a - 1) > 0.03) return false;
    }
    return true;
  };
  for (let i = 0; i < n; i++) {
    const m = meshes[i], b = bricks[i]!, box = boxes[i]!;
    // 2a. A stud standing inside another part's box, the two square to each other.
    if (m && m.studs.length) {
      for (const s of m.studs) {
        const c = toWorld(b, s.center), u = norm(apply(b.rot ?? IDENTITY, s.up));
        const q = add(c, scale(u, 2));
        for (const j of near(q)) if (j !== i && inBox(q, boxes[j]!, 0.3) && aligned(i, j)) link(i, j, 'stud');
      }
    }
    for (const j of neighbours(box)) {
      if (j <= i) continue;
      const o = boxes[j]!;
      const ox = overlapOn(box, o, 0), oy = overlapOn(box, o, 1), oz = overlapOn(box, o, 2);
      // 2b. Stacked square: one part's top face meets the other's bottom face over
      // a stud's footprint, and the lower part has studs there. The mesh lists
      // the studs a part draws with `stud*.dat`; one whose studs are a `stug`
      // stud-group primitive (3010, 3958) lists none, so for it the description
      // decides (a tile or a stud-less brick holds nothing on top).
      const stacked = (lo: number, hi: number): boolean => {
        const lm = meshes[lo];
        if (!lm || Math.abs(boxes[lo]!.min[1] - boxes[hi]!.max[1]) > 1.2 || ox < 6 || oz < 6 || !aligned(lo, hi)) return false;
        const up = lm.studs.filter(s => apply(bricks[lo]!.rot ?? IDENTITY, s.up)[1] < -0.9);
        if (!up.length) return lm.studs.length === 0 && !isTile(descriptions[lo]!);
        const h = boxes[hi]!;
        return up.some(s => { const c = toWorld(bricks[lo]!, s.center); return c[0] > h.min[0] + 1 && c[0] < h.max[0] - 1 && c[2] > h.min[2] + 1 && c[2] < h.max[2] - 1; });
      };
      if (stacked(i, j) || stacked(j, i)) { link(i, j, 'stacked'); continue; }
      // 2c. A small part embedded in another (a pin in a beam, a bar in a hole, a clip on a plate).
      if (ox > EMBED_LDU && oy > EMBED_LDU && oz > EMBED_LDU) {
        const small = (k: number): boolean => { const bb = boxes[k]!; return bb.max[0] - bb.min[0] <= SMALL_PART_LDU + 0.5 && bb.max[1] - bb.min[1] <= SMALL_PART_LDU + 0.5 && bb.max[2] - bb.min[2] <= SMALL_PART_LDU + 0.5; };
        // Square to each other only: the box of a part turned off the grid (a leaf left
        // open) swells over its neighbours, which it does not touch.
        if ((small(i) || small(j)) && aligned(i, j)) link(i, j, 'embedded');
      }
    }
  }
  // 2d. Joints: every one that does not turn holds rigidly; the turning ones are the stage's to cut.
  const index = new Map<ParsedBrick, number>();
  bricks.forEach((b, i) => index.set(b, i));
  for (const jn of joints) {
    const i = index.get(jn.a), j = index.get(jn.b);
    if (i !== undefined && j !== undefined) link(i, j, `joint ${jn.type}`);
  }
  return { edges, why };
}

// ─── Assemblies ──────────────────────────────────────────────────────────────

/** Largest assembly the detector moves (placements): a castle gate, not a wing of the castle. */
export const MAX_HINGED_PARTS = 160;
/** Smallest: a single part on a clip is an ornament (a plant, a lamp), not a door. */
export const MIN_HINGED_PARTS = 2;

/** One joint line and what cutting it does (the diagnostics row). */
export interface HingeLine {
  /** The joints on the line and their type. */
  joints: HingeJoint[];
  point: Vec3;
  axis: Vec3;
  /** Placements (indices) on the side that moves, when the cut splits the model. */
  moving?: number[];
  /** The verdict and why. */
  verdict: 'moves' | 'holds' | 'too big' | 'too small' | 'rejected';
  reason: string;
}

/**
 * Group the turning joints by line (parallel, within `LINE_TOLERANCE` of each
 * other) and, for each line, cut every turning joint on it and find the side
 * that comes away: a connected set of placements, holding the moving half of
 * each joint, reached without crossing a cut joint, of at most
 * `MAX_HINGED_PARTS`. The other side must be bigger (the model).
 */
export function hingedAssemblies(bricks: readonly ParsedBrick[], graph: RigidGraph, joints: readonly HingeJoint[], blocked: ReadonlySet<number>, isPin: (i: number) => boolean = () => false): HingeLine[] {
  const index = new Map<ParsedBrick, number>();
  bricks.forEach((b, i) => index.set(b, i));
  const turning = joints.filter(j => j.turns);
  const lines: Array<{ joints: HingeJoint[]; point: Vec3; axis: Vec3 }> = [];
  for (const j of turning) {
    const line = lines.find(l => Math.abs(dot(l.axis, j.axis)) >= PARALLEL && lineDistance(j.point, l.point, l.axis) <= LINE_TOLERANCE * 2);
    if (line) line.joints.push(j); else lines.push({ joints: [j], point: j.point, axis: j.axis });
  }
  const out: HingeLine[] = [];
  for (const line of lines) {
    const cut = new Set<string>();
    for (const j of line.joints) { const a = index.get(j.a)!, b = index.get(j.b)!; cut.add(`${a}|${b}`); cut.add(`${b}|${a}`); }
    /** Placements reached from `start` without crossing a cut joint, up to `limit` (then null: the model). */
    const reach = (start: number, limit: number): number[] | null => {
      const seen = new Set<number>([start]);
      const queue = [start];
      while (queue.length) {
        const i = queue.shift()!;
        for (const j of graph.edges[i]!) {
          if (seen.has(j) || cut.has(`${i}|${j}`)) continue;
          seen.add(j); queue.push(j);
          if (seen.size > limit) return null;
        }
      }
      return [...seen];
    };
    // Each joint's two halves: the side that stays small is the one that moves.
    let moving: number[] | null = null;
    let reason = 'every joint on the line is held on both sides by other connections';
    let verdict: HingeLine['verdict'] = 'holds';
    for (const j of line.joints) {
      const a = index.get(j.a)!, b = index.get(j.b)!;
      const ra = reach(a, MAX_HINGED_PARTS * 4), rb = reach(b, MAX_HINGED_PARTS * 4);
      if (ra && rb && ra.includes(b)) continue; // still connected round the cut
      if (!ra && !rb) continue; // both sides are big: the joint is inside the model, held elsewhere
      let side = !ra ? rb! : !rb ? ra : (ra.length <= rb.length ? ra : rb);
      // A lone pin on the joint (a bar held by nothing but the door's own clips: 910004's
      // patchwork door, whose bar the source stands free in its frame) is the PIVOT, not the
      // thing that moves: the other side swings about it, when that side is small.
      const other = side === ra ? rb : ra;
      if (side.length === 1 && isPin(side[0]!) && line.joints.length >= 2 && other && other.length >= MIN_HINGED_PARTS && other.length <= MAX_HINGED_PARTS) side = other;
      else if (ra && rb && Math.min(ra.length, rb.length) * 2 > Math.max(ra.length, rb.length)) {
        verdict = 'rejected'; reason = `both sides are about the same size (${ra.length} and ${rb.length} parts): neither is the model`;
        continue;
      }
      if (side.length > MAX_HINGED_PARTS) { verdict = 'too big'; reason = `the side that comes away is ${side.length} parts (over ${MAX_HINGED_PARTS})`; continue; }
      if (side.length < MIN_HINGED_PARTS) { verdict = 'too small'; reason = 'a single part on the joint (an ornament, not an assembly)'; continue; }
      if (side.some(i => blocked.has(i))) { verdict = 'rejected'; reason = 'the side that comes away holds a part another rule owns (a moulded door, a seat)'; continue; }
      moving = moving ? [...new Set([...moving, ...side])] : side;
      verdict = 'moves'; reason = '';
    }
    out.push({ joints: line.joints, point: line.point, axis: line.axis, ...(moving ? { moving } : {}), verdict: moving ? 'moves' : verdict, reason: moving ? '' : reason });
  }
  return out;
}

// ─── Shape ───────────────────────────────────────────────────────────────────

/** An assembly measured against its joint line (`hingedShape`), LDU. */
export interface HingedShape {
  /** A slab on one side of its line, or anything else. */
  cls: 'leaf' | 'mechanism';
  /** Unit direction from the line to the assembly's middle (perpendicular to the line), and the leaf's normal. */
  along: Vec3;
  normal: Vec3;
  /** How far it reaches along `along` from the line, and behind it (negative). */
  width: number;
  back: number;
  /** Its extent across (along `normal`) and the middle of that span. */
  thickness: number;
  tMid: number;
  /** Its span along the line, from the line's point. */
  lineFrom: number;
  lineTo: number;
  /** The farthest any of it reaches from the line. */
  radius: number;
}

/** A leaf's thickness may be at most this share of its width (a door of bricks 1 stud thick, with handles). */
const LEAF_THIN = 0.55;
/** A knuckle or a hinge half may reach this far behind the line and it is still a leaf beside it. */
const LEAF_BACK_LDU = 14;

/**
 * Measure an assembly (`points`: every part's oriented-box corners; `centres`:
 * every part's box centre) against its line (`point`, unit `axis`). A slab
 * beside its line - it starts at the line, reaches out at least 20 LDU and is
 * thin across - is a LEAF; anything else a mechanism.
 */
export function hingedShape(points: readonly Vec3[], centres: readonly Vec3[], point: Vec3, axis: Vec3): HingedShape {
  const perp = (p: Vec3): Vec3 => { const v = sub(p, point); return sub(v, scale(axis, dot(v, axis))); };
  const mean = scale(centres.reduce((s, c) => add(s, perp(c)), [0, 0, 0] as Vec3), 1 / Math.max(1, centres.length));
  const alongs = points.map(p => dot(sub(p, point), axis));
  const lineFrom = Math.min(...alongs), lineTo = Math.max(...alongs);
  const radius = Math.max(...points.map(p => len(perp(p))));
  // Balanced round the line (a rotor, a turntable's load): no side to be a leaf on.
  const fallback = norm(Math.abs(axis[1]) < 0.9 ? cross(axis, [0, 1, 0]) : cross(axis, [1, 0, 0]));
  // The leaf's own direction is its LONG axis across the line (the major axis of its
  // corners projected on the plane square to the line), pointed at its middle: the
  // direction to the middle alone leans towards the side its handles stand on
  // (80049's square doors read 6.4 degrees off the grid).
  const e1 = fallback, e2 = norm(cross(axis, e1));
  let sxx = 0, sxy = 0, syy = 0, mx = 0, my = 0;
  const flat = points.map(p => { const v = perp(p); return [dot(v, e1), dot(v, e2)] as const; });
  for (const [x, y] of flat) { mx += x; my += y; }
  mx /= flat.length; my /= flat.length;
  for (const [x, y] of flat) { sxx += (x - mx) ** 2; sxy += (x - mx) * (y - my); syy += (y - my) ** 2; }
  const theta = 0.5 * Math.atan2(2 * sxy, sxx - syy);
  let major = norm(add(scale(e1, Math.cos(theta)), scale(e2, Math.sin(theta))));
  if (dot(major, mean) < 0) major = scale(major, -1);
  const along = len(mean) >= 4 ? major : fallback, normal = norm(cross(axis, along));
  const ws = points.map(p => dot(perp(p), along)), ts = points.map(p => dot(perp(p), normal));
  const width = Math.max(...ws), back = Math.min(...ws);
  const thickness = Math.max(...ts) - Math.min(...ts), tMid = (Math.max(...ts) + Math.min(...ts)) / 2;
  const leaf = len(mean) >= 4 && back >= -LEAF_BACK_LDU && width >= 20 && thickness <= Math.max(14, LEAF_THIN * width);
  return { cls: leaf ? 'leaf' : 'mechanism', along, normal, width, back, thickness, tMid, lineFrom, lineTo, radius };
}

// ─── Discovery ───────────────────────────────────────────────────────────────

/** A mechanism turns only if at most this share of its samples lands in the model when turned (the sweep). */
const SWEEP_FREE = 0.15;
/** A leaf that lands this much of itself in the model both ways cannot open. */
const LEAF_SWEEP_BLOCKED = 0.34;
/** A mechanism is worth an entity from this many parts and this reach (LDU): not a lamp on a clip. */
const MECHANISM_MIN_PARTS = 5;
const MECHANISM_MIN_RADIUS = 32;
/** What may move, as a share of the scenery: a door, not a wing of the building. */
const MAX_SHARE = 0.12;
/** A gate with no lintel needs this height (LDU) to be a passage; shorter it is a cupboard door or a shutter. */
const GATE_MIN_HEIGHT_LDU = 48;
/** A leaf is at least this wide and tall (LDU: a stud and a half) and at most this thick (a brick and handles). */
const LEAF_MIN_LDU = 30;
const LEAF_MAX_THICK_LDU = 26;
/** How much of a leaf's outline its parts must cover, face on (a panel, not struts). */
const LEAF_COVER = 0.5;
/** A one-way hinged section (a wall wing) is at least this many parts. */
const SECTION_MIN_PARTS = 12;
/** A wing's sweep: at most this share of it in the model swung out, at least this share swung in. */
const SECTION_OUT_MAX = 0.02;
const SECTION_IN_MIN = 0.25;
/** A flap or a lid is at least this much each way (LDU: two studs). */
const FLAP_MIN_LDU = 40;
/** What a leaf or a hinged section is built from: at least half its parts (joint halves aside). */
const STRUCTURAL = /^(Plate|Tile|Brick|Panel|Slope|Wedge|Door|Window|Glass|Fence|Lattice|Wall|Arch|Roof|Hinge|Technic,? (Brick|Beam|Liftarm|Plate|Panel)|Wood|Cylinder Half)\b/i;

export interface BrickHingeInput {
  /** The scenery's placements (not figures, vehicles, rides). */
  bricks: readonly ParsedBrick[];
  meshOf: (b: ParsedBrick) => LdrawPartMesh | null;
  /** Placements other rules own (moulded doors and their inserts, seats): an assembly holding one never moves. */
  taken: ReadonlySet<ParsedBrick>;
}

/** One joint line in the report: where, how it is joined, and what became of it. */
export interface HingeLineReport {
  /** Joint moulds and type (`3830/3831 cylinder`). */
  joint: string;
  verdict: 'moves' | 'holds' | 'too big' | 'too small' | 'rejected';
  reason: string;
  /** Parts on the side that came away (0 when nothing did). */
  parts: number;
  /** What it became. */
  kind?: InteractiveKind;
  /** And what it is called (door, gate, door leaf, shutter, flap, drop-down flap, lid, hinged section, mechanism). */
  noun?: string;
  /** The line's point, LDraw (to find it in a render). */
  at: Vec3;
}

export interface BrickHingeResult {
  items: SceneInteractive[];
  lines: HingeLineReport[];
}

/** The eight corners of a placement's oriented part box, LDraw. */
function orientedCorners(b: ParsedBrick, m: LdrawPartMesh): Vec3[] {
  const { min, max } = m.bounds;
  const out: Vec3[] = [];
  for (const x of [min[0], max[0]]) for (const y of [min[1], max[1]]) for (const z of [min[2], max[2]]) out.push(toWorld(b, [x, y, z]));
  return out;
}
function aabbOf(points: readonly Vec3[]): Box {
  const min: Vec3 = [Infinity, Infinity, Infinity], max: Vec3 = [-Infinity, -Infinity, -Infinity];
  for (const p of points) for (let i = 0; i < 3; i++) { if (p[i]! < min[i]!) min[i] = p[i]!; if (p[i]! > max[i]!) max[i] = p[i]!; }
  return { min, max };
}
const offGridOf = (v: Vec3): number => { const fromX = Math.atan2(Math.abs(v[2]), Math.abs(v[0])) * 180 / Math.PI; return Math.round(Math.min(fromX, 90 - fromX) * 10) / 10; };

/**
 * Find every brick-built door, gate, flap and mechanism (module comment):
 * joints from the table, the rigid graph, a cut per joint line, and the
 * assembly that comes away classed by its shape and checked by a sweep. Every
 * line cut is reported, moved or not, with the reason.
 */
export function discoverBrickHinges(input: BrickHingeInput): BrickHingeResult {
  const bricks: ParsedBrick[] = [], meshes: LdrawPartMesh[] = [];
  for (const b of input.bricks) { const m = input.meshOf(b); if (m) { bricks.push(b); meshes.push(m); } }
  const corners = bricks.map((b, i) => orientedCorners(b, meshes[i]!));
  const boxes = corners.map(aabbOf);
  const joints = findHingeJoints(bricks);
  if (!joints.some(j => j.turns)) return { items: [], lines: [] };
  const graph = rigidConnections(bricks, boxes, meshes, meshes.map(m => m.description), joints);
  const blocked = new Set<number>();
  bricks.forEach((b, i) => { if (input.taken.has(b)) blocked.add(i); });
  const index = new Map<ParsedBrick, number>();
  bricks.forEach((b, i) => index.set(b, i));
  // The share binds only a big model: a small one may still hang a 24-part door.
  const maxParts = Math.min(MAX_HINGED_PARTS, Math.max(24, Math.floor(bricks.length * MAX_SHARE)));
  const items: SceneInteractive[] = [];
  const lines: HingeLineReport[] = [];
  const claimed = new Set<number>();
  // A bar or a Technic pin or axle: what a leaf's clips or holes turn about.
  const PIN = /^(Bar\b|Technic,? (Axle|Pin)\b)/i;
  for (const line of hingedAssemblies(bricks, graph, joints, blocked, i => PIN.test(meshes[i]!.description.replace(/^[~=_]+\s*/, '')))) {
    const joint = `${[...new Set(line.joints.map(j => `${partStem(j.a.part)}/${partStem(j.b.part)}`))].join(', ')} ${line.joints[0]!.type}`;
    const at: Vec3 = [Math.round(line.point[0]), Math.round(line.point[1]), Math.round(line.point[2])];
    const report = (verdict: HingeLineReport['verdict'], reason: string, parts = 0, kind?: InteractiveKind, noun?: string): void => { lines.push({ joint, verdict, reason, parts, at, ...(kind ? { kind } : {}), ...(noun ? { noun } : {}) }); };
    if (!line.moving) { report(line.verdict, line.reason); continue; }
    const moving = line.moving;
    if (moving.length > maxParts) { report('too big', `the side that comes away is ${moving.length} parts, over ${maxParts} (${Math.round(MAX_SHARE * 100)} percent of the scenery or ${MAX_HINGED_PARTS})`, moving.length); continue; }
    if (moving.some(i => claimed.has(i))) { report('rejected', 'it shares parts with an assembly already moving on another line', moving.length); continue; }
    const set = new Set(moving);
    // The moving half of each cut joint leads the assembly (it names the entity).
    const halves = line.joints.map(j => (set.has(index.get(j.a)!) ? j.a : j.b));
    const fixedHalves = new Set(line.joints.map(j => index.get(set.has(index.get(j.a)!) ? j.b : j.a)!));
    const pts = moving.flatMap(i => corners[i]!);
    const centres = moving.map(i => scale(add(boxes[i]!.min, boxes[i]!.max), 0.5));
    const axis = norm(line.axis);
    const shape = hingedShape(pts, centres, line.point, axis);
    // The sweep: each part's centre and its corners pulled a quarter in, turned about the line.
    const samples = moving.flatMap(i => { const c = centres[moving.indexOf(i)]!; return [c, ...corners[i]!.map(p => add(c, scale(sub(p, c), 0.75)))]; });
    const bound = aabbOf(pts), reachLdu = shape.radius + 8;
    const obstacles = boxes.filter((bb, i) => !set.has(i) && !fixedHalves.has(i)
      && bb.max[0] > line.point[0] - reachLdu - (bound.max[0] - bound.min[0]) && bb.min[0] < line.point[0] + reachLdu + (bound.max[0] - bound.min[0])
      && bb.max[1] > bound.min[1] - reachLdu && bb.min[1] < bound.max[1] + reachLdu
      && bb.max[2] > line.point[2] - reachLdu - (bound.max[2] - bound.min[2]) && bb.min[2] < line.point[2] + reachLdu + (bound.max[2] - bound.min[2]));
    // What the closed assembly already sits in (a leaf in its frame's box) does not count against it.
    const free = obstacles.filter(bb => !samples.some(p => inBox(p, bb, 1)));
    const hits = (deg: number): number => samples.reduce((n, p) => n + (free.some(bb => inBox(rotateAbout(p, line.point, axis, deg), bb, 1)) ? 1 : 0), 0);
    const share = (deg: number): number => hits(deg) / samples.length;
    // What turns something that is not a leaf: a Technic pin or axle in its hole, a
    // turntable ring, a hinge brick's or plate's pivot. A bar standing in a hollow stud
    // turns too (a lamp post, a railing, a flag), but it is not a mechanism.
    const named = (b: ParsedBrick): boolean => /\b(Hinge|Turntable)\b/i.test(meshes[index.get(b)!]!.description);
    const cylinder = line.joints.some(j => j.type === 'cylinder' && (j.radius >= 5.5 || named(j.a) || named(j.b)));
    // A HINGE proper: finger hinges and the named hinge and turntable parts. A clip on a
    // bar hangs doors and gates too (80049, 910004, 910047). A bar in a bar tube or a
    // hollow stud is how railings, ladders and lamp posts stand (10341's launch tower
    // read as twenty "lids" on them): it swings nothing here.
    const hinge = line.joints.some(j => j.type === 'finger' || (j.type === 'cylinder' && (named(j.a) || named(j.b))));
    const clipped = line.joints.some(j => j.type === 'clip');
    if (!hinge && !clipped && !cylinder) { report('rejected', 'a bar in a tube or a hollow stud: structure (a railing, a ladder, a post), not a hinge', moving.length); continue; }
    const sideOf = (): { sign: number; best: number } => { const p = share(90), m = share(-90); return p <= m ? { sign: 1, best: p } : { sign: -1, best: m }; };
    let kind: InteractiveKind;
    let noun: string;
    let angle: number;
    let leaf: LeafPlane | undefined;
    let opening: { width: number; height: number } | undefined;
    let sweepShares: { chosen: number; other: number } | undefined;
    const lineLen = shape.lineTo - shape.lineFrom;
    const vertical = Math.abs(axis[1]) >= 0.85;
    // What it is built from: a panel of plates, tiles, bricks and panels, not a
    // lantern, a flame or a plume on a clip (the joint halves themselves aside).
    const body = moving.filter(i => !halves.includes(bricks[i]!));
    const structural = body.filter(i => STRUCTURAL.test(meshes[i]!.description.replace(/^[~=_]+\s*/, ''))).length;
    const builtUp = body.length > 0 && structural * 2 >= body.length;
    if (shape.cls === 'leaf' && (shape.width < LEAF_MIN_LDU || lineLen < LEAF_MIN_LDU)) {
      report('too small', `a leaf ${Math.round(shape.width)} x ${Math.round(lineLen)} LDU: under ${LEAF_MIN_LDU} x ${LEAF_MIN_LDU} (an ornament or a trim)`, moving.length);
      continue;
    }
    // A slab thicker than a brick and its handles is a hinged SECTION (a wall wing), judged as one below.
    if (shape.cls === 'leaf' && shape.thickness <= LEAF_MAX_THICK_LDU) {
      if (!builtUp) { report('rejected', `a leaf of ${body.length} parts, ${structural} of them plates, tiles, bricks or panels: an ornament on a hinge`, moving.length); continue; }
      // A leaf is a PANEL: its parts, seen face on, cover at least half of its outline.
      // Struts, railings and a mirror on its arm are lines, not panels (10341's tower
      // struts and 42172's mirrors on clips read as doors before this).
      const faceOf = (i: number): number => {
        const c = corners[i]!;
        const a = c.map(p => dot(sub(p, line.point), shape.along)), u = c.map(p => dot(sub(p, line.point), axis));
        return (Math.max(...a) - Math.min(...a)) * (Math.max(...u) - Math.min(...u));
      };
      const cover = body.reduce((n, i) => n + faceOf(i), 0) / Math.max(1, shape.width * lineLen);
      if (cover < LEAF_COVER) { report('rejected', `its parts cover ${Math.round(cover * 100)} percent of its outline: struts or a frame, not a panel`, moving.length); continue; }
      const alongY = shape.along[1];
      if (vertical) {
        const { sign, best } = sideOf();
        if (best > LEAF_SWEEP_BLOCKED) { report('rejected', `a leaf that cannot swing: ${Math.round(best * 100)} percent of it lands in the model either way`, moving.length); continue; }
        // A lintel: a part over the leaf's top, within a brick and a half.
        const top = bound.min[1];
        const lintel = boxes.some((bb, i) => !set.has(i) && !fixedHalves.has(i) && bb.max[1] <= top + 1 && bb.max[1] >= top - 36
          && overlapOn(bb, bound, 0) > 4 && overlapOn(bb, bound, 2) > 4);
        // A floor: a door or a gate stands on something, within a plate and a half of its foot
        // (a car's mirror on its clip is as tall as a door but hangs in the air).
        const foot = bound.max[1];
        const floored = boxes.some((bb, i) => !set.has(i) && bb.min[1] >= foot - 2 && bb.min[1] <= foot + 24
          && overlapOn(bb, bound, 0) > 4 && overlapOn(bb, bound, 2) > 4);
        // A doorway's leaf is at most 3.5 times as tall as it is wide: a panel two floors tall on
        // a tower's hinges (11371) is a hinged facade, not a doorway to cut into the walls.
        const doorShaped = lineLen <= 3.5 * shape.width;
        if (lineLen >= DOORWAY_MIN_HEIGHT_LDU && shape.width >= 30 && lintel && floored && doorShaped) { kind = 'door'; noun = 'door'; }
        else if (!lintel && floored && doorShaped && lineLen >= GATE_MIN_HEIGHT_LDU && shape.width >= 30) { kind = 'gate'; noun = 'gate'; }
        else if (lintel && lineLen >= DOORWAY_MIN_HEIGHT_LDU && moving.length >= 4) { kind = 'cabinet'; noun = doorShaped ? 'door leaf' : 'hinged panel'; }
        else {
          // A short leaf, or a tall one with neither a floor nor a lintel: in the review every
          // one was a mirror, a sign or a trim on its clip, not a shutter (docs/bedrock-interactivity.md).
          report('rejected', `a leaf ${Math.round(shape.width)} x ${Math.round(lineLen)} LDU ${floored ? 'on a floor' : 'in the air'} ${lintel ? 'under a lintel' : 'with nothing over it'}: not a door or a gate, and no shutter rule tells a shutter from a trim yet`, moving.length);
          continue;
        }
        angle = sign * OPEN_DEG[kind === 'cabinet' ? 'door' : kind];
        if (kind === 'door' || kind === 'gate') opening = { width: shape.width, height: lineLen };
      } else if (Math.abs(alongY) >= 0.7) {
        // Standing on a horizontal line: hung from its top edge (it hangs DOWN, LDraw +Y) or its bottom.
        const { sign, best } = sideOf();
        if (best > LEAF_SWEEP_BLOCKED) { report('rejected', `a flap that cannot swing: ${Math.round(best * 100)} percent of it lands in the model either way`, moving.length); continue; }
        // Like a lid, a flap hangs on a hinge proper: on clips and pins the review found only
        // roof wedges, pipes and signs (docs/bedrock-interactivity.md).
        if (!hinge) { report('rejected', 'a standing panel on clips or pins (a sign, a trim): a flap hangs on a hinge', moving.length); continue; }
        // A flap is a panel: two parts at least besides its hinge half, and a stud and a half each way.
        if (body.length < 2 || shape.width < FLAP_MIN_LDU || lineLen < FLAP_MIN_LDU) { report('too small', `a flap of ${body.length} parts, ${Math.round(shape.width)} x ${Math.round(lineLen)} LDU: a trim or a sign, not a panel`, moving.length); continue; }
        if (alongY > 0) { kind = 'window'; noun = 'flap'; angle = sign * OPEN_DEG.window; }
        else { kind = 'cabinet'; noun = 'drop-down flap'; angle = sign * 90; }
      } else {
        // Lying flat: a lid, its free edge rises. Only on a hinge proper: a flat panel on
        // clips or pins is a shelf, an awning or a sign far more often than a lid.
        if (!hinge) { report('rejected', 'a flat panel on clips or pins (a shelf, an awning, a sign): a lid hangs on a hinge', moving.length); continue; }
        if (body.length < 2 || shape.width < FLAP_MIN_LDU || lineLen < FLAP_MIN_LDU) { report('too small', `a lid of ${body.length} parts, ${Math.round(shape.width)} x ${Math.round(lineLen)} LDU: a trim, not a lid`, moving.length); continue; }
        const free = add(line.point, scale(shape.along, shape.width));
        const sign = rotateAbout(free, line.point, axis, 90)[1] <= rotateAbout(free, line.point, axis, -90)[1] ? 1 : -1;
        const blockedUp = share(sign * OPEN_DEG.lid);
        if (blockedUp > LEAF_SWEEP_BLOCKED) { report('rejected', `a lid that cannot lift: ${Math.round(blockedUp * 100)} percent of it lands in the model`, moving.length); continue; }
        kind = 'lid'; noun = 'lid'; angle = sign * OPEN_DEG.lid;
      }
      // The closed leaf's mid-plane: from the hinge line out to the free edge, along the line for its height.
      const lineAt = (t: number): Vec3 => add(line.point, scale(axis, t));
      const [from, to] = vertical && axis[1] > 0 ? [shape.lineTo, shape.lineFrom] : [shape.lineFrom, shape.lineTo];
      const corner = add(lineAt(from), scale(shape.normal, shape.tMid));
      leaf = { corner, along: scale(shape.along, shape.width), up: scale(sub(lineAt(to), lineAt(from)), 1), normal: shape.normal, thicknessLdu: shape.thickness };
    } else {
      if (!cylinder) { report('rejected', 'not a leaf, and a clip, a finger hinge or a bar only swings a leaf (an ornament on a hinge)', moving.length); continue; }
      if (moving.length < MECHANISM_MIN_PARTS || shape.radius < MECHANISM_MIN_RADIUS) { report('too small', `a mechanism of ${moving.length} parts reaching ${Math.round(shape.radius)} LDU: an ornament, not worth an entity`, moving.length); continue; }
      // Mostly Technic parts turning on Technic pins are a mechanism's INSIDES (a lift's
      // gears, a pinball table's linkage, a supercar's suspension), not a thing a player turns.
      const technic = body.filter(i => /^Technic\b/i.test(meshes[i]!.description.replace(/^[~=_]+\s*/, ''))).length;
      if (technic * 2 > body.length) { report('rejected', `${technic} of its ${body.length} parts are Technic: a mechanism's insides, not a thing a player turns`, moving.length); continue; }
      const p90 = share(90), m90 = share(-90), half = share(180);
      if (Math.min(p90, m90) > SWEEP_FREE) { report('rejected', `turning it sweeps through the model (${Math.round(Math.min(p90, m90) * 100)} percent of it at a quarter turn)`, moving.length); continue; }
      if (p90 <= SWEEP_FREE && m90 <= SWEEP_FREE && half <= SWEEP_FREE) {
        // Free all round. Only a TURNTABLE says it is meant to turn: on a pin or an axle
        // the review found a cart's wheel, a davit and a lift's linkage beside the rare
        // windmill (docs/bedrock-interactivity.md), and no rule tells them apart yet.
        if (!line.joints.some(j => /\bTurntable\b/i.test(meshes[index.get(j.a)!]!.description) || /\bTurntable\b/i.test(meshes[index.get(j.b)!]!.description))) {
          report('rejected', 'free to turn on a pin or an axle, but nothing says it is meant to (a wheel, a boom, a linkage): only a turntable makes a brick-built mechanism', moving.length);
          continue;
        }
        kind = 'turnable'; noun = 'mechanism'; angle = OPEN_DEG.turnable;
      } else {
        // A section swings on a hinge proper (a wall wing on hinge bricks or plates), with some size to it.
        // A LEVEL hinge set at an angle (not a quarter-turn multiple between its halves) is an
        // ANGLE joint: a sloped roof or a ramp (10261's lift deck in the review). An upright
        // hinge set at an angle is a wing the source left open (41395's bus sides).
        const j0 = line.joints[0]!, R0 = j0.a.rot ?? IDENTITY, R1 = j0.b.rot ?? IDENTITY;
        const square = [0, 1, 2].every(r => [0, 1, 2].every(c => { const v = Math.abs(R0[r]! * R1[c]! + R0[3 + r]! * R1[3 + c]! + R0[6 + r]! * R1[6 + c]!); return v < 0.05 || v > 0.95; }));
        if (!square && !vertical) { report('rejected', 'its level hinge is set at an angle: an angle joint (a sloped roof, a ramp), not a section that swings', moving.length); continue; }
        if (!hinge || moving.length < SECTION_MIN_PARTS) { report('rejected', `a one-way section of ${moving.length} parts on ${hinge ? 'a hinge' : 'clips or pins'}: a section is at least ${SECTION_MIN_PARTS} parts on hinge bricks or plates`, moving.length); continue; }
        // A section that swings one way only: a wall wing, a fold-out side. It is building, not a flag on a pin.
        if (!builtUp) { report('rejected', `a hinged section of ${body.length} parts, ${structural} of them plates, tiles, bricks or panels: an ornament on a hinge`, moving.length); continue; }
        // A wing swings OUT into free air and could not swing in: the way out clear, the way
        // in through the model (41395's bus sides: 0 and 27-46 percent). A piece of a lattice
        // or a railing brushes something either way (10261 0/19 and 6/10, 910049 8/44).
        const out = Math.min(p90, m90), into = Math.max(p90, m90);
        if (out > SECTION_OUT_MAX || into < SECTION_IN_MIN) { report('rejected', `swung a quarter turn it lands ${Math.round(out * 100)} and ${Math.round(into * 100)} percent in the model: not a wing that swings out of it`, moving.length); continue; }
        kind = 'cabinet'; noun = 'hinged section'; angle = (p90 <= m90 ? 1 : -1) * 90;
        sweepShares = { chosen: Math.min(p90, m90), other: Math.max(p90, m90) };
      }
    }
    for (const i of moving) claimed.add(i);
    const assembly = [...halves.filter((b, k) => halves.indexOf(b) === k), ...moving.map(i => bricks[i]!).filter(b => !halves.includes(b))];
    const lo = line.point, mid = add(lo, scale(axis, (shape.lineFrom + shape.lineTo) / 2));
    const description = `Brick-built ${noun} (${moving.length} parts on ${line.joints.length} ${line.joints[0]!.type} joint${line.joints.length === 1 ? '' : 's'}, ${[...new Set(line.joints.map(j => partStem(j.a.part) + '/' + partStem(j.b.part)))].join(', ')})`;
    items.push({
      kind, part: partStem(halves[0]!.part), description, bricks: assembly,
      pivotLdu: mid, axisLdu: axis, angleDeg: angle, ...(leaf ? { leaf } : {}),
      anchorLdu: [(bound.min[0] + bound.max[0]) / 2, bound.max[1], (bound.min[2] + bound.max[2]) / 2], boundsLdu: bound,
      ...(opening ? { openingLdu: opening } : {}), offGridDeg: leaf && vertical ? offGridOf(leaf.along) : 0,
      builtFrom: description, ...(sweepShares ? { sweep: { chosen: Math.round(sweepShares.chosen * 100), other: Math.round(sweepShares.other * 100) } } : {}),
    });
    void lo;
    report('moves', '', moving.length, kind, noun);
  }
  return { items, lines };
}

export { rotateAbout as _rotateAboutForTests, volume as _volumeForTests };
