/**
 * LDraw colour → Bedrock entity material.
 *
 * The entity path never goes through Minecraft block colours: every solid
 * colour is the LDraw RGB itself, and the material CLASS (ABS, transparent,
 * rubber, chrome, metallic, pearl, glow) comes from LDConfig's finish keywords
 * (`ldraw-color-classes.json`, generated by scripts/gen-ldraw-color-classes.mjs
 * from the deployed library's LDConfig.ldr).
 *
 * RGB precedence: `LDRAW_COLOR_RGB` first — it is what the 3D viewer renders,
 * so a model looks the same on screen and in the game — then the generated
 * table (the current LDConfig re-tuned several values, e.g. Red 4 is #B40000
 * there and #C91A09 in the viewer; moving the whole app to the new values is a
 * separate, deliberate step). Alpha, luminance and finish always come from the
 * generated table. Direct colours (`0x2RRGGBB` opaque, `0x3RRGGBB`
 * transparent) are decoded exactly.
 *
 * PBR responses per class live in ONE table (`MATERIAL_PBR`) so the atlas, the
 * classic fallback and any future tuning read the same numbers.
 */

import { LDRAW_COLOR_RGB } from './ldraw-colors.js';
import colorClasses from './ldraw-color-classes.json' with { type: 'json' };

export type LegoMaterialClass = 'abs' | 'transparent' | 'rubber' | 'chrome' | 'metallic' | 'pearl' | 'glow';

export interface LdrawEntityMaterial {
  colorId: number;
  rgb: [number, number, number];
  /** 0..1; < 1 renders through the translucent (alpha-blended) mesh. */
  alpha: number;
  materialClass: LegoMaterialClass;
  /** 0..1 — MER red channel. */
  metalness: number;
  /** 0..1 — MER green channel. */
  emissive: number;
  /** 0..1 — MER blue channel. */
  roughness: number;
  /** False when the id is in no table: the colour is a neutral grey stand-in. */
  known: boolean;
}

interface ColorClassEntry {
  name: string;
  rgb: string;
  alpha?: number;
  luminance?: number;
  finish?: 'chrome' | 'pearl' | 'rubber' | 'matte_metallic' | 'metal' | 'glitter' | 'speckle';
}

const CLASSES: Record<string, ColorClassEntry> = (colorClasses as { colours: Record<string, ColorClassEntry> }).colours;

/** Surface response per class; roughness 0.36 for ABS matches the viewer's material. */
export const MATERIAL_PBR: Record<LegoMaterialClass, { metalness: number; roughness: number; emissive: number }> = {
  abs: { metalness: 0, roughness: 0.36, emissive: 0 },
  transparent: { metalness: 0, roughness: 0.08, emissive: 0 },
  rubber: { metalness: 0, roughness: 0.85, emissive: 0 },
  chrome: { metalness: 1, roughness: 0.1, emissive: 0 },
  metallic: { metalness: 0.9, roughness: 0.35, emissive: 0 },
  pearl: { metalness: 0.35, roughness: 0.3, emissive: 0 },
  glow: { metalness: 0, roughness: 0.5, emissive: 0.6 },
};

/** Alpha used for a transparent colour whose table entry carries none (direct 0x3 colours). */
const DEFAULT_TRANSPARENT_ALPHA = 128 / 255;

/**
 * Studio/BrickLink extended ids (10000+) are not in LDConfig. The viewer's
 * rules for them: 10000–10999 render as rubber, and a handful are transparent.
 */
const STUDIO_TRANSPARENT = new Set([10035, 10036, 10043, 10351, 10366, 10375]);

const hexToRgb = (hex: string): [number, number, number] => [
  parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16),
];

const cache = new Map<number, LdrawEntityMaterial>();

export function resolveLdrawEntityMaterial(colorId: number): LdrawEntityMaterial {
  const hit = cache.get(colorId);
  if (hit) return hit;
  const m = build(colorId);
  cache.set(colorId, m);
  return m;
}

function build(colorId: number): LdrawEntityMaterial {
  const finish = (cls: LegoMaterialClass, rgb: [number, number, number], alpha: number, known: boolean): LdrawEntityMaterial =>
    ({ colorId, rgb, alpha, materialClass: cls, ...MATERIAL_PBR[cls], known });

  // Direct colours: 0x2RRGGBB opaque, 0x3RRGGBB transparent.
  if (colorId >= 0x2000000 && colorId < 0x4000000) {
    const rgb: [number, number, number] = [(colorId >> 16) & 0xff, (colorId >> 8) & 0xff, colorId & 0xff];
    return colorId >= 0x3000000
      ? finish('transparent', rgb, DEFAULT_TRANSPARENT_ALPHA, true)
      : finish('abs', rgb, 1, true);
  }

  const entry = CLASSES[String(colorId)];
  const viewerHex = LDRAW_COLOR_RGB[colorId];
  const hex = viewerHex ?? entry?.rgb;
  if (!hex) return finish('abs', [127, 127, 127], 1, false);
  const rgb = hexToRgb(hex);
  const alpha = entry?.alpha !== undefined ? entry.alpha / 255 : 1;

  let cls: LegoMaterialClass;
  if (entry?.finish === 'chrome') cls = 'chrome';
  else if (entry?.finish === 'metal' || entry?.finish === 'matte_metallic') cls = 'metallic';
  else if (entry?.finish === 'pearl') cls = 'pearl';
  else if (entry?.finish === 'rubber') cls = 'rubber';
  else if (entry?.luminance) cls = 'glow';
  else if (alpha < 1) cls = 'transparent';
  else if (!entry && colorId >= 10000 && colorId < 11000) cls = STUDIO_TRANSPARENT.has(colorId) ? 'transparent' : 'rubber';
  else if (!entry && STUDIO_TRANSPARENT.has(colorId)) cls = 'transparent';
  else cls = 'abs';

  const effectiveAlpha = cls === 'transparent' && alpha >= 1 ? DEFAULT_TRANSPARENT_ALPHA : alpha;
  return finish(cls, rgb, effectiveAlpha, true);
}

/** Stable identity for palette de-duplication. */
export const materialKey = (m: LdrawEntityMaterial): string => String(m.colorId);
