/**
 * Unified model-index source resolution — SHARED by the auto-loader, the
 * search source-filter, the browse-all ordering and the result badges.
 *
 * Why one module: the search filter used to match ANY indexed entry for a set
 * (`models.some(m => srcMatch(m.src))`), so filtering by "Vision recon" listed
 * 71040-1 (Disney Castle) even though its BEST source — the one auto-load
 * actually resolves — is `mecabricks`; the recon entry is only a fallback the
 * user would never see. Filter, sort, badge and loader now all ask the SAME
 * `bestIndexedModel()` question, so they cannot disagree again.
 *
 * The index is generated by the clego repo and served as
 * /lego-models-index.json; `models[]` is ordered best-first.
 */

/** One available 3D model source for a set. */
export interface IndexModel {
  src: string;
  path: string;
  tier: 1 | 2;
  steps: number;
  n: number;
  /** Alternate-model label (B-models, train cars, UCS variants…) — absent on primaries. */
  variant?: string;
  /** 1 = known-rotation-bug script conversion (LXF lineage, src 'lxf_conv') —
   *  parts may be misrotated/misplaced. Load, but label honestly. */
  conv?: number;
  // ── schema 2 (2026-09-09): MEASURED per-file assembly metadata ─────────────
  // Stamped by clego's build_model_index.py from geograde's full-catalog
  // scoreboard. Every field is OPTIONAL: a schema-1 index (or an ungraded
  // file in a schema-2 index) simply omits them, and the reader must treat
  // absence as "not measured", never as a defect.
  /** geograde verdict for THIS file. Absent = never graded, or graded before
   *  the file was last modified → `assemblyStatus()` reports 'unverified'. */
  asm?: 'verified' | 'defective';
  /** geograde severity scalar (0 = clean). Present only alongside `asm`. */
  sev?: number;
  /** geograde's short defect strings (≤3). Present only when defective. */
  defects?: string[];
  /** The file's own `0 !LINEAGE <tool> <good|partial>` payload — the
   *  converter/alignment version that produced it. LDraw-text sources only. */
  lineage?: string;
  /** sha256/12 of the file bytes: content identity for the diagnostic bundle. */
  hash?: string;
}
export interface IndexSetEntry { name: string; year: string; parts: number; models: IndexModel[] }
export interface LegoModelsIndex {
  generated: string;
  sets: Record<string, IndexSetEntry>;
  /** Index schema version (absent/1 = no measured assembly metadata). */
  schema?: number;
  /** Provenance of the `asm`/`sev`/`defects` stamps, for the diagnostic bundle. */
  geograde?: { generated?: string; graded?: number; stale?: number; thresholds?: Record<string, unknown> };
}

/** Strip the '-1', '-2' etc suffix to get the base set number used in clego filenames. */
export function baseSetNum(setNum: string): string {
  return setNum.replace(/-\d+$/, '');
}

/** Index keys are base set numbers ("10001"); catalog uses "10001-1". */
export function lookupIndexModels(idx: LegoModelsIndex, setNum: string): IndexModel[] | null {
  const entry = idx.sets[setNum] ?? idx.sets[baseSetNum(setNum)];
  if (!entry || entry.models.length === 0) return null;
  // Suffix sets ("10001-2"): the index is keyed by base number only, so all
  // variants share one entry. When a model file names the full suffixed set
  // number, float those entries to the front so a -2/-3 catalog set loads its
  // own variant instead of the -1 primary (order otherwise preserved).
  const suffixed = /-[2-9]\d*$/.test(setNum);
  if (suffixed) {
    const want = setNum.toLowerCase();
    const hits = entry.models.filter(m => m.path.toLowerCase().includes(want));
    if (hits.length > 0) return [...hits, ...entry.models.filter(m => !hits.includes(m))];
  }
  return entry.models;
}

// ─── Measured assembly status (index schema 2) ────────────────────────────────

/**
 * What a MEASUREMENT says about a source's assembly, as opposed to what its
 * provenance suggests (that's `sourceClass` / source-quality.ts).
 *  • 'verified'   — geograde graded this exact file PASS on every calibrated
 *                   threshold (floating clusters, interpenetration, sunk
 *                   parts, unknown parts, duplicates).
 *  • 'defective'  — geograde graded it and at least one threshold failed.
 *  • 'unverified' — NOT MEASURED. Either never graded, or graded before the
 *                   file was last modified. This is the absence of evidence,
 *                   not evidence of a defect, and nothing may treat it as one.
 */
export type AssemblyStatus = 'verified' | 'unverified' | 'defective';

export function assemblyStatus(m: IndexModel): AssemblyStatus {
  return m.asm ?? 'unverified';
}

/** One-line human summary of the measured status (for badges/tooltips). */
export function assemblyStatusLabel(m: IndexModel): string {
  switch (assemblyStatus(m)) {
    case 'verified':
      return 'geometry-audited: no defects found';
    case 'defective':
      return `geometry-audited: ${m.defects?.join('; ') || 'defects found'}`;
    default:
      return 'assembly not measured';
  }
}

/**
 * Share of the incumbent's placement count a candidate must retain to be
 * promoted over it. geograde's own rerank rule (clego build_model_index.py
 * BEST_OVERRIDES) uses the same guard, and for the same reason: a source can
 * pass every defect threshold simply by containing LESS of the model — legacy
 * `dbix_conv` drops parts, `pdf_recon` reconstructs a subset — and promoting
 * that trades a measurable defect for an unmeasured omission.
 */
const MIN_PLACEMENT_RETENTION = 0.95;

/**
 * The order the indexed auto-loader tries a set's sources in.
 *
 * Two demotions, applied in this order:
 *
 * 1. **conv demotion** (unchanged): if the top-ranked entry is a conv-flagged
 *    script conversion but a non-conv source exists further down, the first
 *    non-conv entry goes FIRST.
 *
 * 2. **verified promotion** (schema 2): if the resulting first pick is graded
 *    DEFECTIVE and a later entry is graded PASS, the graded-PASS entry goes
 *    first — but ONLY under guards that keep this a refinement rather than a
 *    new ranking:
 *      – the incumbent must be graded 'defective'. An *unverified* incumbent
 *        is never demoted: absence of a grade is not evidence against it.
 *      – the candidate must not be conv-flagged (rule 1 still holds).
 *      – the candidate's provenance class must be no worse than the
 *        incumbent's, so a vision reconstruction can never displace a
 *        conversion and a conversion can never displace an authentic build
 *        file merely by grading better.
 *      – the candidate must retain ≥95 % of the incumbent's placements and
 *        must not grade WORSE on severity.
 *    Measured over the 2026-09-05 index + the 2026-09-03 full scoreboard: the
 *    unguarded "first verified wins" rule reordered 360 sets, 34 of them by
 *    promoting a `pdf_recon`/`recon_v3` reconstruction over a conversion. The
 *    guarded rule reorders 145, none across a class boundary.
 *
 * The picker's own order is never touched — every entry stays user-selectable
 * with its caveats; only the auto-pick moves.
 */
export function indexedTryOrder(models: IndexModel[]): number[] {
  return resolveTryOrder(models).order;
}

/** The try-order AND the reason the first pick moved — one source of truth for
 *  `indexedTryOrder` and `tryOrderReason`, so the UI can never explain a pick
 *  the loader didn't make. */
function resolveTryOrder(models: IndexModel[]): { order: number[]; reason: string | null } {
  let order = models.map((_, i) => i);
  let reason: string | null = null;
  // 1. conv demotion
  if (models[0]?.conv) {
    const firstNonConv = models.findIndex(m => !m.conv);
    if (firstNonConv > 0) {
      order = [firstNonConv, ...order.filter(i => i !== firstNonConv)];
      reason = `${models[0]!.src} is a script conversion with known placement defects,`
        + ` so ${models[firstNonConv]!.src} was tried first`;
    }
  }
  // 2. verified promotion
  const promoted = verifiedPromotion(models, order);
  if (promoted != null) {
    const inc = models[order[0]!]!;
    const why = inc.defects?.length ? inc.defects.join('; ') : 'geometry audit found defects';
    reason = `${inc.src} is graded defective (${why}),`
      + ` so ${models[promoted]!.src} — which passed the same audit — was tried first`;
    order = [promoted, ...order.filter(i => i !== promoted)];
  }
  return { order, reason };
}

/**
 * Index of the graded-PASS entry that should displace a graded-DEFECTIVE first
 * pick, or null when no promotion applies. Exported so the UI can explain the
 * pick without re-deriving the rule (see `tryOrderReason`).
 */
export function verifiedPromotion(models: IndexModel[], order: number[]): number | null {
  const cur = models[order[0] ?? -1];
  if (!cur || assemblyStatus(cur) !== 'defective') return null;
  const curRank = sourceClassRank(sourceClass(cur.src));
  for (const i of order.slice(1)) {
    const cand = models[i];
    if (!cand || cand.conv || assemblyStatus(cand) !== 'verified') continue;
    if (sourceClassRank(sourceClass(cand.src)) > curRank) continue;
    if (cand.n < MIN_PLACEMENT_RETENTION * cur.n) continue;
    if (cand.sev != null && cur.sev != null && cand.sev > cur.sev) continue;
    return i;
  }
  return null;
}

/**
 * Why the auto-pick is not simply `models[0]`, phrased for the UI. null when
 * the index's own first entry is the pick (nothing to explain).
 */
export function tryOrderReason(models: IndexModel[]): string | null {
  return resolveTryOrder(models).reason;
}

/**
 * The source a set will ACTUALLY load from — the first entry the indexed
 * auto-load chain attempts. `null` when the set isn't in the models index.
 * (A gated/broken source can still fail and fall through at load time, but
 * this is the intended one, and it's what the UI must advertise.)
 */
export function bestIndexedModel(idx: LegoModelsIndex, setNum: string): IndexModel | null {
  const models = lookupIndexModels(idx, setNum);
  if (!models) return null;
  const first = indexedTryOrder(models)[0];
  return first == null ? null : (models[first] ?? null);
}

// ─── Source quality classes ──────────────────────────────────────────────────

/**
 * How trustworthy a source's geometry is:
 *  • authentic  — real LDraw/Studio build files (omr, ldr, io, io_model2*)
 *  • conversion — machine conversions from another format (mecabricks*, dbix_*,
 *                 lxf/lxf_conv, eurobricks): usually right, sometimes splayed
 *  • recon      — reconstructions from instruction PDFs / vision (recon_v3,
 *                 pdf_recon): approximate placements by construction
 *  • unindexed  — no model in the index at all (classic OMR/BFF fallback only)
 */
export type SourceClass = 'authentic' | 'conversion' | 'recon' | 'unindexed';

export function sourceClass(src: string): SourceClass {
  if (src === 'omr' || src === 'ldr' || src === 'io' || src.startsWith('io_model2')) return 'authentic';
  if (src === 'recon_v3' || src === 'pdf_recon' || src.startsWith('recon')) return 'recon';
  return 'conversion';
}

const CLASS_RANK: Record<SourceClass, number> = {
  authentic: 0, conversion: 1, recon: 2, unindexed: 3,
};

export function sourceClassRank(c: SourceClass): number { return CLASS_RANK[c]; }

/** Best-source class for a catalog set number ('unindexed' when absent). */
export function bestSourceClass(idx: LegoModelsIndex, setNum: string): SourceClass {
  const best = bestIndexedModel(idx, setNum);
  return best ? sourceClass(best.src) : 'unindexed';
}

/**
 * Stable partition of relevance-ranked results by best-source class:
 * authentic first, then conversions, then recon, then unindexed — the
 * flagship order rankSets produced is PRESERVED inside each class.
 */
export function sortByBestSourceClass<T extends { set_num: string }>(
  list: T[], idx: LegoModelsIndex,
): void {
  const rank = new Map<T, number>();
  for (const s of list) rank.set(s, sourceClassRank(bestSourceClass(idx, s.set_num)));
  const decorated = list.map((s, i) => ({ s, i, r: rank.get(s)! }));
  decorated.sort((a, b) => (a.r - b.r) || (a.i - b.i));
  for (let i = 0; i < decorated.length; i++) list[i] = decorated[i]!.s;
}

// ─── Source filter groups + badges ───────────────────────────────────────────

/** Source-filter groups (#lego-source-filter values) → predicate over a source
 *  id. Applied to the set's BEST source only (see bestIndexedModel): a set
 *  whose recon file is merely a never-used fallback must not show up under
 *  "Vision recon". Sets absent from the index match no group. */
export const SOURCE_GROUPS: Record<string, (src: string) => boolean> = {
  omr:        src => src === 'omr' || src === 'ldr',
  io:         src => src === 'io' || src.startsWith('io_model2'),
  dbix:       src => src.startsWith('dbix_'),
  mecabricks: src => src.startsWith('mecabricks'),
  eurobricks: src => src === 'eurobricks',
  lxf:        src => src === 'lxf' || src === 'lxf_conv',
  recon:      src => sourceClass(src) === 'recon',
};

/** Short, card-sized label for a source id ("io_model2_v2" → "io"). */
export function sourceBadgeLabel(src: string): string {
  if (src === 'io' || src.startsWith('io_model2')) return 'io';
  if (src === 'omr') return 'omr';
  if (src === 'ldr') return 'ldr';
  if (src.startsWith('mecabricks')) return 'meca';
  if (src.startsWith('dbix')) return 'dbix';
  if (src === 'lxf' || src === 'lxf_conv') return 'lxf';
  if (src === 'eurobricks') return 'euro';
  if (sourceClass(src) === 'recon') return 'recon';
  return src.slice(0, 6);
}
