/**
 * Unified model-index source resolution — SHARED by the auto-loader, the
 * search source-filter, the browse-all ordering and the result badges.
 *
 * Why one module: the search filter used to match ANY indexed entry for a set
 * (`models.some(m => srcMatch(m.src))`), so filtering by "Vision recon" listed
 * 71040-1 (Disney Castle) even though its BEST source — the one auto-load
 * actually resolves — is `mecabricks`; the recon entry is only a fallback the
 * user would never see. Filter, sort, badge and loader now all ask the SAME
 * `bestIndexedModel()` question, so they cannot disagree again.
 *
 * The index is generated by the clego repo and served as
 * /lego-models-index.json; `models[]` is ordered best-first.
 */

/** One available 3D model source for a set. */
export interface IndexModel {
  src: string;
  path: string;
  tier: 1 | 2;
  steps: number;
  n: number;
  /** Alternate-model label (B-models, train cars, UCS variants…) — absent on primaries. */
  variant?: string;
  /** 1 = known-rotation-bug script conversion (LXF lineage, src 'lxf_conv') —
   *  parts may be misrotated/misplaced. Load, but label honestly. */
  conv?: number;
}
export interface IndexSetEntry { name: string; year: string; parts: number; models: IndexModel[] }
export interface LegoModelsIndex { generated: string; sets: Record<string, IndexSetEntry> }

/** Strip the '-1', '-2' etc suffix to get the base set number used in clego filenames. */
export function baseSetNum(setNum: string): string {
  return setNum.replace(/-\d+$/, '');
}

/** Index keys are base set numbers ("10001"); catalog uses "10001-1". */
export function lookupIndexModels(idx: LegoModelsIndex, setNum: string): IndexModel[] | null {
  const entry = idx.sets[setNum] ?? idx.sets[baseSetNum(setNum)];
  if (!entry || entry.models.length === 0) return null;
  // Suffix sets ("10001-2"): the index is keyed by base number only, so all
  // variants share one entry. When a model file names the full suffixed set
  // number, float those entries to the front so a -2/-3 catalog set loads its
  // own variant instead of the -1 primary (order otherwise preserved).
  const suffixed = /-[2-9]\d*$/.test(setNum);
  if (suffixed) {
    const want = setNum.toLowerCase();
    const hits = entry.models.filter(m => m.path.toLowerCase().includes(want));
    if (hits.length > 0) return [...hits, ...entry.models.filter(m => !hits.includes(m))];
  }
  return entry.models;
}

/**
 * The order the indexed auto-loader tries a set's sources in.
 *
 * Honest default: if the top-ranked entry is a conv-flagged script conversion
 * but a non-conv source exists further down, the first non-conv entry goes
 * FIRST (the picker's own order stays untouched — conv entries remain
 * user-selectable, they just don't win the auto-pick).
 */
export function indexedTryOrder(models: IndexModel[]): number[] {
  const order = models.map((_, i) => i);
  if (models[0]?.conv) {
    const firstNonConv = models.findIndex(m => !m.conv);
    if (firstNonConv > 0) return [firstNonConv, ...order.filter(i => i !== firstNonConv)];
  }
  return order;
}

/**
 * The source a set will ACTUALLY load from — the first entry the indexed
 * auto-load chain attempts. `null` when the set isn't in the models index.
 * (A gated/broken source can still fail and fall through at load time, but
 * this is the intended one, and it's what the UI must advertise.)
 */
export function bestIndexedModel(idx: LegoModelsIndex, setNum: string): IndexModel | null {
  const models = lookupIndexModels(idx, setNum);
  if (!models) return null;
  const first = indexedTryOrder(models)[0];
  return first == null ? null : (models[first] ?? null);
}

// ─── Source quality classes ──────────────────────────────────────────────────

/**
 * How trustworthy a source's geometry is:
 *  • authentic  — real LDraw/Studio build files (omr, ldr, io, io_model2*)
 *  • conversion — machine conversions from another format (mecabricks*, dbix_*,
 *                 lxf/lxf_conv, eurobricks): usually right, sometimes splayed
 *  • recon      — reconstructions from instruction PDFs / vision (recon_v3,
 *                 pdf_recon): approximate placements by construction
 *  • unindexed  — no model in the index at all (classic OMR/BFF fallback only)
 */
export type SourceClass = 'authentic' | 'conversion' | 'recon' | 'unindexed';

export function sourceClass(src: string): SourceClass {
  if (src === 'omr' || src === 'ldr' || src === 'io' || src.startsWith('io_model2')) return 'authentic';
  if (src === 'recon_v3' || src === 'pdf_recon' || src.startsWith('recon')) return 'recon';
  return 'conversion';
}

const CLASS_RANK: Record<SourceClass, number> = {
  authentic: 0, conversion: 1, recon: 2, unindexed: 3,
};

export function sourceClassRank(c: SourceClass): number { return CLASS_RANK[c]; }

/** Best-source class for a catalog set number ('unindexed' when absent). */
export function bestSourceClass(idx: LegoModelsIndex, setNum: string): SourceClass {
  const best = bestIndexedModel(idx, setNum);
  return best ? sourceClass(best.src) : 'unindexed';
}

/**
 * Stable partition of relevance-ranked results by best-source class:
 * authentic first, then conversions, then recon, then unindexed — the
 * flagship order rankSets produced is PRESERVED inside each class.
 */
export function sortByBestSourceClass<T extends { set_num: string }>(
  list: T[], idx: LegoModelsIndex,
): void {
  const rank = new Map<T, number>();
  for (const s of list) rank.set(s, sourceClassRank(bestSourceClass(idx, s.set_num)));
  const decorated = list.map((s, i) => ({ s, i, r: rank.get(s)! }));
  decorated.sort((a, b) => (a.r - b.r) || (a.i - b.i));
  for (let i = 0; i < decorated.length; i++) list[i] = decorated[i]!.s;
}

// ─── Source filter groups + badges ───────────────────────────────────────────

/** Source-filter groups (#lego-source-filter values) → predicate over a source
 *  id. Applied to the set's BEST source only (see bestIndexedModel): a set
 *  whose recon file is merely a never-used fallback must not show up under
 *  "Vision recon". Sets absent from the index match no group. */
export const SOURCE_GROUPS: Record<string, (src: string) => boolean> = {
  omr:        src => src === 'omr' || src === 'ldr',
  io:         src => src === 'io' || src.startsWith('io_model2'),
  dbix:       src => src.startsWith('dbix_'),
  mecabricks: src => src.startsWith('mecabricks'),
  eurobricks: src => src === 'eurobricks',
  lxf:        src => src === 'lxf' || src === 'lxf_conv',
  recon:      src => src === 'recon_v3' || src === 'pdf_recon',
};

/** Short, card-sized label for a source id ("io_model2_v2" → "io"). */
export function sourceBadgeLabel(src: string): string {
  if (src === 'io' || src.startsWith('io_model2')) return 'io';
  if (src === 'omr') return 'omr';
  if (src === 'ldr') return 'ldr';
  if (src.startsWith('mecabricks')) return 'meca';
  if (src.startsWith('dbix')) return 'dbix';
  if (src === 'lxf' || src === 'lxf_conv') return 'lxf';
  if (src === 'eurobricks') return 'euro';
  if (src === 'recon_v3' || src === 'pdf_recon') return 'recon';
  return src.slice(0, 6);
}
