/**
 * Parse a LEGO Digital Designer .lxf file → ParsedBrick[].
 *
 * LXF is a plain ZIP archive containing IMAGE100.LXFML (XML).
 * LXFML structure:
 *   <LXFML>
 *     <Bricks>
 *       <Brick designID="3001">
 *         <Part materials="21,...">
 *           <Bone transformation="r00,r01,...,tx,ty,tz"/>
 *         </Part>
 *       </Brick>
 *     </Bricks>
 *   </LXFML>
 *
 * Two coordinate problems must both be solved to place parts correctly:
 *
 * 1. LDD vs LDraw world axes — LDD is Y-up, cm units; LDraw is Y-down, LDU.
 *    Conversion: flip Y, scale translations ×25 (1 LDD unit = 25 LDU).
 *
 * 2. LDD vs LDraw PART ORIGIN — the same physical part has a different local
 *    origin in LDD than in the LDraw library, so the LXFML <Bone> transform
 *    (which positions the LDD origin) does NOT place the LDraw geometry
 *    correctly. BrickLink Studio's ldraw.xml ships a per-part alignment
 *    transform (axis-angle rotation + translation, in LDD units) plus the
 *    correct LDraw filename (e.g. designID 60583 → 60583b.dat). We bundle that
 *    table at /ldd-part-map.json (generated by scripts/gen-ldd-part-map.py) and
 *    compose it with the bone transform. Without this, .lxf models render with
 *    floating / overlapping / mis-rotated pieces (issue #108).
 *
 * Final per-part transform, derived cleanly in LDD space then converted:
 *   R_world = R_bone · R_align          (rotation)
 *   t_world = R_bone · t_align + t_bone  (translation, LDD units)
 *   then LDraw: rot = F·R_world·F, pos = 25·(F·t_world),  F = diag(1,-1,1)
 */

import { extractFile } from './zip-utils';
import { lddToLDraw } from './ldd-colors';
import type { ParsedBrick } from './ldraw-parser';

/** 1 cm = 25 LDraw units (1 stud = 0.8cm = 20 LDU → 1cm = 25 LDU). */
const CM_TO_LDU = 25;

/** designID → [ldrawFile, tx, ty, tz, angle(rad), ax, ay, az]. */
type PartAlign = [string, number, number, number, number, number, number, number];
let partMapPromise: Promise<Record<string, PartAlign>> | null = null;

/** Lazily fetch + cache the LDD→LDraw part-alignment table (~232 KB). */
function loadPartMap(): Promise<Record<string, PartAlign>> {
  if (!partMapPromise) {
    partMapPromise = fetch('/ldd-part-map.json')
      .then(r => (r.ok ? r.json() : {}))
      .catch(() => ({} as Record<string, PartAlign>));
  }
  return partMapPromise;
}

/** Axis-angle (radians) → 3×3 row-major rotation matrix. */
function axisAngleToMatrix(angle: number, ax: number, ay: number, az: number): number[] {
  if (Math.abs(angle) < 1e-9) return [1, 0, 0, 0, 1, 0, 0, 0, 1];
  const n = Math.hypot(ax, ay, az);
  if (n < 1e-9) return [1, 0, 0, 0, 1, 0, 0, 0, 1];
  ax /= n; ay /= n; az /= n;
  const c = Math.cos(angle), s = Math.sin(angle), t = 1 - c;
  return [
    t * ax * ax + c,      t * ax * ay - s * az, t * ax * az + s * ay,
    t * ax * ay + s * az, t * ay * ay + c,      t * ay * az - s * ax,
    t * ax * az - s * ay, t * ay * az + s * ax, t * az * az + c,
  ];
}

/** Multiply two 3×3 row-major matrices. */
function mul3(a: number[], b: number[]): number[] {
  const r = new Array<number>(9);
  for (let i = 0; i < 3; i++)
    for (let j = 0; j < 3; j++)
      r[i * 3 + j] = a[i * 3] * b[j] + a[i * 3 + 1] * b[3 + j] + a[i * 3 + 2] * b[6 + j];
  return r;
}

/** Multiply a 3×3 row-major matrix by a 3-vector. */
function mulVec(m: number[], v: [number, number, number]): [number, number, number] {
  return [
    m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
    m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
    m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
  ];
}

export async function parseLxf(buffer: ArrayBuffer): Promise<ParsedBrick[]> {
  const xmlBytes = await extractFile(buffer, 'IMAGE100.LXFML');
  const xmlText = new TextDecoder('utf-8').decode(xmlBytes);

  const doc = new DOMParser().parseFromString(xmlText, 'text/xml');
  const parserError = doc.querySelector('parsererror');
  if (parserError) throw new Error(`LXFML parse error: ${parserError.textContent?.slice(0, 120)}`);

  const partMap = await loadPartMap();
  const bricks: ParsedBrick[] = [];

  for (const brick of doc.querySelectorAll('Brick')) {
    const designID = brick.getAttribute('designID') ?? '3001';

    const partEl = brick.querySelector('Part');
    const materialsAttr = partEl?.getAttribute('materials') ?? '';
    const materialId = parseInt(materialsAttr.split(',')[0], 10) || 194;
    const color = lddToLDraw(materialId);

    const bone = brick.querySelector('Bone');
    const tf = bone?.getAttribute('transformation');
    if (!tf) continue;

    const vals = tf.split(',').map(Number);
    if (vals.length < 12) continue;

    // Bone matrix is column-major 4×3: cols 0..2 are the rotation basis,
    // vals[9..11] the translation (LDD units). Row-major R_bone:
    const rBone = [
      vals[0], vals[3], vals[6],
      vals[1], vals[4], vals[7],
      vals[2], vals[5], vals[8],
    ];
    const tBone: [number, number, number] = [vals[9], vals[10], vals[11]];

    // Per-part LDD→LDraw alignment (filename + origin offset). Falls back to a
    // bare designID.dat with identity alignment when the part isn't in the table.
    const align = partMap[designID];
    const part = align ? align[0] : `${designID}.dat`;
    const tAlign: [number, number, number] = align ? [align[1], align[2], align[3]] : [0, 0, 0];
    const rAlign = align
      ? axisAngleToMatrix(align[4], align[5], align[6], align[7])
      : [1, 0, 0, 0, 1, 0, 0, 0, 1];

    // Compose in LDD space: R_world = R_bone·R_align, t_world = R_bone·t_align + t_bone
    const rWorld = mul3(rBone, rAlign);
    const rotated = mulVec(rBone, tAlign);
    const tWorld: [number, number, number] = [
      rotated[0] + tBone[0],
      rotated[1] + tBone[1],
      rotated[2] + tBone[2],
    ];

    // LDD → LDraw: conjugate rotation by F=diag(1,-1,1) (negate row1 XOR col1),
    // flip Y of translation, scale to LDU.
    const rot = [
       rWorld[0], -rWorld[1],  rWorld[2],
      -rWorld[3],  rWorld[4], -rWorld[5],
       rWorld[6], -rWorld[7],  rWorld[8],
    ];

    bricks.push({
      color,
      x:  tWorld[0] * CM_TO_LDU,
      y: -tWorld[1] * CM_TO_LDU,
      z:  tWorld[2] * CM_TO_LDU,
      rot,
      part,
    });
  }

  if (bricks.length === 0) throw new Error('No brick placements found in LXFML');
  return bricks;
}
