/**
 * Parse a LEGO Digital Designer .lxf file → ParsedBrick[].
 *
 * LXF is a plain ZIP archive containing IMAGE100.LXFML (XML).
 * LXFML structure:
 *   <LXFML>
 *     <Bricks>
 *       <Brick designID="3001">
 *         <Part materials="21,...">
 *           <Bone transformation="r00,r01,...,tx,ty,tz"/>
 *         </Part>
 *       </Brick>
 *     </Bricks>
 *   </LXFML>
 *
 * Two coordinate problems must both be solved to place parts correctly:
 *
 * 1. LDD vs LDraw world axes — LDD is Y-up, cm units; LDraw is Y-down, LDU.
 *    Conversion: flip Y, scale translations ×25 (1 LDD unit = 25 LDU).
 *
 * 2. LDD vs LDraw PART ORIGIN — the same physical part has a different local
 *    origin in LDD than in the LDraw library, so the LXFML <Bone> transform
 *    (which positions the LDD origin) does NOT place the LDraw geometry
 *    correctly. BrickLink Studio's ldraw.xml ships a per-part alignment
 *    transform (axis-angle rotation + translation, in LDD units) plus the
 *    correct LDraw filename (e.g. designID 60583 → 60583b.dat). We bundle that
 *    table at /ldd-part-map.json (generated by scripts/gen-ldd-part-map.py) and
 *    compose it with the bone transform. Without this, .lxf models render with
 *    floating / overlapping / mis-rotated pieces (issue #108).
 *
 * Final per-part transform, derived cleanly in LDD space then converted:
 *   R_world = R_bone · R_align          (rotation)
 *   t_world = R_bone · t_align + t_bone  (translation, LDD units)
 *   then LDraw: rot = F·R_world·F, pos = 25·(F·t_world),  F = diag(1,-1,1)
 */

import { extractFile } from './zip-utils';
import { lddToLDraw } from './ldd-colors';
import type { ParsedBrick } from './ldraw-parser';

/** 1 cm = 25 LDraw units (1 stud = 0.8cm = 20 LDU → 1cm = 25 LDU). */
const CM_TO_LDU = 25;

/** designID → [ldrawFile, tx, ty, tz, angle(rad), ax, ay, az]. */
export type PartAlign = [string, number, number, number, number, number, number, number];

/** Where the alignment table lives (generated by scripts/gen-ldd-part-map.py). */
export const PART_MAP_URL = '/ldd-part-map.json';
/** A transient failure gets this many tries in total before we give up on it. */
const TABLE_FETCH_ATTEMPTS = 3;
const TABLE_RETRY_BACKOFF_MS = [250, 750];

/**
 * The loaded alignment resource. `state` separates the two failures the audit
 * found conflated: `unavailable` means the WHOLE table is missing (so every
 * placement silently falls back to its raw LDD origin and the model looks
 * scattered), while an `ok` table with a design id absent from `entries` is one
 * unsupported mould among thousands of correct ones.
 */
export interface LxfAlignmentTable {
  state: 'ok' | 'unavailable';
  /** the URL it was fetched from — half of the "source identity". */
  source: string;
  /** schema-validated entries, keyed by LDD designID. */
  entries: Record<string, PartAlign>;
  /** raw entries present in the JSON but rejected by `validatePartAlign`. */
  rejected: number;
  /** the resource's own identity, from its HTTP validators when it has them. */
  version?: string;
  /** why the whole resource is unavailable. */
  error?: string;
}

/** What a `.lxf` parse can tell the caller about how well it went. */
export interface LxfDiagnostics {
  table: Pick<LxfAlignmentTable, 'state' | 'source' | 'rejected' | 'error'> & {
    entries: number;
    version?: string;
  };
  /** placements positioned through a table entry. */
  mappedPlacements: number;
  /** placements that fell back to identity alignment + bare `designID.dat`. */
  unmappedPlacements: number;
  /** distinct unmapped design ids, most-used first (capped for readability). */
  unmappedDesignIds: string[];
  /** `<Part>` elements with no `<Bone>` at all. */
  skippedNoBone: number;
  /** `<Part>` elements whose `<Bone transformation>` had < 12 numbers. */
  skippedBadTransform: number;
  /** `<Part>` elements with several `<Bone>`s (flex segments; first one wins). */
  multiBoneParts: number;
}

/**
 * One `<Part>` worth of LXFML, lifted out of the DOM so the placement maths can
 * be exercised without a DOM (the test environment is plain node).
 */
export interface LxfPartRecord {
  designID: string;
  materialId: number;
  transformation: string;
  boneCount: number;
}

/** True when `v` is a structurally valid `PartAlign` row. */
export function validatePartAlign(v: unknown): v is PartAlign {
  if (!Array.isArray(v) || v.length !== 8) return false;
  if (typeof v[0] !== 'string' || v[0].length === 0) return false;
  for (let i = 1; i < 8; i++) {
    if (typeof v[i] !== 'number' || !Number.isFinite(v[i])) return false;
  }
  return true;
}

/**
 * Validate a fetched alignment table. A malformed or non-object body yields an
 * `unavailable` table rather than a silent empty one, and individual bad rows
 * are DROPPED and COUNTED — one corrupt row must not disable alignment for the
 * other 4,466 parts.
 */
export function validatePartMap(raw: unknown, source: string, version?: string): LxfAlignmentTable {
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) {
    return {
      state: 'unavailable', source, entries: {}, rejected: 0, version,
      error: `alignment table is not a JSON object (got ${Array.isArray(raw) ? 'array' : typeof raw})`,
    };
  }
  const entries: Record<string, PartAlign> = {};
  let rejected = 0;
  for (const [id, v] of Object.entries(raw as Record<string, unknown>)) {
    if (validatePartAlign(v)) entries[id] = v;
    else rejected++;
  }
  if (Object.keys(entries).length === 0) {
    return {
      state: 'unavailable', source, entries, rejected, version,
      error: `alignment table has no usable entries (${rejected} rejected by schema)`,
    };
  }
  return { state: 'ok', source, entries, rejected, version };
}

let partMapPromise: Promise<LxfAlignmentTable> | null = null;

/** Drop the cached table so the next load refetches. Exported for tests. */
export function resetPartMapCache(): void {
  partMapPromise = null;
}

const sleep = (ms: number) => new Promise<void>(r => setTimeout(r, ms));

/**
 * Fetch + validate the table, retrying a TRANSIENT failure. A 404/410 is
 * definitive (the asset genuinely isn't deployed) and is not retried; a thrown
 * fetch, a 5xx or a 429 is not.
 */
async function fetchPartMap(): Promise<LxfAlignmentTable> {
  let error = 'unknown failure';
  for (let attempt = 0; attempt < TABLE_FETCH_ATTEMPTS; attempt++) {
    if (attempt > 0) await sleep(TABLE_RETRY_BACKOFF_MS[attempt - 1] ?? 750);
    let resp: Response;
    try {
      resp = await fetch(PART_MAP_URL);
    } catch (err) {
      error = `network error: ${err instanceof Error ? err.message : String(err)}`;
      continue;
    }
    if (!resp.ok) {
      error = `HTTP ${resp.status}`;
      if (resp.status === 404 || resp.status === 410) break; // definitive
      continue;
    }
    // The resource carries no version field of its own, so its identity is the
    // HTTP validator the server does send, plus the accepted entry count.
    const version = resp.headers?.get?.('etag')
      ?? resp.headers?.get?.('last-modified')
      ?? undefined;
    try {
      return validatePartMap(await resp.json(), PART_MAP_URL, version ?? undefined);
    } catch (err) {
      // Malformed JSON is a property of the bytes, not of the connection —
      // retrying cannot help, so stop here and report it.
      return {
        state: 'unavailable', source: PART_MAP_URL, entries: {}, rejected: 0,
        version: version ?? undefined,
        error: `malformed JSON: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }
  return { state: 'unavailable', source: PART_MAP_URL, entries: {}, rejected: 0, error };
}

/**
 * Lazily fetch + cache the LDD→LDraw part-alignment table (~232 KB).
 *
 * A SUCCESSFUL table is cached for the page session; a failure is NOT. The old
 * implementation turned every HTTP/network/JSON error into `{}` and kept that
 * promise, so one transient blip left every later `.lxf` load in the session
 * placing parts at their raw LDD origins with no way to recover short of a
 * reload (audit 2026-09-08, P1 item 3).
 */
export function loadPartMap(): Promise<LxfAlignmentTable> {
  if (!partMapPromise) {
    partMapPromise = fetchPartMap().then(
      t => {
        if (t.state !== 'ok') partMapPromise = null; // let the next load retry
        return t;
      },
      err => {
        partMapPromise = null;
        throw err;
      },
    );
  }
  return partMapPromise;
}

/** Axis-angle (radians) → 3×3 row-major rotation matrix. */
export function axisAngleToMatrix(angle: number, ax: number, ay: number, az: number): number[] {
  if (Math.abs(angle) < 1e-9) return [1, 0, 0, 0, 1, 0, 0, 0, 1];
  const n = Math.hypot(ax, ay, az);
  if (n < 1e-9) return [1, 0, 0, 0, 1, 0, 0, 0, 1];
  ax /= n; ay /= n; az /= n;
  const c = Math.cos(angle), s = Math.sin(angle), t = 1 - c;
  return [
    t * ax * ax + c,      t * ax * ay - s * az, t * ax * az + s * ay,
    t * ax * ay + s * az, t * ay * ay + c,      t * ay * az - s * ax,
    t * ax * az - s * ay, t * ay * az + s * ax, t * az * az + c,
  ];
}

/** Multiply two 3×3 row-major matrices. */
function mul3(a: number[], b: number[]): number[] {
  const r = new Array<number>(9);
  for (let i = 0; i < 3; i++)
    for (let j = 0; j < 3; j++)
      r[i * 3 + j] = a[i * 3] * b[j] + a[i * 3 + 1] * b[3 + j] + a[i * 3 + 2] * b[6 + j];
  return r;
}

/** Multiply a 3×3 row-major matrix by a 3-vector. */
function mulVec(m: number[], v: [number, number, number]): [number, number, number] {
  return [
    m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
    m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
    m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
  ];
}

/**
 * Parse an LXFML `<Bone transformation>` string into a row-major rotation +
 * translation. The LXFML value is a COLUMN-major 4×3 (9 rotation values then
 * tx,ty,tz, LDD units); this returns the transposed row-major R plus t.
 * Returns null when there aren't at least 12 values.
 */
export function parseBoneTransform(
  tf: string,
): { rBone: number[]; tBone: [number, number, number] } | null {
  const v = tf.split(',').map(Number);
  if (v.length < 12) return null;
  return {
    rBone: [v[0], v[3], v[6], v[1], v[4], v[7], v[2], v[5], v[8]],
    tBone: [v[9], v[10], v[11]],
  };
}

export interface LxfPlacement { rot: number[]; x: number; y: number; z: number; }

/**
 * The testable core of issue #108: compose the LDD bone transform with the
 * per-part LDD→LDraw origin alignment, then convert LDD space (Y-up, cm) to
 * LDraw space (Y-down, LDU). Pure — no DOM / fetch / ZIP.
 *
 *   R_world = R_bone · R_align,  t_world = R_bone · t_align + t_bone   (LDD)
 *   rot = F·R_world·F,  pos = 25·(F·t_world),  F = diag(1,-1,1)
 *
 * `align` undefined → identity alignment (bare `designID.dat` fallback caller-side).
 */
export function composeLxfPlacement(
  rBone: number[],
  tBone: [number, number, number],
  align: PartAlign | undefined,
): LxfPlacement {
  const tAlign: [number, number, number] = align ? [align[1], align[2], align[3]] : [0, 0, 0];
  const rAlign = align
    ? axisAngleToMatrix(align[4], align[5], align[6], align[7])
    : [1, 0, 0, 0, 1, 0, 0, 0, 1];

  const rWorld = mul3(rBone, rAlign);
  const rotated = mulVec(rBone, tAlign);
  const tWorld: [number, number, number] = [
    rotated[0] + tBone[0],
    rotated[1] + tBone[1],
    rotated[2] + tBone[2],
  ];

  // LDD → LDraw: conjugate rotation by F=diag(1,-1,1) (negate row1 XOR col1),
  // flip Y of translation, scale to LDU.
  const rot = [
     rWorld[0], -rWorld[1],  rWorld[2],
    -rWorld[3],  rWorld[4], -rWorld[5],
     rWorld[6], -rWorld[7],  rWorld[8],
  ];
  return {
    rot,
    x:  tWorld[0] * CM_TO_LDU,
    y: -tWorld[1] * CM_TO_LDU,
    z:  tWorld[2] * CM_TO_LDU,
  };
}

/**
 * The DOM-free core: LXFML `<Part>` records × the alignment table → placements
 * plus the coverage/skip counts. Pure, so the production table's real coverage
 * is testable without a browser.
 */
export function buildLxfPlacements(
  records: readonly LxfPartRecord[],
  table: LxfAlignmentTable,
): { bricks: ParsedBrick[]; diagnostics: LxfDiagnostics } {
  const bricks: ParsedBrick[] = [];
  const unmapped = new Map<string, number>();
  let mappedPlacements = 0;
  let unmappedPlacements = 0;
  let skippedNoBone = 0;
  let skippedBadTransform = 0;
  let multiBoneParts = 0;

  for (const rec of records) {
    if (rec.boneCount > 1) multiBoneParts++;
    if (!rec.transformation) { skippedNoBone++; continue; }
    const boneT = parseBoneTransform(rec.transformation);
    if (!boneT) { skippedBadTransform++; continue; }

    // Per-part LDD→LDraw alignment (filename + origin offset). Falls back to a
    // bare designID.dat with identity alignment when the part isn't in the table.
    const align = table.entries[rec.designID];
    if (align) mappedPlacements++;
    else {
      unmappedPlacements++;
      unmapped.set(rec.designID, (unmapped.get(rec.designID) ?? 0) + 1);
    }
    const part = align ? align[0] : `${rec.designID}.dat`;
    const { rot, x, y, z } = composeLxfPlacement(boneT.rBone, boneT.tBone, align);
    bricks.push({ color: lddToLDraw(rec.materialId), x, y, z, rot, part });
  }

  return {
    bricks,
    diagnostics: {
      table: {
        state: table.state,
        source: table.source,
        rejected: table.rejected,
        entries: Object.keys(table.entries).length,
        ...(table.version !== undefined ? { version: table.version } : {}),
        ...(table.error !== undefined ? { error: table.error } : {}),
      },
      mappedPlacements,
      unmappedPlacements,
      unmappedDesignIds: [...unmapped.entries()]
        .sort((a, b) => b[1] - a[1])
        .slice(0, 40)
        .map(([id]) => id),
      skippedNoBone,
      skippedBadTransform,
      multiBoneParts,
    },
  };
}

/**
 * One line describing how the alignment table served this model, or null when
 * there is nothing worth telling the user. Pure, so the wording is testable.
 */
export function describeLxfDiagnostics(d: LxfDiagnostics): string | null {
  if (d.table.state !== 'ok') {
    return `LDD alignment table unavailable (${d.table.error ?? 'unknown'}) — every part is placed at its raw LDD origin, so this model will look scattered. Reload to retry.`;
  }
  const total = d.mappedPlacements + d.unmappedPlacements;
  const parts: string[] = [];
  if (d.unmappedPlacements > 0 && total > 0) {
    const pct = (100 * d.unmappedPlacements) / total;
    parts.push(
      `${d.unmappedPlacements} of ${total} placements (${pct.toFixed(1)}%, ` +
      `${d.unmappedDesignIds.length} design id${d.unmappedDesignIds.length === 1 ? '' : 's'}) ` +
      'have no LDD→LDraw alignment entry and use their raw LDD origin',
    );
  }
  if (d.skippedBadTransform > 0) parts.push(`${d.skippedBadTransform} malformed bone transforms skipped`);
  if (d.skippedNoBone > 0) parts.push(`${d.skippedNoBone} parts with no bone skipped`);
  return parts.length ? `LDD .lxf: ${parts.join('; ')}` : null;
}

/** Lift every `<Part>` out of an LXFML document. Thin — the DOM half. */
function readLxfParts(doc: Document): LxfPartRecord[] {
  const out: LxfPartRecord[] = [];
  // A <Brick> can contain MULTIPLE <Part> elements (assemblies — e.g. a hinge
  // is designID 73983 wrapping parts 2430 + 2429), each with its OWN designID,
  // materials, and <Bone> transform. Iterate every Part, not just the first,
  // or assembly halves silently vanish.
  for (const brick of doc.querySelectorAll('Brick')) {
    const brickDesign = brick.getAttribute('designID');
    for (const partEl of brick.querySelectorAll('Part')) {
      const bones = partEl.querySelectorAll('Bone');
      out.push({
        designID: partEl.getAttribute('designID') ?? brickDesign ?? '3001',
        materialId: parseInt((partEl.getAttribute('materials') ?? '').split(',')[0], 10) || 194,
        // Each Part carries its own Bone(s); the first bone is its placement.
        // (Multiple bones = a flex part's segments — out of scope; first wins,
        // matching prior behaviour, and counted in the diagnostics.)
        transformation: bones[0]?.getAttribute('transformation') ?? '',
        boneCount: bones.length,
      });
    }
  }
  return out;
}

/** `.lxf` → placements + the alignment diagnostics behind them. */
export async function parseLxfWithDiagnostics(
  buffer: ArrayBuffer,
): Promise<{ bricks: ParsedBrick[]; diagnostics: LxfDiagnostics }> {
  // .lxf is a ZIP wrapping IMAGE100.LXFML; a bare .lxfml is the same XML
  // unwrapped (DBIX interactive-instruction dumps ship as .lxfml). Sniff the
  // ZIP magic instead of trusting the extension.
  const head = new Uint8Array(buffer.slice(0, 2));
  const isZip = head[0] === 0x50 && head[1] === 0x4B; // 'PK'
  const xmlBytes = isZip
    ? await extractFile(buffer, 'IMAGE100.LXFML')
    : new Uint8Array(buffer);
  const xmlText = new TextDecoder('utf-8').decode(xmlBytes);

  const doc = new DOMParser().parseFromString(xmlText, 'text/xml');
  const parserError = doc.querySelector('parsererror');
  if (parserError) throw new Error(`LXFML parse error: ${parserError.textContent?.slice(0, 120)}`);

  const table = await loadPartMap();
  const result = buildLxfPlacements(readLxfParts(doc), table);
  if (result.bricks.length === 0) throw new Error('No brick placements found in LXFML');
  return result;
}

/** `.lxf` → placements. Diagnostics-free wrapper for callers that don't need them. */
export async function parseLxf(buffer: ArrayBuffer): Promise<ParsedBrick[]> {
  return (await parseLxfWithDiagnostics(buffer)).bricks;
}
