/**
 * Comparison — API data comparison viewer with before/after image slider.
 * Loads comparison-data.json generated by scripts/gen-comparison.ts and renders
 * an interactive slider + full API data tables for each address.
 */

// ─── Types (match comparison-data.json schema) ─────────────────────────────

interface ApiRecord {
  name: string;
  available: boolean;
  status: 'ok' | 'error' | 'skipped' | 'unavailable';
  error?: string;
  data: Record<string, unknown>;
  fieldsSet: string[];
  impactedGenFields: string[];
}

interface ComparisonResult {
  key: string;
  address: string;
  apis: ApiRecord[];
  property: Record<string, unknown>;
  genOptions: Record<string, unknown>;
  grid: { width: number; height: number; depth: number; blocks: number };
  views: {
    exterior: { api: string };
    cutaway: string[];
    floor: string[];
  };
}

// ─── Constants ──────────────────────────────────────────────────────────────

const VIEW_TYPES = ['exterior', 'cutaway', 'floor'] as const;
const VIEW_LABELS: Record<string, string> = { exterior: 'Exterior', cutaway: 'Cutaway', floor: 'Floor Plan' };

/** Default generation values for the "no API" side of comparison */
const NOAPI_DEFAULTS: Record<string, string | number> = {
  style: 'fantasy', floors: 2, grid: '78\u00d720\u00d740', blocks: '15,190',
  wall: 'default', trim: 'default', roof: 'default', door: 'default',
  shape: 'L', roofShape: 'gable', windowSpacing: 3,
};

/** Noapi image paths use .jpg extension (pre-converted in web/public/comparison/) */
const NOAPI_VIEWS = {
  exterior: 'noapi_exterior.jpg',
  cutaway: [0, 1, 2, 3].map(i => `noapi_cutaway_${i}.jpg`),
  floor: [0, 1, 2, 3].map(i => `noapi_floor_${i}.jpg`),
};

// ─── Helpers ────────────────────────────────────────────────────────────────

function mc(block: unknown): string {
  return String(block ?? '').replace('minecraft:', '');
}

function esc(str: unknown): string {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ─── Module State ───────────────────────────────────────────────────────────

let allData: ComparisonResult[] = [];
let currentIdx = 0;
let currentView: typeof VIEW_TYPES[number] = 'exterior';
let currentLayer = 0;
let sliderPos = 0.5;
let dragging = false;
let loaded = false;

// DOM element references (set during init)
let rootEl: HTMLElement;

/**
 * Initialize the comparison viewer inside the given container element.
 * Fetches comparison-data.json lazily on first call.
 */
export function initComparison(container: HTMLElement): void {
  rootEl = container;
  rootEl.innerHTML = '<p class="cmp-loading">Loading comparison data...</p>';

  fetch('comparison/comparison-data.json')
    .then(r => r.json())
    .then((data: ComparisonResult[]) => {
      allData = data;
      loaded = true;
      buildShell();
      render();
    })
    .catch(() => {
      rootEl.innerHTML = '<p class="cmp-loading">Failed to load comparison data. Run <code>scripts/gen-comparison.ts</code> first.</p>';
    });
}

// ─── Shell (static DOM skeleton) ────────────────────────────────────────────

function buildShell(): void {
  rootEl.innerHTML = `
    <div class="cmp-header">
      <h2 class="cmp-title">API Data Comparison</h2>
      <p class="cmp-subtitle">Drag the slider to compare default generation vs real API-enriched output</p>
    </div>
    <div class="cmp-nav" id="cmp-nav"></div>
    <div class="cmp-tabs" id="cmp-tabs"></div>
    <div class="cmp-layers" id="cmp-layers"></div>
    <div class="cmp-slider-wrap">
      <div class="cmp-slider" id="cmp-slider">
        <img class="cmp-img-noapi" id="cmp-img-noapi" alt="Default">
        <img class="cmp-img-api" id="cmp-img-api" alt="API Enriched">
        <div class="cmp-label-left">Default</div>
        <div class="cmp-label-right">API Enriched</div>
        <div class="cmp-divider" id="cmp-divider">
          <div class="cmp-handle" id="cmp-handle"></div>
        </div>
      </div>
    </div>
    <div class="cmp-gen-summary" id="cmp-gen-summary"></div>
    <div class="cmp-api-section" id="cmp-api-section"></div>
  `;

  // Wire up drag events on the slider
  const sliderEl = document.getElementById('cmp-slider')!;
  const handleEl = document.getElementById('cmp-handle')!;

  const startDrag = (e: Event) => { e.preventDefault(); dragging = true; };
  const endDrag = () => { dragging = false; };

  const moveDrag = (e: MouseEvent | TouchEvent) => {
    if (!dragging) return;
    e.preventDefault();
    const rect = sliderEl.getBoundingClientRect();
    const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
    sliderPos = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    updateSlider();
  };

  const jumpSlider = (e: MouseEvent | TouchEvent) => {
    if (e.target === handleEl) return;
    const rect = sliderEl.getBoundingClientRect();
    const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
    sliderPos = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    updateSlider();
    dragging = true;
  };

  handleEl.addEventListener('mousedown', startDrag);
  handleEl.addEventListener('touchstart', startDrag, { passive: false });
  sliderEl.addEventListener('mousedown', jumpSlider as EventListener);
  sliderEl.addEventListener('touchstart', jumpSlider as EventListener, { passive: false });
  document.addEventListener('mousemove', moveDrag as EventListener);
  document.addEventListener('touchmove', moveDrag as EventListener, { passive: false });
  document.addEventListener('mouseup', endDrag);
  document.addEventListener('touchend', endDrag);
}

// ─── Render ─────────────────────────────────────────────────────────────────

function render(): void {
  if (!loaded || allData.length === 0) return;
  buildNav();
  buildViewTabs();
  buildLayers();
  updateImages();
  buildGenSummary();
  buildApiTables();
}

function buildNav(): void {
  const el = document.getElementById('cmp-nav')!;
  el.innerHTML = '';
  allData.forEach((loc, i) => {
    const btn = document.createElement('button');
    btn.className = 'cmp-nav-btn' + (i === currentIdx ? ' active' : '');
    const city = loc.address.split(',')[1]?.trim() || loc.key;
    btn.innerHTML = `<span class="cmp-nav-label">${esc(city)}</span><span class="cmp-nav-addr">${esc(loc.address)}</span>`;
    btn.addEventListener('click', () => { currentIdx = i; currentLayer = 0; render(); });
    el.appendChild(btn);
  });
}

function buildViewTabs(): void {
  const el = document.getElementById('cmp-tabs')!;
  el.innerHTML = '';
  for (const vt of VIEW_TYPES) {
    const btn = document.createElement('button');
    btn.className = 'cmp-tab-btn' + (vt === currentView ? ' active' : '');
    btn.textContent = VIEW_LABELS[vt];
    btn.addEventListener('click', () => { currentView = vt; currentLayer = 0; render(); });
    el.appendChild(btn);
  }
}

function buildLayers(): void {
  const el = document.getElementById('cmp-layers')!;
  el.innerHTML = '';
  if (currentView === 'exterior') {
    el.classList.add('hidden');
    return;
  }
  el.classList.remove('hidden');
  const loc = allData[currentIdx];
  const apiLayers = currentView === 'cutaway' ? loc.views.cutaway : loc.views.floor;
  const noapiLayers = NOAPI_VIEWS[currentView];
  const maxLayers = Math.max(apiLayers.length, noapiLayers.length);
  for (let i = 0; i < maxLayers; i++) {
    const btn = document.createElement('button');
    btn.className = 'cmp-layer-btn' + (i === currentLayer ? ' active' : '');
    btn.textContent = String(i);
    btn.addEventListener('click', () => { currentLayer = i; render(); });
    el.appendChild(btn);
  }
}

function updateImages(): void {
  const loc = allData[currentIdx];
  const imgNoapi = document.getElementById('cmp-img-noapi') as HTMLImageElement;
  const imgApi = document.getElementById('cmp-img-api') as HTMLImageElement;
  if (!imgNoapi || !imgApi) return;

  let apiPath: string;
  let noapiPath: string;

  if (currentView === 'exterior') {
    apiPath = `comparison/${loc.views.exterior.api}`;
    noapiPath = `comparison/${loc.key}-${NOAPI_VIEWS.exterior}`;
  } else {
    const apiArr = currentView === 'cutaway' ? loc.views.cutaway : loc.views.floor;
    const noapiArr = NOAPI_VIEWS[currentView];
    const apiIdx = Math.min(currentLayer, apiArr.length - 1);
    const noapiIdx = Math.min(currentLayer, noapiArr.length - 1);
    apiPath = `comparison/${apiArr[apiIdx]}`;
    noapiPath = `comparison/${loc.key}-${noapiArr[noapiIdx]}`;
  }

  imgNoapi.src = noapiPath;
  imgApi.src = apiPath;

  const sliderEl = document.getElementById('cmp-slider')!;
  let loadCount = 0;
  const checkHeight = () => {
    loadCount++;
    if (loadCount >= 2) {
      const containerW = sliderEl.offsetWidth;
      const ratioA = imgApi.naturalHeight / (imgApi.naturalWidth || 1);
      const ratioB = imgNoapi.naturalHeight / (imgNoapi.naturalWidth || 1);
      const maxRatio = Math.max(ratioA, ratioB);
      const h = Math.min(containerW * maxRatio, 700);
      sliderEl.style.height = Math.max(h, 200) + 'px';
      updateSlider();
    }
  };
  imgApi.onload = checkHeight;
  imgNoapi.onload = checkHeight;
  if (imgApi.complete) loadCount++;
  if (imgNoapi.complete) loadCount++;
  if (loadCount >= 2) checkHeight();
}

function updateSlider(): void {
  const sliderEl = document.getElementById('cmp-slider');
  const imgApi = document.getElementById('cmp-img-api') as HTMLImageElement;
  const dividerEl = document.getElementById('cmp-divider');
  if (!sliderEl || !imgApi || !dividerEl) return;

  const w = sliderEl.offsetWidth;
  const x = Math.round(sliderPos * w);
  imgApi.style.clipPath = `inset(0 0 0 ${x}px)`;
  dividerEl.style.left = x + 'px';
}

// ─── Generation Summary ─────────────────────────────────────────────────────

function buildGenSummary(): void {
  const el = document.getElementById('cmp-gen-summary')!;
  const loc = allData[currentIdx];
  const g = loc.genOptions;
  const noapi = NOAPI_DEFAULTS;

  const rows: [string, unknown, unknown][] = [
    ['Style', noapi.style, g.style],
    ['Floors', noapi.floors, g.floors],
    ['Grid', noapi.grid, `${g.width}\u00d7${loc.grid.height}\u00d7${g.length || '?'}`],
    ['Blocks', noapi.blocks, loc.grid.blocks?.toLocaleString()],
    ['Sq Ft', '\u2014', (loc.property.sqft as number)?.toLocaleString()],
    ['Beds/Baths', '\u2014', `${loc.property.bedrooms || '?'} / ${loc.property.bathrooms || '?'}`],
    ['Year', '\u2014', loc.property.yearUncertain ? '\u2014' : loc.property.yearBuilt],
    ['Wall', noapi.wall, mc(g.wallOverride) || 'default'],
    ['Trim', noapi.trim, mc(g.trimOverride) || 'default'],
    ['Roof', noapi.roof, g.roofOverride ? mc((g.roofOverride as Record<string, unknown>).cap) : 'default'],
    ['Door', noapi.door, g.doorOverride || 'default'],
    ['Shape', noapi.shape, g.floorPlanShape || 'rect'],
    ['Roof Shape', noapi.roofShape, g.roofShape || 'gable'],
    ['Win Spacing', noapi.windowSpacing, g.windowSpacing || 3],
    ['Roof Height', 'default', g.roofHeightOverride ?? 'default'],
  ];

  const makeTable = (side: 'noapi' | 'api') => {
    let html = `<div class="cmp-gen-card ${side}"><h4>${side === 'noapi' ? 'Default (No API)' : 'API Enriched'}</h4><table>`;
    for (const [label, noapiVal, apiVal] of rows) {
      const val = side === 'noapi' ? noapiVal : apiVal;
      const isChanged = side === 'api' && String(noapiVal) !== String(apiVal);
      const cls = isChanged ? ' class="changed"' : '';
      html += `<tr><td>${label}</td><td${cls}>${esc(val)}</td></tr>`;
    }
    html += '</table></div>';
    return html;
  };

  el.innerHTML = makeTable('noapi') + makeTable('api');
}

// ─── API Data Tables ────────────────────────────────────────────────────────

function buildApiTables(): void {
  const el = document.getElementById('cmp-api-section')!;
  const loc = allData[currentIdx];

  const activeCount = loc.apis.filter(a => a.status === 'ok').length;
  let html = `<h3 class="cmp-api-heading">API Data Sources (${activeCount}/${loc.apis.length} active)</h3>`;
  html += '<div class="cmp-api-grid">';

  for (const api of loc.apis) {
    html += '<div class="cmp-api-card">';
    html += `<div class="cmp-api-header"><span class="cmp-api-name">${esc(api.name)}</span><span class="cmp-api-status ${api.status}">${api.status}</span></div>`;

    if (api.error && api.status !== 'ok') {
      html += `<p class="cmp-api-error">${esc(api.error)}</p>`;
    }

    // Returned data
    if (api.data && Object.keys(api.data).length > 0) {
      html += '<table class="cmp-api-table">';
      for (const [k, v] of Object.entries(api.data)) {
        if (v === null || v === undefined) continue;
        html += `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`;
      }
      html += '</table>';
    }

    // Fields set
    if (api.fieldsSet?.length > 0) {
      html += '<div class="cmp-tag-row"><span class="cmp-tag-label">Sets</span><div class="cmp-tags cmp-tags-green">';
      for (const f of api.fieldsSet) html += `<span class="cmp-tag">${esc(f)}</span>`;
      html += '</div></div>';
    }

    // Impact
    if (api.impactedGenFields?.length > 0) {
      html += '<div class="cmp-tag-row"><span class="cmp-tag-label">Impacts</span><div class="cmp-tags cmp-tags-blue">';
      for (const f of api.impactedGenFields) html += `<span class="cmp-tag">${esc(f)}</span>`;
      html += '</div></div>';
    }

    html += '</div>';
  }

  html += '</div>';
  el.innerHTML = html;
}
