/**
 * THE CHEAT SHEET. Every current operator-facing entry point of the LEGO /
 * Bedrock toolchain, with its real arguments (read from each script's own
 * argument parsing — nothing here is guessed), what it answers, where its
 * evidence lands and roughly how long it takes.
 *
 * Maintain it here and only here: the console UI renders this list, the
 * command builder turns it into argv, and the tests check its shape.
 *
 * Scripts judged STALE (numbered iteration relics, one-off probes whose
 * question is answered, VLM loops keyed to `.claude/*state.json`) are listed
 * at the bottom in `STALE`, so the judgement is reviewable, not silent.
 */
import type { Operation } from './types.ts';

/** Studio's bundled LDraw library, the root every offline script pins. */
export const LDRAW_ROOT = 'C:/git/clego/extracted/studio_release/app/ldraw';
export const CLEGO_ROOT = 'C:/git/clego';
export const CORPUS_ROOT = `${CLEGO_ROOT}/lego_sets`;

const SILHOUETTE_VIEWS = ['front', 'back', 'left', 'right', 'top', 'iso'] as const;

export const OPERATIONS: readonly Operation[] = [
  // ───────────────────────────── Pack export ─────────────────────────────
  {
    id: 'playable-pack',
    group: 'Pack export',
    title: 'Export a playable .mcaddon',
    answers: 'What pack does the REAL shared pipeline (engine/schem-pipeline.ts, the LEGO tab\'s Worker code) produce for this model, with which components, warnings, scale, LOD and budget?',
    entry: 'scripts/_playable_ref.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr', 'lxf'], batch: 'per-item',
    args: [{ item: true }, { opt: 'out' }, { opt: 'quality' }, { opt: 'mode' }, { opt: 'facing' }, { opt: 'label' }, { opt: 'noPbr' }, { opt: 'camera' }, { opt: 'mainOnly' }, { opt: 'buildings' }, { opt: 'scale' }, { opt: 'resolution' }, { opt: 'lod' }, { opt: 'lodDistance' }, { opt: 'figureCollisionHeight' }],
    options: [
      { key: 'out', flag: '', render: 'positional', type: 'path', help: 'Output .mcaddon (default output/bedrock-entity-qa/<stem>.mcaddon).' },
      { key: 'quality', flag: 'quality', render: 'eq', type: 'enum', values: ['balanced', 'high', 'ultra'], default: 'balanced', help: 'Entity cuboid quality.' },
      { key: 'mode', flag: 'mode', render: 'eq', type: 'enum', values: ['auto', 'car', 'plane', 'boat', 'static'], default: 'auto', help: 'Vehicle mode.' },
      { key: 'facing', flag: 'facing', render: 'eq', type: 'enum', values: ['auto', '+x', '-x', '+z', '-z'], default: 'auto', help: 'Vehicle nose direction.' },
      { key: 'label', flag: 'label', render: 'eq', type: 'string', help: 'Pack/entity label (default: file stem).' },
      { key: 'noPbr', flag: 'no-pbr', render: 'switch', type: 'boolean', default: false, help: 'Skip PBR texture sets.' },
      { key: 'camera', flag: 'camera', render: 'eq', type: 'enum', values: ['orbit', 'boom'], default: 'orbit', help: 'Ride camera style.' },
      { key: 'mainOnly', flag: 'main-only', render: 'switch', type: 'boolean', default: false, help: 'Export the main vehicle only.' },
      { key: 'buildings', flag: 'buildings', render: 'eq', type: 'enum', values: ['bricks', 'blocks'], default: 'bricks', help: 'bricks = brick-accurate shell entity over colliders; blocks = block placement.' },
      { key: 'scale', flag: 'scale', render: 'eq', type: 'enum', values: ['auto', '0.25', '0.5', '0.75', '1', '1.5', '2', '3', '4'], default: 'auto', help: 'Model scale as a multiplier of minifig scale (engine/addon-scale.ts).' },
      { key: 'resolution', flag: 'resolution', render: 'eq', type: 'enum', values: ['auto', 'minifig'], help: 'Resolution plan override (parsed by the script; undocumented in its header).' },
      { key: 'lod', flag: 'lod', render: 'eq', type: 'enum', values: ['hull', 'none'], default: 'hull', help: 'Resident per-colour surface hull drawn past the LOD distance.' },
      { key: 'lodDistance', flag: 'lod-distance', render: 'eq', type: 'number', help: 'LOD switch distance in blocks.' },
      { key: 'figureCollisionHeight', flag: 'figure-collision-height', render: 'eq', type: 'number', help: 'Experimental override of a figure NPC collision_box.height (default computed, 1.0-1.8).' },
    ],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'bricks', label: 'bricks', path: 'bricks' },
      { key: 'scale', label: 'scale', path: 'scale.scale' },
      { key: 'components', label: 'components', path: 'components.length' },
      { key: 'warnings', label: 'warnings', path: 'warnings.length' },
      { key: 'bytes', label: 'bytes', path: 'bytes' },
      { key: 'ms', label: 'ms', path: 'ms' },
      { key: 'sha256', label: 'sha256', path: 'sha256' },
      { key: 'out', label: 'pack', path: 'out' },
    ],
    evidence: { fromJson: 'out', dir: 'output/bedrock-entity-qa' },
    duration: '20 s (small vehicle) to 5+ min (71043-class building) per model',
    docs: ['TASKS-BEDROCK-ADDON.md', 'docs/bedrock-addon-guide.md'],
    notes: 'Follow with "Validate .mcaddon structure" before a device round. VERBOSE=1 in the environment prints pipeline phases to stderr.',
  },
  {
    id: 'minifig-pack',
    group: 'Pack export',
    title: 'Build a custom-minifig pack',
    answers: 'Does one minifig NPC assembled from chosen parts (minifig-rig.ts) build through the real add-on builder, and with which rig bones / cube count?',
    entry: 'scripts/_minifig_ref.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'out' }, { opt: 'label' }, { opt: 'torso' }, { opt: 'head' }, { opt: 'hair' }, { opt: 'legs' }, { opt: 'hips' }, { opt: 'arms' }, { opt: 'hands' }, { opt: 'heldRight' }, { opt: 'heldLeft' }, { opt: 'cape' }, { opt: 'spec' }, { opt: 'creator' }],
    options: [
      { key: 'out', flag: '', render: 'positional', type: 'path', help: 'Output .mcaddon.' },
      { key: 'label', flag: 'label', render: 'eq', type: 'string', default: 'Custom Minifig', help: 'NPC label.' },
      { key: 'torso', flag: 'torso', render: 'eq', type: 'string', default: '973:4', help: '<part>:<colour>.' },
      { key: 'head', flag: 'head', render: 'eq', type: 'string', help: '<part>:<colour>.' },
      { key: 'hair', flag: 'hair', render: 'eq', type: 'string', help: '<part>:<colour>, e.g. 3901:0.' },
      { key: 'legs', flag: 'legs', render: 'eq', type: 'number', help: 'LDraw colour id.' },
      { key: 'hips', flag: 'hips', render: 'eq', type: 'number', help: 'LDraw colour id.' },
      { key: 'arms', flag: 'arms', render: 'eq', type: 'number', help: 'LDraw colour id.' },
      { key: 'hands', flag: 'hands', render: 'eq', type: 'number', help: 'LDraw colour id.' },
      { key: 'heldRight', flag: 'held-right', render: 'eq', type: 'string', help: '<part>:<colour>, e.g. 3847:71.' },
      { key: 'heldLeft', flag: 'held-left', render: 'eq', type: 'string', help: '<part>:<colour>.' },
      { key: 'cape', flag: 'cape', render: 'eq', type: 'number', help: 'Cape colour id.' },
      { key: 'spec', flag: 'spec', render: 'eq', type: 'path', help: 'A MinifigSpec JSON; flags override its fields.' },
      { key: 'creator', flag: 'creator', render: 'eq', type: 'enum', values: ['starter'], help: 'Include the standalone in-game creator wand.' },
    ],
    parse: { kind: 'json-last' },
    columns: [],
    evidence: { fromJson: 'out', dir: 'output/bedrock-entity-qa' },
    duration: '~10 s',
    docs: ['docs/bedrock-addon-guide.md', 'docs/minifig-creator-wand.md'],
  },
  {
    id: 'coaster-qa-pack',
    group: 'Pack export',
    title: 'Build the Coaster QA pack',
    answers: 'A 33 kB device pack (stone pad + one measured straight, optional loop and 3-car train) that upgrades the CoasterQA world in place.',
    entry: 'scripts/_coaster_qa_pack.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'out' }, { opt: 'loop' }, { opt: 'train' }],
    options: [
      { key: 'out', flag: '', render: 'positional', type: 'path', help: 'Output (default output/bedrock-entity-qa/coaster-qa.mcaddon).' },
      { key: 'loop', flag: 'loop', render: 'switch', type: 'boolean', default: false, help: 'Also emit a closed 16-point vertical loop route.' },
      { key: 'train', flag: 'train', render: 'switch', type: 'boolean', default: false, help: 'Declare 10303\'s measured 3-car train on the straight.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: { dir: 'output/bedrock-entity-qa' },
    duration: '~5 s',
    docs: ['docs/bedrock-addon-guide.md'],
  },

  // ─────────────────────────── Pack validation ───────────────────────────
  {
    id: 'mcaddon-check',
    group: 'Pack validation',
    title: 'Validate .mcaddon structure',
    answers: 'Will the archive load at all: two manifests with valid UUIDs, BP depends on RP, every geometry/texture/script an entity names exists, identifiers parse. The cheap offline gate before a device round.',
    entry: 'scripts/_mcaddon_check.py',
    runtime: 'python', cwd: 'craftmatic', input: 'pack', batch: 'one-process',
    args: [{ items: 'args' }],
    options: [],
    parse: { kind: 'regex-lines', pattern: '^(?<status>OK|FAIL)[ \\t]+(?<pack>\\S+)[ \\t]*(?<notes>.*)$', groups: ['status', 'pack', 'notes'] },
    columns: [
      { key: 'status', label: 'status', path: 'status' },
      { key: 'pack', label: 'pack', path: 'pack' },
      { key: 'notes', label: 'notes', path: 'notes' },
    ],
    evidence: {},
    duration: '< 1 s per pack',
    docs: ['docs/testing-guide.md'],
    notes: 'Exit code is non-zero when any pack fails. Structural only — it is not a substitute for loading the pack.',
  },
  {
    id: 'entity-color-diff',
    group: 'Pack validation',
    title: 'Colour diff two packs',
    answers: 'Cube by cube, does every entity of pack B sample the same RGBA as pack A (geometry → render controller → texture → texel)? The offline gate for any change to how colour reaches geometry.',
    entry: 'scripts/_entity_color_diff.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'before' }, { opt: 'after' }],
    options: [
      { key: 'before', flag: '', render: 'positional', type: 'path', required: true, help: 'before.mcaddon' },
      { key: 'after', flag: '', render: 'positional', type: 'path', required: true, help: 'after.mcaddon' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~10-60 s',
    docs: ['docs/testing-guide.md'],
  },
  {
    id: 'collider-treads',
    group: 'Pack validation',
    title: 'Invisible-step (tread) measurement',
    answers: 'At every wand size step, the highest surface a player reaches on foot WITHOUT and WITH treads, tread counts, what could not be restored and whether named points (a coaster station) are reachable.',
    entry: 'scripts/_collider_treads.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr', 'mcaddon'], batch: 'per-item',
    args: [{ item: true }, { opt: 'turns' }, { opt: 'sizes' }, { opt: 'target' }, { opt: 'route' }, { opt: 'refused' }, '--json'],
    options: [
      { key: 'turns', flag: 'turns', render: 'switch', type: 'boolean', default: false, help: 'Plan every quarter turn (default 0° only).' },
      { key: 'sizes', flag: 'sizes', render: 'eq', type: 'string', help: 'Size steps in %, comma-separated (default 100,150,200,300,400).' },
      { key: 'target', flag: 'target', render: 'repeat', type: 'string', help: 'x,y,z[:label] — repeatable; comma-separate several with ";".' },
      { key: 'route', flag: 'route', render: 'switch', type: 'boolean', default: false, help: 'Print the walk route to each reached target.' },
      { key: 'refused', flag: 'refused', render: 'switch', type: 'boolean', default: false, help: 'Print the refused edges.' },
    ],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'cells', label: 'solid cells', path: 'cells' },
      { key: 'rows', label: 'size rows', path: 'rows.length' },
      { key: 'r0before', label: '100 % highest before', path: 'rows.0.highestBefore' },
      { key: 'r0after', label: '100 % highest after', path: 'rows.0.highestAfter' },
      { key: 'r0treads', label: '100 % tread blocks', path: 'rows.0.treadBlocks' },
    ],
    evidence: {},
    duration: '10 s (pack) to minutes (source built through the pipeline)',
    docs: ['docs/bedrock-addon-guide.md'],
    notes: 'A .mcaddon is read as shipped (its CONFIG colliders); a source is built through the pipeline at auto scale. Pick packs from the "Packs" selection tab.',
  },

  // ───────────────────── Placement & accuracy grading ─────────────────────
  {
    id: 'entity-silhouette',
    group: 'Placement & accuracy grading',
    title: 'Silhouette IoU (entity vs source)',
    answers: 'From six orthographic cameras, how much of the source model\'s silhouette does the emitted cuboid entity cover (IoU per view + mean)? Red = missing from the entity, blue = over-coverage.',
    entry: 'scripts/_entity_silhouette.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr'], batch: 'per-item',
    args: [{ item: true }, { opt: 'quality' }, { opt: 'mode' }, { opt: 'facing' }, { opt: 'label' }, { opt: 'px' }, { opt: 'out' }],
    options: [
      { key: 'quality', flag: 'quality', render: 'eq', type: 'enum', values: ['balanced', 'high', 'ultra'], default: 'balanced', help: 'Entity quality.' },
      { key: 'mode', flag: 'mode', render: 'eq', type: 'enum', values: ['auto', 'car', 'plane', 'boat', 'static'], default: 'auto', help: 'Vehicle mode.' },
      { key: 'facing', flag: 'facing', render: 'eq', type: 'enum', values: ['auto', '+x', '-x', '+z', '-z'], default: 'auto', help: 'Nose direction.' },
      { key: 'label', flag: 'label', render: 'eq', type: 'string', help: 'Component label (default: file stem).' },
      { key: 'px', flag: 'px', render: 'eq', type: 'number', default: 512, help: 'Longest side in pixels.' },
      { key: 'out', flag: 'out', render: 'eq', type: 'path', help: 'Directory for one PNG per view (leave empty for numbers only).' },
    ],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'meanIoU', label: 'mean IoU', path: 'meanIoU' },
      { key: 'meanIoUFullSource', label: 'mean IoU (full source)', path: 'meanIoUFullSource' },
      ...SILHOUETTE_VIEWS.map(v => ({ key: v, label: v, path: `views.${v}.iou` })),
      { key: 'cubeCount', label: 'cubes', path: 'cubeCount' },
      { key: 'dropped', label: 'dropped placements', path: 'droppedPlacements' },
    ],
    evidence: { fromJson: 'out' },
    duration: '~15-90 s per model',
    docs: ['docs/bedrock-addon-guide.md'],
  },
  {
    id: 'geograde',
    group: 'Placement & accuracy grading',
    title: 'geograde (deterministic geometry grade)',
    answers: 'Floating clusters, deep overlap volume, sinkage, missing/unknown parts, figure and window defects for a model file — the grader behind the index\'s asm/sev stamps. No VLM, no renderer.',
    entry: 'geograde/geograde.py',
    runtime: 'python', cwd: 'clego', input: 'model', accepts: ['io', 'mpd', 'ldr'], batch: 'one-process',
    args: [{ items: 'args' }, '--out', { runDir: 'geograde' }],
    options: [],
    parse: { kind: 'regex-lines', pattern: '^(?<file>.+?)\\s+n=(?<n>\\d+)\\s+float=(?<float>\\d+)\\s*\\((?<floatClusters>\\d+)cl,(?<floatPct>[\\d.]+)%\\)\\s+BIG=(?<big>\\d+)\\s*\\(.*?fig=(?<fig>\\d+)\\s+win=(?<win>\\d+).*?ovl=\\s*(?<ovlPct>[\\d.]+)%.*?sunk=(?<sunk>\\d+)\\s+dup=(?<dup>\\d+)\\s+unk=(?<unk>\\d+)\\s+inv=(?<inv>\\S+)', groups: ['file', 'n', 'float', 'floatClusters', 'floatPct', 'big', 'fig', 'win', 'ovlPct', 'sunk', 'dup', 'unk', 'inv'] },
    columns: [
      { key: 'file', label: 'file', path: 'file' },
      { key: 'n', label: 'placed', path: 'n' },
      { key: 'float', label: 'floating', path: 'float' },
      { key: 'floatPct', label: 'float %', path: 'floatPct' },
      { key: 'big', label: 'BIG floating', path: 'big' },
      { key: 'fig', label: 'figure defects', path: 'fig' },
      { key: 'win', label: 'window defects', path: 'win' },
      { key: 'ovlPct', label: 'overlap %', path: 'ovlPct' },
      { key: 'sunk', label: 'sunk', path: 'sunk' },
      { key: 'unk', label: 'unknown', path: 'unk' },
      { key: 'inv', label: 'placed/inventory', path: 'inv' },
    ],
    evidence: { runDir: true },
    duration: '2-30 s per file (part-point cache warms after the first)',
    docs: ['docs/lego-sources-guide.md', 'C:/git/clego/GEOGRADE.md'],
    notes: 'One process per run (the part-point cache is saved at exit, so parallel processes would race it). Writes one JSON per model plus _batch.json into the run directory.',
  },
  {
    id: 'geograde-set',
    group: 'Placement & accuracy grading',
    title: 'geograde every indexed source of a set',
    answers: 'The same grade over EVERY model the index lists for a set, so the sources can be compared.',
    entry: 'geograde/geograde.py',
    runtime: 'python', cwd: 'clego', input: 'set', batch: 'per-item',
    args: ['--set', { item: true }, '--out', { runDir: 'geograde' }],
    options: [],
    parse: { kind: 'regex-lines', pattern: '^(?<file>.+?)\\s+n=(?<n>\\d+)\\s+float=(?<float>\\d+)\\s*\\((?<floatClusters>\\d+)cl,(?<floatPct>[\\d.]+)%\\).*?fig=(?<fig>\\d+)\\s+win=(?<win>\\d+).*?inv=(?<inv>\\S+)', groups: ['file', 'n', 'float', 'floatClusters', 'floatPct', 'fig', 'win', 'inv'] },
    columns: [
      { key: 'file', label: 'file', path: 'file' },
      { key: 'n', label: 'placed', path: 'n' },
      { key: 'float', label: 'floating', path: 'float' },
      { key: 'fig', label: 'figure defects', path: 'fig' },
      { key: 'win', label: 'window defects', path: 'win' },
      { key: 'inv', label: 'placed/inventory', path: 'inv' },
    ],
    evidence: { runDir: true },
    duration: '2-30 s per source',
    notes: 'Run this with concurrency 1: the part-point cache is written at process exit.',
  },
  {
    id: 'lxf-gt-eval',
    group: 'Placement & accuracy grading',
    title: 'LXF placement vs Studio ground truth',
    answers: 'GEO / exact placement agreement of the browser\'s .lxf maths (ldraw.xml rows applied as their INVERSE + measured table + mini-doll slots) against the authentic Studio .io of the same set.',
    entry: 'scripts/lxf_gt_eval.py',
    runtime: 'python', cwd: 'craftmatic', input: 'set', batch: 'one-process',
    args: [{ opt: 'all' }, '--sets', { items: 'args' }, { opt: 'variants' }, { opt: 'noMinidoll' }, '--json', { runDir: 'lxf-gt.json' }],
    options: [
      { key: 'all', flag: 'all', render: 'switch', type: 'boolean', default: false, ignoresSelection: true, help: 'Every native .lxf with an authentic .io (91 sets) — ignores the selection.' },
      { key: 'variants', flag: 'variants', render: 'list', type: 'string', default: 'shipped', help: 'Placement variants to score (space-separated; --list-variants prints them).' },
      { key: 'noMinidoll', flag: 'no-minidoll', render: 'switch', type: 'boolean', default: false, help: 'Reproduce the placements from before the mini-doll slot correction.' },
    ],
    parse: { kind: 'regex-lines', pattern: '^\\s+(?<set>\\d+)\\s+(?<variant>\\S+)\\s+GEO\\s+(?<geoPct>[\\d.]+)%\\s+exact\\s+(?<exactPct>[\\d.]+)%', groups: ['set', 'variant', 'geoPct', 'exactPct'] },
    columns: [
      { key: 'set', label: 'set', path: 'set' },
      { key: 'variant', label: 'variant', path: 'variant' },
      { key: 'geoPct', label: 'GEO %', path: 'geoPct' },
      { key: 'exactPct', label: 'exact %', path: 'exactPct' },
    ],
    evidence: { runDir: true },
    duration: '~5-20 s per set',
    docs: ['TASKS-BEDROCK-ADDON.md', 'docs/lego-sources-guide.md'],
    notes: 'Only sets with BOTH a native .lxf and an authentic Studio .io score; others print ERROR. 71043 has no authentic .io — never quote it as ground truth.',
  },
  {
    id: 'vox-stats',
    group: 'Placement & accuracy grading',
    title: 'Voxelization stats (.io)',
    answers: 'Non-air cells, fallback (no-geometry) parts, the inter-part contact pass (floating / bridged / cells added) and wall time of the REAL geometry voxelizer at a cell size.',
    entry: 'scripts/_vox_stats.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io'], batch: 'per-item',
    args: [{ item: true }, { opt: 'cell' }, { opt: 'noBridge' }],
    options: [
      { key: 'cell', flag: '', render: 'positional', type: 'number', default: 4, help: 'Cell size in LDU.' },
      { key: 'noBridge', flag: 'no-bridge', render: 'switch', type: 'boolean', default: false, help: 'Disable the inter-part contact pass (A/B).' },
    ],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'bricks', label: 'bricks', path: 'bricks' },
      { key: 'nonAir', label: 'non-air', path: 'nonAir' },
      { key: 'fallback', label: 'fallback parts', path: 'fallbackPartCount' },
      { key: 'ms', label: 'ms', path: 'ms' },
    ],
    evidence: {},
    duration: '10 s - 3 min per model',
    docs: ['docs/minecraft-pipeline-guide.md'],
  },
  {
    id: 'schem-ref',
    group: 'Placement & accuracy grading',
    title: 'Reference .schem export + digest (.io)',
    answers: 'The .schem (or --mcpack) the REAL shared export path emits for a Studio .io, its sha256, grid sha256, dims and non-air count — the byte-identity gate for any pipeline change.',
    entry: 'scripts/_schem_ref.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io'], batch: 'per-item',
    args: [{ item: true }, { opt: 'out' }, { opt: 'cell' }, { opt: 'noBridge' }, { opt: 'lights' }, { opt: 'noShapes' }, { opt: 'mcpack' }, { opt: 'profile' }],
    options: [
      { key: 'out', flag: '', render: 'positional', type: 'path', required: true, default: 'output/vox-work/console.schem', help: 'Output file. Positional — required before the cell.' },
      { key: 'cell', flag: '', render: 'positional', type: 'string', help: 'Forced cell LDU or resolution choice (blank = auto).' },
      { key: 'noBridge', flag: 'no-bridge', render: 'switch', type: 'boolean', default: false, help: 'Disable the inter-part contact pass.' },
      { key: 'lights', flag: 'lights', render: 'switch', type: 'boolean', default: false, help: 'Light fill.' },
      { key: 'noShapes', flag: 'no-shapes', render: 'switch', type: 'boolean', default: false, help: 'Disable the block-shape pass.' },
      { key: 'mcpack', flag: 'mcpack', render: 'switch', type: 'boolean', default: false, help: 'Emit Bedrock\'s native format through the same pipeline.' },
      { key: 'profile', flag: 'profile', render: 'eq', type: 'string', help: 'Block-mapping profile to A/B (e.g. textured).' },
    ],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'cellLDU', label: 'cell LDU', path: 'cellLDU' },
      { key: 'nonAir', label: 'non-air', path: 'nonAir' },
      { key: 'dims', label: 'dims', path: 'dims' },
      { key: 'schemSha256', label: 'schem sha256', path: 'schemSha256' },
      { key: 'gridSha256', label: 'grid sha256', path: 'gridSha256' },
      { key: 'voxMs', label: 'vox ms', path: 'voxMs' },
    ],
    evidence: {},
    duration: '30 s - 5 min per model (21063 ≈ 1.19 M cells)',
    docs: ['docs/minecraft-pipeline-guide.md', 'docs/testing-guide.md'],
    notes: 'The baseline hashes for 21063 live in the script header. In a batch every item overwrites the same `out` unless you point it at a directory pattern — use one item per run for byte gates.',
  },
  {
    id: 'schem-ldr',
    group: 'Placement & accuracy grading',
    title: 'Voxel-export one .ldr/.mpd',
    answers: 'The same shared pipeline as the reference export, for an LDraw text source instead of a Studio .io.',
    entry: 'scripts/_schem_ldr.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['ldr', 'mpd'], batch: 'per-item',
    args: [{ item: true }, { opt: 'out' }, { opt: 'cell' }, { opt: 'noBridge' }],
    options: [
      { key: 'out', flag: '', render: 'positional', type: 'path', required: true, default: 'output/vox-work/console-ldr.schem', help: 'Output file (required).' },
      { key: 'cell', flag: '', render: 'positional', type: 'number', default: 4, help: 'Cell LDU.' },
      { key: 'noBridge', flag: 'no-bridge', render: 'switch', type: 'boolean', default: false, help: 'Disable the inter-part contact pass.' },
    ],
    parse: { kind: 'json-last' }, columns: [],
    evidence: {},
    duration: '30 s - 5 min',
  },
  {
    id: 'schem-diff',
    group: 'Placement & accuracy grading',
    title: 'Content diff of two .schem files',
    answers: 'Cells gained, lost and recoloured between two exports (both re-imported through the REAL Upload-tab parser) — did a hash change move in the right direction?',
    entry: 'scripts/_schem_diff.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'before' }, { opt: 'after' }],
    options: [
      { key: 'before', flag: '', render: 'positional', type: 'path', required: true, help: 'before.schem' },
      { key: 'after', flag: '', render: 'positional', type: 'path', required: true, help: 'after.schem' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~10-30 s',
    docs: ['docs/minecraft-pipeline-guide.md'],
  },
  {
    id: 'schem-roundtrip',
    group: 'Placement & accuracy grading',
    title: 'Re-import a .schem',
    answers: 'Dims, non-air count, palette size and top blocks of an exported .schem read back through the REAL Upload-tab parser.',
    entry: 'scripts/_schem_roundtrip_check.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'schem' }],
    options: [{ key: 'schem', flag: '', render: 'positional', type: 'path', required: true, help: 'The .schem to read.' }],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'dims', label: 'dims', path: 'dims' },
      { key: 'nonAir', label: 'non-air', path: 'nonAir' },
      { key: 'palette', label: 'palette', path: 'palette' },
    ],
    evidence: {},
    duration: '~5 s',
  },

  // ─────────────────── Walk-through, vehicles & coasters ───────────────────
  {
    id: 'access-scale',
    group: 'Walk-through, vehicles & coasters',
    title: 'Walk-through size measurement',
    answers: 'Doorways and interior headroom against the player\'s 1×2-block passage, which size step makes the model walkable and why (recommendAccessScale).',
    entry: 'scripts/_access_scale.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr'], batch: 'per-item',
    args: [{ item: true }, { opt: 'cell' }, { opt: 'openings' }, { opt: 'json' }],
    options: [
      { key: 'cell', flag: 'cell', render: 'eq', type: 'string', help: 'Measurement cell as <xz>x<y> (e.g. 8x8).' },
      { key: 'openings', flag: 'openings', render: 'eq', type: 'number', default: 8, help: 'List the N easiest openings.' },
      { key: 'json', flag: 'json', render: 'switch', type: 'boolean', default: false, help: 'Print the whole measurement (openings included).' },
    ],
    parse: { kind: 'json-last' },
    columns: [
      { key: 'bricks', label: 'bricks', path: 'bricks' },
      { key: 'figures', label: 'figures', path: 'figures' },
      { key: 'doorLeaves', label: 'door leaves', path: 'doorLeaves' },
      { key: 'openings', label: 'openings', path: 'openings' },
      { key: 'headroom', label: 'headroom (blocks)', path: 'headroomBlocks' },
      { key: 'auto', label: 'auto scale', path: 'auto.scale' },
      { key: 'rec', label: 'recommended', path: 'recommendation.scale' },
      { key: 'reason', label: 'reason', path: 'recommendation.reason' },
    ],
    evidence: {},
    duration: '~10-60 s per model',
    docs: ['docs/bedrock-addon-guide.md'],
  },
  {
    id: 'coaster-assemblies',
    group: 'Walk-through, vehicles & coasters',
    title: 'Coaster track + car assembly probe',
    answers: 'The measured track routes (open/closed, mould count, length) and the detected cars (chassis, wheels, seats, route arc) of a coaster source.',
    entry: 'scripts/_coaster_assemblies_probe.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['ldr', 'mpd'], batch: 'per-item',
    args: [{ item: true }],
    options: [],
    parse: { kind: 'regex-lines', pattern: '^cars: (?<cars>\\d+) \\(ride (?<ride>\\d+), stray (?<stray>\\d+)\\)', groups: ['cars', 'ride', 'stray'] },
    columns: [
      { key: 'cars', label: 'cars', path: 'cars' },
      { key: 'ride', label: 'on route', path: 'ride' },
      { key: 'stray', label: 'stray', path: 'stray' },
    ],
    evidence: { dir: 'output/coaster-assemblies' },
    duration: '~10-40 s per model',
    docs: ['docs/bedrock-addon-guide.md'],
    notes: 'LDraw text only (.ldr/.mpd) — a .io must be converted first. Writes output/coaster-assemblies/<stem>.json.',
  },
  {
    id: 'vehicle-probe',
    group: 'Walk-through, vehicles & coasters',
    title: 'Vehicle facing + cockpit probe',
    answers: 'The entity compiler\'s own preparation of a vehicle: level, clusters, extras, facing votes and the cockpit it would choose.',
    entry: 'scripts/_vehicle_probe.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr'], batch: 'per-item',
    args: [{ item: true }, { opt: 'label' }, { opt: 'mode' }, { opt: 'extremes' }],
    options: [
      { key: 'label', flag: 'label', render: 'eq', type: 'string', help: 'Component label (default: file stem).' },
      { key: 'mode', flag: 'mode', render: 'eq', type: 'enum', values: ['auto', 'car', 'plane', 'boat', 'static'], help: 'Vehicle mode.' },
      { key: 'extremes', flag: 'extremes', render: 'eq', type: 'string', help: 'Print placement extremes (any value enables it).' },
    ],
    parse: { kind: 'regex-lines', pattern: '^facing (?<nose>\\S+) (?<source>\\S+) agreement (?<agreement>\\S+)', groups: ['nose', 'source', 'agreement'] },
    columns: [
      { key: 'nose', label: 'nose', path: 'nose' },
      { key: 'source', label: 'signal', path: 'source' },
      { key: 'agreement', label: 'agreement', path: 'agreement' },
    ],
    evidence: {},
    duration: '~10-30 s per model',
  },
  {
    id: 'entity-seat-probe',
    group: 'Walk-through, vehicles & coasters',
    title: 'Seat / collision / bounds probe',
    answers: 'Submodel groups, discovered playable components and each compiled entity\'s seat, collision box, visible bounds and cube count.',
    entry: 'scripts/_entity_seat_probe.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr'], batch: 'per-item',
    args: [{ item: true }, { opt: 'label' }, { opt: 'mode' }],
    options: [
      { key: 'label', flag: '', render: 'positional', type: 'string', required: true, default: 'probe', help: 'Component label (positional).' },
      { key: 'mode', flag: '', render: 'positional', type: 'enum', values: ['auto', 'car', 'plane', 'boat'], default: 'auto', help: 'Vehicle mode (positional).' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~10-30 s per model',
  },

  // ─────────────────── Windows, parts & corpus checks ───────────────────
  {
    id: 'converter-coverage',
    group: 'Windows, parts & corpus checks',
    title: 'Source-directive coverage audit',
    answers: 'Does the converter have a function for every instruction the sources carry? Walks every .ldr/.mpd/.dat/.lxfml AND every .lxf/.io archive, classifies each line-type-0 directive and each LXFML element/attribute against the coverage tables, and reports what is UNKNOWN (a gap nobody has looked at), what is a known gap that can change the model, and what is only described by a meta whose geometry is written out anyway.',
    entry: 'scripts/_converter_coverage_audit.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'root' }, { opt: 'cls' }, { opt: 'json' }, { opt: 'noArchives' }],
    options: [
      { key: 'root', flag: 'root', render: 'space', type: 'path', default: 'C:/git/clego/lego_sets', help: 'Corpus root to walk.' },
      { key: 'cls', flag: 'class', render: 'space', type: 'string', help: 'Limit to one corpus class, e.g. OMR.' },
      { key: 'json', flag: 'json', render: 'space', type: 'path', help: 'Also write the full classification as JSON.' },
      { key: 'noArchives', flag: 'no-archives', render: 'switch', type: 'boolean', default: false, help: 'Skip .lxf/.io archives (about half the time, but 38,840 fewer LDraw files).' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~180 s with archives, ~90 s without',
    docs: ['TASKS-BEDROCK-ADDON.md'],
    notes: 'Exit code is non-zero when anything in the corpus is missing from web/src/engine/ldraw-directives.ts or lxfml-schema.ts. Add a new directive to the table in the same change that meets it.',
  },
  {
    id: 'window-census',
    group: 'Windows, parts & corpus checks',
    title: 'Window defect census',
    answers: 'Per source class: files, window frames, panes, panes off their frame, and the CONCENTRATION (distinct sets vs placements) — over the selected files or a seeded sample of the index\'s primary picks.',
    entry: 'geograde/window_census.py',
    runtime: 'python', cwd: 'clego', input: 'index-path', batch: 'one-process',
    args: ['--list', { itemsFile: true }, '--out', { runDir: 'window-census.json' }],
    options: [],
    parse: { kind: 'regex-lines', pattern: '^(?<src>\\S+)\\s+(?<files>\\d+)\\s+(?<withFrames>\\d+)\\s+(?<frames>\\d+)\\s+(?<panes>\\d+)\\s+(?<judged>\\d+)\\s+(?<off>\\d+)\\s+(?<filesDefect>\\d+)\\s+(?<rate>[\\d.]+)%', groups: ['src', 'files', 'withFrames', 'frames', 'panes', 'judged', 'off', 'filesDefect', 'rate'] },
    columns: [
      { key: 'src', label: 'class', path: 'src' },
      { key: 'files', label: 'files', path: 'files' },
      { key: 'frames', label: 'frames', path: 'frames' },
      { key: 'panes', label: 'panes', path: 'panes' },
      { key: 'off', label: 'panes off frame', path: 'off' },
      { key: 'filesDefect', label: 'files w/ defect', path: 'filesDefect' },
      { key: 'rate', label: 'rate %', path: 'rate' },
    ],
    evidence: { runDir: true },
    duration: '~1-3 s per file',
    docs: ['docs/lego-sources-guide.md'],
    notes: 'With a selection the listing is written to the run dir and passed as --list (class "list"). For the seeded corpus sample use "Window census (sample)".',
  },
  {
    id: 'window-census-sample',
    group: 'Windows, parts & corpus checks',
    title: 'Window census (seeded corpus sample)',
    answers: 'The same census over a reproducible sample of the index\'s primary picks, optionally one src class.',
    entry: 'geograde/window_census.py',
    runtime: 'python', cwd: 'clego', input: 'none', batch: 'one-process',
    args: [{ opt: 'sample' }, { opt: 'seed' }, { opt: 'src' }, '--out', { runDir: 'window-census.json' }, '--sample-out', { runDir: 'window-census-sample.txt' }],
    options: [
      { key: 'sample', flag: 'sample', render: 'space', type: 'number', default: 500, help: 'Sample size.' },
      { key: 'seed', flag: 'seed', render: 'space', type: 'number', default: 20260920, help: 'Shuffle seed.' },
      { key: 'src', flag: 'src', render: 'space', type: 'string', help: 'Only this index src class (e.g. dbix_conv_v3).' },
    ],
    parse: { kind: 'regex-lines', pattern: '^(?<src>\\S+)\\s+(?<files>\\d+)\\s+(?<withFrames>\\d+)\\s+(?<frames>\\d+)\\s+(?<panes>\\d+)\\s+(?<judged>\\d+)\\s+(?<off>\\d+)\\s+(?<filesDefect>\\d+)\\s+(?<rate>[\\d.]+)%', groups: ['src', 'files', 'withFrames', 'frames', 'panes', 'judged', 'off', 'filesDefect', 'rate'] },
    columns: [
      { key: 'src', label: 'class', path: 'src' },
      { key: 'files', label: 'files', path: 'files' },
      { key: 'off', label: 'panes off frame', path: 'off' },
      { key: 'filesDefect', label: 'files w/ defect', path: 'filesDefect' },
      { key: 'rate', label: 'rate %', path: 'rate' },
    ],
    evidence: { runDir: true },
    duration: '500 files ≈ 10-20 min',
  },
  {
    id: 'missing-geometry-census',
    group: 'Windows, parts & corpus checks',
    title: 'Missing-geometry census',
    answers: 'Which part names the renderer cannot resolve for the selected sets, how often, from which source class and WHY (alias ladder, inline 0 FILE, unresolved sub-parts) — resolution rules imported from the renderer.',
    entry: 'scripts/missing-geometry-census.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'set', batch: 'one-process',
    args: ['--sets', { items: 'csv' }, '--json', { runDir: 'missing-geometry.json' }, { opt: 'lib' }, { opt: 'base' }, { opt: 'noSubparts' }, { opt: 'fresh' }],
    options: [
      { key: 'lib', flag: 'lib', render: 'space', type: 'string', help: 'Offline library roots, comma-separated (official,unofficial). Blank = the prod mirror.' },
      { key: 'base', flag: 'base', render: 'space', type: 'string', help: 'Mirror base URL (default https://craftmatic.click/ldraw-parts).' },
      { key: 'noSubparts', flag: 'no-subparts', render: 'switch', type: 'boolean', default: false, help: 'Skip the deep sub-part pass.' },
      { key: 'fresh', flag: 'fresh', render: 'switch', type: 'boolean', default: false, help: 'Discard the cached library listing.' },
    ],
    parse: { kind: 'regex-lines', pattern: '^TOTAL: (?<missing>\\d+) missing of (?<refs>\\d+) placements \\((?<pct>[^)]*)\\)', groups: ['missing', 'refs', 'pct'] },
    columns: [
      { key: 'missing', label: 'missing', path: 'missing' },
      { key: 'refs', label: 'placements', path: 'refs' },
      { key: 'pct', label: 'loss', path: 'pct' },
    ],
    evidence: { runDir: true },
    duration: '1-10 min depending on the selection and the mirror',
    docs: ['docs/lego-sources-guide.md'],
    notes: 'Without --sets it draws its own sample (--per-class / --flagship); the console always passes the selection.',
  },
  {
    id: 'check-missing-parts',
    group: 'Windows, parts & corpus checks',
    title: 'Missing parts per set (banner equivalent)',
    answers: 'What the LEGO tab\'s "N piece(s) of M part type(s) not in library" banner would say for each set, against the R2 mirror or a local library.',
    entry: 'scripts/check-missing-parts.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'set', batch: 'one-process',
    args: [{ opt: 'local' }, { opt: 'base' }, { items: 'args' }],
    options: [
      { key: 'local', flag: 'local', render: 'space', type: 'path', help: `Local library root (e.g. ${LDRAW_ROOT}). Blank = the prod mirror.` },
      { key: 'base', flag: 'base', render: 'space', type: 'string', help: 'Mirror base URL.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~5-30 s per set',
    docs: ['docs/lego-sources-guide.md'],
    notes: 'Model files come from the same index + R2 corpus the app uses.',
  },

  // ───────────────────────── Index & scoreboard ─────────────────────────
  {
    id: 'scoreboard',
    group: 'Index & scoreboard',
    title: 'geograde scoreboard (resolve / grade / report)',
    answers: 'Corpus-wide quality board of the sets users see first: resolve the auto-load pick per set, grade it (and alternatives), report pass rates and rerank proposals.',
    entry: 'geograde/scoreboard.py',
    runtime: 'python', cwd: 'clego', input: 'none', batch: 'one-process',
    args: [{ opt: 'resolve' }, { opt: 'grade' }, { opt: 'report' }, { opt: 'alts' }, { opt: 'allEntries' }, { opt: 'full' }, { opt: 'top' }, { opt: 'workers' }, { opt: 'limit' }, { opt: 'outDir' }],
    options: [
      { key: 'resolve', flag: 'resolve', render: 'switch', type: 'boolean', default: true, help: 'Phase 1: resolve the primary pick per set.' },
      { key: 'grade', flag: 'grade', render: 'switch', type: 'boolean', default: false, help: 'Phase 2: grade (resumable, appends jsonl).' },
      { key: 'report', flag: 'report', render: 'switch', type: 'boolean', default: false, help: 'Phase 3: write the board + proposals.' },
      { key: 'alts', flag: 'alts', render: 'switch', type: 'boolean', default: false, help: 'With --grade: alternatives of DEFECTIVE sets.' },
      { key: 'allEntries', flag: 'all-entries', render: 'switch', type: 'boolean', default: false, help: 'With --grade: primaries and all alternatives.' },
      { key: 'full', flag: 'full', render: 'switch', type: 'boolean', default: false, help: 'The whole indexed catalog, not the top N.' },
      { key: 'top', flag: 'top', render: 'space', type: 'number', default: 500, help: 'Top N sets by the LEGO tab\'s default score.' },
      { key: 'workers', flag: 'workers', render: 'space', type: 'number', default: 4, help: 'Grader workers (script default 8; 4 keeps the box usable).' },
      { key: 'limit', flag: 'limit', render: 'space', type: 'number', default: 0, help: 'Stop after N (0 = all).' },
      { key: 'outDir', flag: 'out-dir', render: 'space', type: 'path', required: true, default: '{runDir}/board', help: 'Isolated board directory; the live geograde/ boards stay untouched. Point it at an existing board to resume.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: { runDir: true },
    duration: 'resolve ≈ 1 min; grade top-500 ≈ 1-3 h at 4 workers; --full ≈ a day',
    docs: ['docs/lego-sources-guide.md'],
    notes: 'The three phases are separate runs. --out-dir is required by the console so a run can never append to the live geograde/scoreboard_*.jsonl by accident.',
  },
  {
    id: 'changed-since-index',
    group: 'Index & scoreboard',
    title: 'Corpus files changed since the index',
    answers: 'Which corpus files differ (by sha256/12) from the bytes the index describes — exactly the listing a republish must carry.',
    entry: 'changed_since_index.py',
    runtime: 'python', cwd: 'clego', input: 'none', batch: 'one-process',
    args: [{ opt: 'index' }, '--out', { runDir: 'changed.txt' }],
    options: [{ key: 'index', flag: 'index', render: 'space', type: 'path', help: 'Index to compare against (default clego/lego-models-index.json).' }],
    parse: { kind: 'regex-lines', pattern: '(?<entries>\\d+) entries, (?<changed>\\d+) changed, (?<missing>\\d+) missing, (?<nohash>\\d+) without a hash', groups: ['entries', 'changed', 'missing', 'nohash'] },
    columns: [
      { key: 'entries', label: 'entries', path: 'entries' },
      { key: 'changed', label: 'changed', path: 'changed' },
      { key: 'missing', label: 'missing', path: 'missing' },
    ],
    evidence: { runDir: true },
    duration: '~2-5 min (hashes 20k files)',
    docs: ['docs/lego-sources-guide.md'],
    notes: 'Feed changed.txt to the R2 publisher as --only-file.',
  },
  {
    id: 'build-index-candidate',
    group: 'Index & scoreboard',
    title: 'Build a CANDIDATE model index',
    answers: 'What the best-model-per-set index would look like from the current corpus + an optional isolated scoreboard — written to one file, the live copies untouched.',
    entry: 'build_model_index.py',
    runtime: 'python', cwd: 'clego', input: 'none', batch: 'one-process',
    args: [{ opt: 'scoreboard' }, '--out', { runDir: 'candidate-index.json' }],
    options: [{ key: 'scoreboard', flag: 'scoreboard', render: 'space', type: 'path', help: 'An isolated complete board (scoreboard_full.json) to stamp asm/sev from.' }],
    parse: { kind: 'none' }, columns: [],
    evidence: { runDir: true },
    duration: '~5-10 min',
    docs: ['docs/lego-sources-guide.md', 'TASKS-BEDROCK-ADDON.md'],
  },
  {
    id: 'build-index-live',
    group: 'Index & scoreboard',
    title: 'Build the LIVE model index',
    answers: 'Regenerates lego-models-index.json in clego AND web/public/ (what the app ships). Not reversible from the console.',
    entry: 'build_model_index.py',
    runtime: 'python', cwd: 'clego', input: 'none', batch: 'one-process',
    args: [{ opt: 'scoreboard' }],
    options: [{ key: 'scoreboard', flag: 'scoreboard', render: 'space', type: 'path', help: 'An isolated complete board to stamp from (default: geograde/scoreboard_full.json + scoreboard_extra.json).' }],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~5-10 min',
    danger: { why: 'Overwrites the live index in both checkouts (the file the web app and the publisher read).' },
    docs: ['docs/lego-sources-guide.md'],
  },

  // ───────────────────────── Publishing (outward) ─────────────────────────
  {
    id: 'sync-models-r2',
    group: 'Publishing (outward)',
    title: 'Publish model files to R2',
    answers: 'Uploads the selected indexed corpus paths (or everything missing) to the public lego-models bucket, then the index unless --no-index. Dry-run shows the plan.',
    entry: 'sync_models_r2.py',
    runtime: 'python', cwd: 'clego', input: 'index-path', batch: 'one-process',
    args: [{ opt: 'dryRun' }, { opt: 'status' }, { opt: 'verifyLegacy' }, '--only-file', { itemsFile: true }, { opt: 'noIndex' }],
    options: [
      { key: 'dryRun', flag: 'dry-run', render: 'switch', type: 'boolean', default: true, help: 'Validate and show the upload plan without writing.' },
      { key: 'status', flag: 'status', render: 'switch', type: 'boolean', default: false, help: 'Counts only; never upload.' },
      { key: 'verifyLegacy', flag: 'verify-legacy', render: 'switch', type: 'boolean', default: false, help: 'Certify legacy rows by CDN byte readback; never PUT.' },
      { key: 'noIndex', flag: 'no-index', render: 'switch', type: 'boolean', default: true, help: 'Do not publish the index after the model uploads.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: { runDir: true },
    duration: '~70 files/min on the 6-thread pool (4,746 files ≈ 70 min)',
    danger: { why: 'Writes to the public R2 bucket that production serves. Prod caches /lego-models/* for 1 h and the index for 5 min.', dryRunOption: 'dryRun' },
    docs: ['docs/lego-sources-guide.md', 'TASKS-BEDROCK-ADDON.md'],
    notes: 'The selection\'s index paths are written to a listing and passed as --only-file, so only those files move. A bare sync (no selection, no dry-run) uploads every file missing from the receipts. Launch long publishes detached if the console might be closed.',
  },
  {
    id: 'sync-ldraw-r2',
    group: 'Publishing (outward)',
    title: 'Mirror the LDraw library to R2',
    answers: 'Uploads new/changed parts from the upstream release archives into the lego-models bucket (ldraw/ keys), stateless delta by MD5 vs etag.',
    entry: 'scripts/sync-ldraw-r2.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'dryRun' }, { opt: 'workers' }, { opt: 'limit' }, { opt: 'only' }],
    options: [
      { key: 'dryRun', flag: 'dry-run', render: 'switch', type: 'boolean', default: true, help: 'Compute the delta, upload nothing.' },
      { key: 'workers', flag: 'workers', render: 'space', type: 'number', default: 4, help: 'Upload workers (script default 8).' },
      { key: 'limit', flag: 'limit', render: 'space', type: 'number', help: 'Stop after N uploads.' },
      { key: 'only', flag: 'only', render: 'space', type: 'string', help: 'Regex over relative paths.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: 'delta ≈ minutes; a full upload ≈ hours',
    danger: { why: 'Writes to the public R2 bucket that serves geometry to production.', dryRunOption: 'dryRun' },
    docs: ['docs/lego-sources-guide.md'],
  },
  {
    id: 'warm-parts-cache',
    group: 'Publishing (outward)',
    title: 'Warm the prod parts edge cache',
    answers: 'GETs every primitive (p/, p/48/) through craftmatic.click/ldraw-parts at a polite rate so the edge holds a 200 for a week.',
    entry: 'scripts/warm-parts-cache.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'rps' }, { opt: 'dirs' }],
    options: [
      { key: 'rps', flag: 'rps', render: 'space', type: 'number', default: 3, help: 'Requests per second.' },
      { key: 'dirs', flag: 'dirs', render: 'space', type: 'string', default: 'p,p/48', help: 'Library dirs to walk.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~10-20 min at 3 rps',
    danger: { why: 'Sustained traffic against production (read-only, but outward).' },
  },

  // ────────────────────────────── Device ──────────────────────────────
  {
    id: 'pixel-shot',
    group: 'Device (Pixel)',
    title: 'Device screenshot (size-safe JPEG)',
    answers: 'A ≤1999 px q85 JPEG of the connected Android device\'s screen.',
    entry: 'scripts/_pixel_shot.sh',
    runtime: 'bash', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'name' }, { opt: 'outdir' }, { opt: 'serial' }],
    options: [
      { key: 'name', flag: '', render: 'positional', type: 'string', required: true, default: 'console', help: 'File stem.' },
      { key: 'outdir', flag: '', render: 'positional', type: 'path', help: 'Default output/bedrock-entity-qa/shots.' },
      { key: 'serial', flag: 'ANDROID_SERIAL', render: 'env', type: 'string', help: 'adb serial (ip:port) — the wireless port rotates; check `adb devices -l`.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: { dir: 'output/bedrock-entity-qa/shots' },
    duration: '~3 s',
    danger: { why: 'Talks to the connected device over adb.' },
    needs: ['adb', 'ImageMagick (magick)'],
    docs: ['docs/bedrock-addon-guide.md'],
  },
  {
    id: 'pixel-cmd',
    group: 'Device (Pixel)',
    title: 'Type a chat command into Minecraft',
    answers: 'Runs one chat command (e.g. /summon craftmatic:… ~ ~ ~5) on the device through measured tap coordinates (Pixel 8 Pro, 2244×1008 landscape).',
    entry: 'scripts/_pixel_cmd.sh',
    runtime: 'bash', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'command' }, { opt: 'serial' }],
    options: [
      { key: 'command', flag: '', render: 'positional', type: 'string', required: true, help: 'The chat command, with its leading slash.' },
      { key: 'serial', flag: 'ANDROID_SERIAL', render: 'env', type: 'string', help: 'adb serial (ip:port).' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~6 s',
    danger: { why: 'Injects input into the game on the device; coordinates are device-specific.' },
    needs: ['adb'],
    docs: ['docs/bedrock-addon-guide.md'],
  },
  {
    id: 'pixel-perf',
    group: 'Device (Pixel)',
    title: 'Device memory / fps / load harness',
    answers: 'mem: one meminfo sample; fps: SurfaceFlinger frame-interval stats; ref: capture the in-world HUD crop; load: time a world load to in-world.',
    entry: 'scripts/_pixel_perf.sh',
    runtime: 'bash', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'mode' }, { opt: 'label' }, { opt: 'outdir' }, { opt: 'serial' }],
    options: [
      { key: 'mode', flag: '', render: 'positional', type: 'enum', values: ['mem', 'fps', 'ref', 'load'], required: true, default: 'mem', help: 'Harness mode.' },
      { key: 'label', flag: '', render: 'positional', type: 'string', default: 'console', help: 'Sample label (not used by ref).' },
      { key: 'outdir', flag: '', render: 'positional', type: 'path', help: 'Default output/bedrock-entity-qa/perf.' },
      { key: 'serial', flag: 'ANDROID_SERIAL', render: 'env', type: 'string', required: true, help: 'adb serial (ip:port) — the script refuses to run without it.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: { dir: 'output/bedrock-entity-qa/perf' },
    duration: 'mem/fps ≈ 10 s; load ≈ 1-3 min',
    danger: { why: 'Drives the device (taps the world tile in load mode).' },
    needs: ['adb'],
    docs: ['docs/bedrock-addon-guide.md'],
    notes: 'For mode=ref the label is ignored by the script; leave it blank.',
  },

  // ─────────────────────────── Browser gates ───────────────────────────
  {
    id: 'lego-visual-fixtures',
    group: 'Browser gates (dev server on :4000)',
    title: 'Visual + geometric fixtures',
    answers: 'Drives the REAL app through the indexed-source path for the pinned fixtures: source hash, fixed cameras, explode round-trip transforms and per-fixture geometry assertions.',
    entry: 'scripts/lego-visual-fixtures.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'only' }, { opt: 'out' }],
    options: [
      { key: 'only', flag: 'only', render: 'space', type: 'string', help: 'One fixture name.' },
      { key: 'out', flag: 'out', render: 'space', type: 'path', help: 'Output dir.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~2-5 min',
    needs: ['bun dev:web on :4000', 'Chrome'],
    docs: ['docs/testing-guide.md'],
  },
  {
    id: 'lego-perf-baseline',
    group: 'Browser gates (dev server on :4000)',
    title: 'Load-performance baseline',
    answers: 'Cold vs warm load, /ldraw-parts request counts, geometry coverage, composite time, renderer.info and JS heap for a set, plus a mobile-profile pass.',
    entry: 'scripts/lego-perf-baseline.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'set', batch: 'per-item', setRevision: true,
    args: ['--set', { item: true }, { opt: 'out' }],
    options: [{ key: 'out', flag: 'out', render: 'space', type: 'path', help: 'Output dir.' }],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~3-6 min per set',
    needs: ['bun dev:web on :4000', 'Chrome'],
    docs: ['docs/testing-guide.md', 'docs/lego-perf-baseline-2026-09-09.md'],
    notes: 'The script takes the CATALOG set number with revision (10316-1); the console appends -1 to a bare index set number.',
  },
  {
    id: 'lego-export-validate',
    group: 'Browser gates (dev server on :4000)',
    title: '3D export byte-identity after explode',
    answers: 'Do OBJ/STL/3MF/GLB exports stay byte-identical after an explode 0 → 100 → 0 round trip, and is the OBJ bbox at 8 mm/stud?',
    entry: 'scripts/lego-export-validate.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'set', batch: 'per-item',
    args: ['--only', { item: true }, { opt: 'out' }],
    options: [{ key: 'out', flag: 'out', render: 'space', type: 'path', help: 'Output dir.' }],
    parse: { kind: 'none' }, columns: [],
    evidence: {},
    duration: '~2-4 min per set',
    needs: ['bun dev:web on :4000', 'Chrome'],
    docs: ['docs/testing-guide.md'],
  },
  {
    id: 'export-browser-check',
    group: 'Browser gates (dev server on :4000)',
    title: 'Minecraft export through the real LEGO tab',
    answers: 'Does the Worker export complete and download through the settings popover + progress banner, in how long, with which phases?',
    entry: 'scripts/_export_browser_check.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'model', accepts: ['io', 'mpd', 'ldr', 'lxf'], batch: 'per-item',
    args: [{ item: true }, { opt: 'label' }, { opt: 'shapes' }, { opt: 'format' }],
    options: [
      { key: 'label', flag: '', render: 'positional', type: 'string', default: 'console', help: 'Run label.' },
      { key: 'shapes', flag: 'shapes', render: 'space', type: 'enum', values: ['on', 'off'], help: 'Seed the persisted block-shape setting.' },
      { key: 'format', flag: 'format', render: 'space', type: 'enum', values: ['schem', 'litematic', 'mcpack'], help: 'Download-menu entry to drive.' },
    ],
    parse: { kind: 'none' }, columns: [],
    evidence: { dir: 'output/vox-work' },
    duration: '~1-5 min per model',
    needs: ['bun dev:web on :4000', 'Chrome'],
    docs: ['docs/minecraft-pipeline-guide.md'],
  },
  {
    id: 'lego-probe',
    group: 'Browser gates (dev server on :4000)',
    title: 'Headless LEGO-tab probe (explode + instance dump + PNGs)',
    answers: 'Can explode state displace an assembled model; every instance\'s world position + part id; fixed-camera canvas PNGs.',
    entry: 'scripts/_lego-probe.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'set', batch: 'per-item',
    args: [{ item: true }, { runDir: 'probe' }, { opt: 'label' }],
    options: [{ key: 'label', flag: '', render: 'positional', type: 'string', help: 'Optional label.' }],
    parse: { kind: 'json-last' }, columns: [],
    evidence: { runDir: true },
    duration: '~1-4 min per set',
    needs: ['bun dev:web on :4000', 'Chrome'],
    docs: ['docs/testing-guide.md'],
  },
  {
    id: 'minifig-browser-check',
    group: 'Browser gates (dev server on :4000)',
    title: 'Custom-minifig popover check',
    answers: 'Open the popover, round-trip a backpack through the portable code, export the creator-wand pack and inspect its script/controllers.',
    entry: 'scripts/_minifig_browser_check.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ runDir: 'minifig-browser-check' }],
    options: [],
    parse: { kind: 'none' }, columns: [],
    evidence: { runDir: true },
    duration: '~1-2 min',
    needs: ['bun dev:web on :4000', 'Chrome'],
    docs: ['docs/minifig-creator-wand.md'],
  },
  {
    id: 'schem-external-check',
    group: 'Browser gates (dev server on :4000)',
    title: 'schemat.io external-viewer gate',
    answers: 'Does a reference .schem render correctly in a third-party viewer (the only place a palette/colour-space mistake is visible)?',
    entry: 'scripts/schem-external-check.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'model', accepts: ['io', 'schem'], batch: 'per-item',
    args: [{ item: true }, { opt: 'label' }],
    options: [{ key: 'label', flag: '', render: 'positional', type: 'string', default: 'console', help: 'Screenshot label.' }],
    parse: { kind: 'none' }, columns: [],
    evidence: { dir: 'output/schem-backlog' },
    duration: '~2-5 min per model',
    danger: { why: 'Uploads the export to a third-party site (schemat.io).' },
    needs: ['Chrome'],
    docs: ['docs/minecraft-pipeline-guide.md', 'TASKS-SCHEM-BACKLOG.md'],
  },
  {
    id: 'prod-check',
    group: 'Browser gates (dev server on :4000)',
    title: 'Production load check',
    answers: 'Does a set load on craftmatic.click, what does the status line say, which model/ldd assets were requested; iso/front canvas screenshots.',
    entry: 'scripts/_prod-check.mjs',
    runtime: 'node', cwd: 'craftmatic', input: 'set', batch: 'per-item',
    args: [{ item: true }, { runDir: 'prod' }],
    options: [],
    parse: { kind: 'json-last' },
    columns: [{ key: 'status', label: 'status', path: 'status' }, { key: 'assets', label: 'assets', path: 'assets.length' }],
    evidence: { runDir: true },
    duration: '~1-5 min per set',
    needs: ['Chrome', 'network'],
    notes: 'Read-only against production. Keep concurrency at 1-2: each item is a headless Chrome.',
  },

  // ───────────────────────── Provenance & freshness ─────────────────────────
  {
    id: 'pipeline-stamp',
    group: 'Provenance & freshness',
    title: 'Export pipeline provenance stamp',
    answers: 'The content hash + last commit of the export pipeline\'s import closure, whether it is dirty, and (with --files) the closure itself.',
    entry: 'scripts/pipeline-stamp.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [{ opt: 'files' }],
    options: [{ key: 'files', flag: 'files', render: 'switch', type: 'boolean', default: false, help: 'Also list the closure.' }],
    parse: { kind: 'json-last' }, columns: [],
    evidence: {},
    duration: '~2 s',
    docs: ['docs/bedrock-addon-guide.md'],
  },
  {
    id: 'source-freshness',
    group: 'Provenance & freshness',
    title: 'Catalog vs model-index freshness',
    answers: 'Which searchable sets have no model, and which of those a known channel (DBIX LXFML, OMR) could supply today.',
    entry: 'scripts/source-freshness.ts',
    runtime: 'bun', cwd: 'craftmatic', input: 'none', batch: 'one-process',
    args: [],
    options: [],
    parse: { kind: 'none' }, columns: [],
    evidence: { dir: 'web/public' },
    duration: '~1-2 min (fetches the live index + DBIX SKU list)',
    needs: ['network', 'bun run prebuild artifacts (lego-catalog.json, omr-index.json)'],
    docs: ['docs/lego-sources-guide.md'],
    notes: 'Writes web/public/source-freshness.json (a committed artifact) — review the diff before committing.',
  },
];

/**
 * Scripts present in `scripts/` (or clego) that the console deliberately does
 * NOT wire, with the reason. Reviewable, so a wrong judgement is one line to fix.
 */
export const STALE: readonly { pattern: string; why: string }[] = [
  { pattern: 'scripts/batch-v*.sh, batch-voxelize-v*.sh, grade-v*.ts, render-v*.ts, render-*.ts, _render-*.ts', why: 'Numbered iteration relics of the Minecraft map/tiles pipeline (v8-v79); each pins one experiment\'s parameters.' },
  { pattern: 'scripts/audit-*.ts, check-42049.ts, check-8855.ts, check-p.ts, check-tires.ts, test-bracket*.ts, part-lookup.ts, full-audit.ts, diagnose-model.ts', why: 'One-off part-dimension audits from the bounding-box voxelizer era; the geometry voxelizer superseded the question.' },
  { pattern: 'scripts/grade-models.ts, grade-geometry.ts, geometry-quality-loop.ts, visual-grade.ts, showcase-grade.ts, vlm-grade.ts, vlm-batch-render.mjs, iterate-grade.ts, quick-grade-2.ts', why: 'VLM grading loops keyed to `.claude/*-state.json` Stop-hook rounds; need API keys and grade a fixed set list. Not an operator gate.' },
  { pattern: 'scripts/verify-lego-visual.ts', why: 'Its own header says it covers neither the renderer nor per-part placement and fetches unpinned OMR files.' },
  { pattern: 'scripts/_io_track_count.ts, _hair_probe.ts, _minifig_slice.ts, _s1_autopsy.ts, _brick_near.ts, _calib_table.ts, _grade-*.ts, _compare-*.ts, _analyze-*.ts, _debug-tiles.ts, _imginfo.ts', why: 'One-off diagnostics for defects that shipped fixed (floating hair, track counts, S1 palette).' },
  { pattern: 'scripts/_probe-geo-audit.ts, _probe-hull-lod.ts, _bedrock_probe_pack.py, master-addon-frontier.ts, block-route-per-set.ts, part-library-cost.ts, corpus-part-census.ts, decomposition-pack-ab.ts, part-decomposition-compare.ts, part-block-bounds.ts', why: 'Throwaway probes of the master-add-on / entity-instancing audit; conclusions recorded in docs/bedrock-addon-guide.md ("Entity instancing is a NO-GO"). Don\'t retry.' },
  { pattern: 'scripts/_element_survey.ts, _textured_survey.ts, _res_survey.ts, _tri_color_survey*.ts, _schem_profile.ts, _schem_encode_profile.ts, _vox_range.ts, _vox_partcheck.ts', why: 'Slice evidence for shipped palette/shape/profile decisions; rerun only when re-deciding them.' },
  { pattern: 'scripts/_schem_pipeline.ts, _lite_ref.ts', why: 'Fixed 20-set round-trip QA and a synthetic litematic digest — covered by the vitest suites now.' },
  { pattern: 'scripts/_verify-sets-*.mjs/.sh, _rerank-visual.mjs, _rerank-visual-sheet.py, recapture-all.sh, batch-recapture-v2.sh', why: 'Round drivers for the 2026-09-18/20 review and rerank rounds (closed).' },
  { pattern: 'scripts/renderer-improve-loop.mjs, renderer-pass-isolation.mjs, loop-check.mjs, showcase-loop-check.mjs, visual-loop-check.mjs, improve-next.sh, run-claude-pass.sh', why: 'Stop-hook automation (inactive) — not operator commands.' },
  { pattern: 'scripts/gen-*.ts/.py/.mjs, prebuild-*.ts, scrape-lego-thumbs.ts, build-hotschem.mjs, hotschem-zip.mjs, fix-android-binaries.mjs', why: 'Build-time generators with package.json scripts of their own (prebuild:*, gen-part-dims); rerun when the library or census changes, not per model.' },
  { pattern: 'scripts/ldcad_connectivity.py', why: 'Its header records the conclusion (snaps alone cannot certify connectivity); the hybrid contact check lives in the engine.' },
  { pattern: 'scripts/pdf-recon/*', why: 'PDF reconstruction research harnesses — see docs/pdf-pipeline-guide.md; out of this console\'s (pack/placement/window) scope.' },
  { pattern: 'scripts/*tiles*, *satellite*, geocode-addresses.ts, generate-houses.ts, eval-tiles.ts, cdp-tiles-test.ts, download-*.ts, schem-receiver.ts, live-delivery-workerd-check.mjs, inspect-hosted-ws-frame.mjs, install-windows-bedrock.ps1', why: 'Minecraft map / tiles / live-delivery pipeline, not the LEGO toolchain.' },
  { pattern: 'clego/_*.py, geograde/_*.py', why: 'Underscore-prefixed probes and round drivers in clego (io-origin, mecabricks, polish, triage rounds); their outcomes are in the geograde boards and docs/lego-sources-guide.md.' },
  { pattern: 'clego/recon_figure_assemble.py, geograde/dbix_polish.py, sync_*.py (kept/polished/mecabricks/dbix_v3)', why: 'Corpus REWRITE tools (in-place figure snapping, polish, per-source publishers) — run from clego by hand with their own dry-run; a console batch over 2,000 files is not the safe shape for them.' },
];

export const operationById = (id: string): Operation | undefined => OPERATIONS.find(o => o.id === id);

export const GROUPS: readonly Operation['group'][] = [...new Set(OPERATIONS.map(o => o.group))];
