/**
 * Generate the simulator's catalog of the REAL Script API surface
 * (`web/src/sim/script-host/api-catalog.ts`) from the published type
 * declarations of `@minecraft/server` and `@minecraft/server-ui`.
 *
 * Why: the simulator's mock answers an API member it does not implement by
 * throwing `Unmodelled` and recording it - but only when the game HAS that
 * member. A name the game lacks reads `undefined` on the device too, so a
 * feature probe (`entity.someNewMethod?.()`) must not be reported. The catalog
 * is how the mock tells the two apart.
 *
 * Usage (the tarballs from the npm registry, unpacked anywhere):
 *   bun scripts/_sim_api_catalog.ts <server/index.d.ts> <server-ui/index.d.ts> [--out=<file>]
 * The versions must be the ones the packs' manifests declare
 * (`@minecraft/server` 2.9.0, `@minecraft/server-ui` 2.1.0 on 2026-09-30).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import * as ts from 'typescript';

const args = process.argv.slice(2);
const flag = (n: string): string | undefined => args.find(a => a.startsWith(`--${n}=`))?.slice(n.length + 3);
const files = args.filter(a => !a.startsWith('--'));
if (files.length !== 2) { console.error('usage: bun scripts/_sim_api_catalog.ts <server/index.d.ts> <server-ui/index.d.ts> [--out=<file>]'); process.exit(2); }
const out = flag('out') ?? 'web/src/sim/script-host/api-catalog.ts';

interface Entry { kind: 'class' | 'interface' | 'enum'; extends: string[]; members: Set<string>; statics: Set<string> }

function read(path: string): { entries: Map<string, Entry>; exports: string[]; version: string } {
  const text = readFileSync(path, 'utf8');
  const src = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true);
  const entries = new Map<string, Entry>();
  const exports: string[] = [];
  const version = /@minecraft\/[\w-]+@?\s*([\d.]+)/.exec(text)?.[1] ?? /"version":\s*"([^"]+)"/.exec(text)?.[1] ?? '';
  const nameOf = (n: ts.PropertyName | undefined): string | undefined => (n && (ts.isIdentifier(n) || ts.isStringLiteral(n)) ? n.text : undefined);
  for (const st of src.statements) {
    const exported = ts.canHaveModifiers(st) && ts.getModifiers(st)?.some(m => m.kind === ts.SyntaxKind.ExportKeyword);
    if (ts.isClassDeclaration(st) && st.name) {
      const e: Entry = { kind: 'class', extends: [], members: new Set(), statics: new Set() };
      for (const h of st.heritageClauses ?? []) for (const t of h.types) e.extends.push(t.expression.getText(src));
      for (const m of st.members) {
        const n = nameOf(m.name);
        if (!n) continue;
        const isStatic = ts.canHaveModifiers(m) && ts.getModifiers(m)?.some(k => k.kind === ts.SyntaxKind.StaticKeyword);
        (isStatic ? e.statics : e.members).add(n);
      }
      entries.set(st.name.text, e);
      if (exported) exports.push(st.name.text);
    } else if (ts.isInterfaceDeclaration(st)) {
      const e: Entry = { kind: 'interface', extends: [], members: new Set(), statics: new Set() };
      for (const h of st.heritageClauses ?? []) for (const t of h.types) e.extends.push(t.expression.getText(src));
      for (const m of st.members) { const n = nameOf(m.name); if (n) e.members.add(n); }
      entries.set(st.name.text, e);
    } else if (ts.isEnumDeclaration(st)) {
      const e: Entry = { kind: 'enum', extends: [], members: new Set(), statics: new Set() };
      for (const m of st.members) { const n = nameOf(m.name); if (n) e.members.add(n); }
      entries.set(st.name.text, e);
      if (exported) exports.push(st.name.text);
    } else if (ts.isVariableStatement(st) && exported) {
      for (const d of st.declarationList.declarations) if (ts.isIdentifier(d.name)) exports.push(d.name.text);
    } else if (ts.isFunctionDeclaration(st) && st.name && exported) exports.push(st.name.text);
  }
  // Flatten inheritance so each entry lists every member it answers to.
  const resolve = (name: string, seen = new Set<string>()): Set<string> => {
    const e = entries.get(name);
    if (!e || seen.has(name)) return new Set();
    seen.add(name);
    const all = new Set(e.members);
    for (const p of e.extends) for (const m of resolve(p.replace(/<.*$/, ''), seen)) all.add(m);
    return all;
  };
  for (const [name, e] of entries) e.members = resolve(name);
  return { entries, exports, version };
}

const server = read(files[0]!), ui = read(files[1]!);
const lines: string[] = [];
lines.push('/**');
lines.push(' * GENERATED by `bun scripts/_sim_api_catalog.ts` from the published type');
lines.push(' * declarations of `@minecraft/server` and `@minecraft/server-ui` (the versions');
lines.push(' * the packs\' manifests declare). Do not edit by hand: re-run the generator.');
lines.push(' *');
lines.push(' * Every class/interface of the real API with the members it answers to');
lines.push(' * (inherited ones included), each enum with its members, and each module\'s');
lines.push(' * exports. The mock consults it to tell an UNMODELLED member (the game has it,');
lines.push(' * the simulator does not: throw and record) from a name the game lacks');
lines.push(' * (`undefined`, as on the device).');
lines.push(' */');
lines.push('');
lines.push('/** One API type: its kind and member names (instance members; `statics` for a class\'s static ones). */');
lines.push('export interface ApiType { kind: \'class\' | \'interface\' | \'enum\'; members: readonly string[]; statics?: readonly string[] }');
lines.push('');
const dump = (label: string, r: ReturnType<typeof read>): void => {
  lines.push(`/** \`${label}\`: exports. */`);
  lines.push(`export const ${label === '@minecraft/server' ? 'SERVER' : 'SERVER_UI'}_EXPORTS: readonly string[] = ${JSON.stringify(r.exports.sort())};`);
  lines.push('');
  lines.push(`/** \`${label}\`: types by name. */`);
  lines.push(`export const ${label === '@minecraft/server' ? 'SERVER' : 'SERVER_UI'}_TYPES: Readonly<Record<string, ApiType>> = {`);
  for (const [name, e] of [...r.entries].sort((a, b) => a[0].localeCompare(b[0]))) {
    const statics = e.statics.size ? `, statics: ${JSON.stringify([...e.statics].sort())}` : '';
    lines.push(`  ${JSON.stringify(name)}: { kind: '${e.kind}', members: ${JSON.stringify([...e.members].sort())}${statics} },`);
  }
  lines.push('};');
  lines.push('');
};
dump('@minecraft/server', server);
dump('@minecraft/server-ui', ui);
writeFileSync(out, lines.join('\n'));
console.log(`${out}: ${server.entries.size} server types, ${ui.entries.size} ui types; exports ${server.exports.length} + ${ui.exports.length}`);
