/**
 * Generate web/src/engine/ldconfig-colors.generated.ts from LDraw.org's
 * LDConfig.ldr (vendored at scripts/ldconfig/LDConfig.ldr).
 *
 * Why: the hand-kept colour tables (ldraw-colors.ts LDRAW_COLOR_RGB,
 * ldd-colors.ts LDD_TO_LDRAW) predate 144 LDraw codes and 45 LEGO colour
 * ids. An unknown LEGO id fell back to Light Bluish Grey (71) and an unknown
 * LDraw code drew #808080 — 42703's 2026 mini-dolls came out grey and its
 * Bright Blue Violet rails lost their colour (device report 2026-09-24).
 * The generated maps FILL only: every hand-kept entry still wins.
 *
 * Output:
 *   LDCONFIG_RGB     LDraw code -> '#RRGGBB'
 *   LDCONFIG_ALPHA   LDraw code -> ALPHA (0-255), only for codes below 255
 *   LDCONFIG_LEGOID  LEGO (= LDD material) id -> LDraw code, from the
 *                    `// LEGOID <n>` comment LDConfig puts above a colour
 *
 * Usage: bun scripts/gen-ldconfig-colors.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'scripts/ldconfig/LDConfig.ldr';
const OUT = 'web/src/engine/ldconfig-colors.generated.ts';

const lines = readFileSync(SRC, 'utf8').split(/\r?\n/);
const version = lines.find(l => l.startsWith('0 !LDRAW_ORG'))?.slice(2) ?? 'unknown';
const rgb: Record<number, string> = {};
const alpha: Record<number, number> = {};
const legoId: Record<number, number> = {};
lines.forEach((line, i) => {
  const m = /^0 !COLOUR (\S+)\s+CODE\s+(\d+)\s+VALUE\s+#([0-9A-Fa-f]{6})(.*)$/.exec(line);
  if (!m) return;
  const code = Number(m[2]);
  rgb[code] = `#${m[3]!.toUpperCase()}`;
  const a = /ALPHA\s+(\d+)/.exec(m[4]!);
  if (a && Number(a[1]) < 255) alpha[code] = Number(a[1]);
  // The LEGOID comment sits on the line above the colour it names.
  for (const id of (lines[i - 1] ?? '').matchAll(/LEGOID\s+(\d+)/g)) {
    const n = Number(id[1]);
    if (!(n in legoId)) legoId[n] = code;
  }
});

const obj = (o: Record<number, string | number>): string =>
  `{\n${Object.entries(o).sort((a, b) => Number(a[0]) - Number(b[0])).map(([k, v]) => `  ${k}: ${typeof v === 'string' ? `'${v}'` : v},`).join('\n')}\n}`;
const text = `// GENERATED by scripts/gen-ldconfig-colors.ts from ${SRC}
// (${version}). Do not edit; re-run the generator after updating the source.

/** LDraw colour code -> '#RRGGBB' for every colour LDConfig defines. */
export const LDCONFIG_RGB: Readonly<Record<number, string>> = ${obj(rgb)};

/** LDraw colour code -> ALPHA (0-255) for the colours LDConfig makes translucent. */
export const LDCONFIG_ALPHA: Readonly<Record<number, number>> = ${obj(alpha)};

/** LEGO colour id (the LDD material id) -> LDraw colour code, from LDConfig's LEGOID comments. */
export const LDCONFIG_LEGOID: Readonly<Record<number, number>> = ${obj(legoId)};
`;
writeFileSync(OUT, text);
console.log(`${OUT}: ${Object.keys(rgb).length} colours, ${Object.keys(alpha).length} translucent, ${Object.keys(legoId).length} LEGO ids (${version})`);
