"""Generate web/src/engine/bl-ldraw-map.ts from Studio's StudioColorDefinition.txt.

Columns (tab-separated, 0-indexed): 0=Studio code, 1=BL code, 2=LDraw code.
First row per key wins (matches clego io_authenticity.load_bl_to_ldraw).
Source: C:/git/clego/extracted/studio_release/app/data/StudioColorDefinition.txt
"""
import os

SRC = r'C:/git/clego/extracted/studio_release/app/data/StudioColorDefinition.txt'
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   '..', 'web', 'src', 'engine', 'bl-ldraw-map.ts')

m = {}
with open(SRC, encoding='utf-8-sig') as f:
    next(f)
    for line in f:
        col = line.rstrip('\n').split('\t')
        if len(col) < 3:
            continue
        for key in (col[0].strip(), col[1].strip()):
            if not key.isdigit():
                continue
            ldr = col[2].strip()
            if not ldr.lstrip('-').isdigit():
                continue
            m.setdefault(int(key), int(ldr))

lines = [
    '// AUTO-GENERATED by scripts/gen-bl-ldraw-map.py — do not edit by hand.',
    '// Source: Studio StudioColorDefinition.txt (col 0 = Studio code, col 1 = BL',
    '// code, col 2 = LDraw code; first row per key wins).',
    '//',
    '// Studio/BrickLink colour code -> standard LDraw colour code. Used ONLY to',
    "// detect which colour space an .io archive's chosen model entry uses (see",
    '// detectIoColorSpace in io-extractor.ts) — never conflate the two spaces.',
    '',
    'export const BL_TO_LDRAW: Record<number, number> = {',
]
for k in sorted(m):
    lines.append(f'  {k}: {m[k]},')
lines += ['};', '']
with open(os.path.normpath(OUT), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))
print(f'wrote {os.path.normpath(OUT)} with {len(m)} entries')
