/**
 * Device-measured facts about Bedrock that no documentation states, each with
 * the evidence it was measured by. The simulator's modules CONSULT this
 * registry (they read their numbers from it and name the quirk they apply),
 * so a fact is written once, next to its proof, and a device round that
 * re-measures it changes one row.
 *
 * `simulated` says what the engine does with a fact:
 *   - `modelled`: the engine behaves this way;
 *   - `partial`: modelled in the common case, with a stated gap;
 *   - `device-only`: the engine cannot show it (rendering, client timing,
 *     touch hardware). A scenario step that depends on it is reported
 *     `device-only`, never passed.
 *
 * Adding a fact: a row here with its evidence (a path under `output/`, a
 * commit, a doc section and the date), then the module that applies it reads
 * `quirk(<id>)`. See docs/sim-engine.md "The quirk registry".
 */

import { ACTOR_DRAW_CEILING_BLOCKS, RENDER_CULL_BLOCKS_PER_UNIT } from '../../engine/bedrock-lod-hull.js';

/** The engine module a quirk bears on. */
export type QuirkArea = 'world' | 'entity' | 'physics' | 'script-host' | 'input' | 'render' | 'camera' | 'ui' | 'commands' | 'sound';

export interface Quirk {
  id: QuirkId;
  /** The fact, as a rule the engine can apply. */
  rule: string;
  /** Where it was measured: evidence path, commit or doc section, and the date. */
  evidence: string;
  appliesTo: readonly QuirkArea[];
  simulated: 'modelled' | 'partial' | 'device-only';
  /** The measured numbers the engine uses (units in the key's name or the rule). */
  values?: Readonly<Record<string, number>>;
  /** For `partial`: what is not modelled. */
  gap?: string;
}

export type QuirkId =
  | 'add-rider-spawn-tick' | 'tp-dismounts' | 'rider-eye-above-seat' | 'seat-z-is-nose' | 'sneak-dismounts'
  | 'tap-is-hit' | 'hold-is-interact' | 'no-selection-box-passes-taps' | 'unloaded-block-undefined'
  | 'unloaded-entity-invisible' | 'group-removal-strips-base' | 'float-property-int-literal'
  | 'entity-id-leading-digit' | 'pushable-dropped' | 'form-deletes-percent' | 'hover-controller-speed'
  | 'hover-climb-descend' | 'hover-descend-needs-jump' | 'camera-pitch-limit' | 'camera-roll-animation-only'
  | 'client-entity-lag' | 'rider-yaw-lag' | 'actor-draw-ceiling' | 'cull-by-collision-box' | 'box-uv-sub-unit-faces'
  | 'coplanar-hatching' | 'slow-falling-gravity' | 'fill-volume-limit' | 'structure-load-keeps-states'
  | 'no-dismount-event' | 'dynamic-property-string-limit' | 'simulation-distance' | 'native-mount-bursts' | 'teleport-into-floor' | 'dismount-free-spot'
  | 'fly-sound-block-normal' | 'rider-seat-order' | 'add-rider-after-eject' | 'dynamic-properties-per-pack' | 'aabb-is-collision-box'
  | 'block-collision-x-mirrored' | 'rider-free-look';

const QUIRKS: readonly Quirk[] = [
  { id: 'add-rider-spawn-tick', rule: '`Rideable.addRider` can refuse a rider in the tick either entity spawned; a retry a couple of ticks later succeeds.', evidence: 'Pixel 2026-09-29: the orbit companion refused at placement and was seated seconds later by rides.js (TASKS-BEDROCK-ADDON.md "Nimbus follow-ups", `SEAT_RETRIES` in bedrock-placement-pack.ts)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'tp-dismounts', rule: 'Teleporting a riding player (`/tp @s ~ ~ ~`, and the script `teleport` of the rider itself) dismounts it; teleporting the RIDDEN entity carries its riders.', evidence: 'Saga 2026-09-29 (TASKS-BEDROCK-ADDON.md "Phones": "/tp @s ~ ~ ~ DISMOUNTS"); rides and coasters carry riders by teleporting the seat (physics spec §4.7)', appliesTo: ['entity', 'commands'], simulated: 'partial', gap: 'the script-API teleport of the rider itself is assumed to behave like /tp (not measured separately)' },
  { id: 'rider-eye-above-seat', rule: 'A riding player\'s eye is 1.12 blocks above its seat position.', evidence: 'CLAUDE.md "A minecraft:rideable seat\'s +Z is the entity\'s NOSE" (measured 2026-09-26); cockpit-seat.ts', appliesTo: ['entity', 'physics'], simulated: 'modelled', values: { eyeAboveSeatBlocks: 1.12 } },
  { id: 'seat-z-is-nose', rule: 'A `minecraft:rideable` seat position is in the entity frame with +Z the nose, turned by the entity yaw.', evidence: 'CLAUDE.md (every compiled seat was mirrored until 2026-09-26)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'sneak-dismounts', rule: 'Sneak (the touch sneak button) dismounts a rider from a vanilla rideable; there is no dismount event in @minecraft/server 2.9.', evidence: 'TASKS-BEDROCK-ADDON.md Nimbus ("sneak gets off"; a sneak at ALT 169 dropped the Saga rider 229 blocks), physics spec §4.6', appliesTo: ['entity', 'input'], simulated: 'modelled' },
  { id: 'tap-is-hit', rule: 'A touch TAP on an entity fires `entityHitEntity` (the player hits it); it does not fire the interact. The server accepts a hit (`SimulatedPlayer.attack()`, a ray from the head) out to ~7 blocks in Creative and ~3 in Survival; the simulator picks at 5, inside the Creative limit the QA worlds play in.', evidence: 'Pixel round 29c (10788 slide seat: three taps boarded nobody, `/ride` worked); add-on guide "The slide\'s seat could not be boarded by a tap"; pinball measurements. Reach: Pixel GameTest 2026-09-30 (quirk_reach, output/gametest-quirks-0930/run1/cmgt.log QREACH): a 0.5 box moved 0.25 at a time, hit while eye-to-centre <= 7.25 and missed from 7.36 (Creative), hit <= 3.25 and missed from 3.26 (Survival), at floor and at eye height; `attackEntity` hit at 20 blocks (documented reach-free)', appliesTo: ['input'], simulated: 'partial', values: { reachBlocks: 5, serverReachCreativeBlocks: 7, serverReachSurvivalBlocks: 3 }, gap: 'the reach measured is the SERVER\'s for a simulated player; how far a phone\'s touch pick reaches before the server sees it is not measurable by GameTest, so the pick stays at 5 (inside the server\'s Creative 7); a Survival child (server 3) is not modelled' },
  { id: 'hold-is-interact', rule: 'A press held ~0.5 s fires `playerInteractWithEntity`; a vanilla rideable mounts on it. The interact reaches ~5 blocks in both Creative and Survival.', evidence: 'add-on guide "The slide\'s seat could not be boarded by a tap" (2026-09-29); CLAUDE.md "A touch tap is entityHitEntity". Reach: Pixel GameTest 2026-09-30 (quirk_reach, output/gametest-quirks-0930/run1/cmgt.log QREACH): `SimulatedPlayer.interact()` on the moulded seat mounted it while eye-to-centre <= 5.25 (eye height) / 5.16 (on the floor) and not from 5.40, in both modes', appliesTo: ['input', 'entity'], simulated: 'partial', values: { holdTicks: 10, reachBlocks: 5 }, gap: 'the hold time (~0.5 s) is from the pinball rounds; the 5-block reach is the server\'s for a simulated player (a phone\'s own pick is not measurable by GameTest)' },
  { id: 'no-selection-box-passes-taps', rule: 'A block whose `minecraft:selection_box` is false is passed by the tap ray (a tap reaches an entity inside a collider); `playerInteractWithBlock` never fires for it.', evidence: 'add-on guide "The slide\'s seat could not be boarded by a tap"; docs/bedrock-interactivity.md "Taps through walls"', appliesTo: ['input', 'world'], simulated: 'modelled' },
  { id: 'unloaded-block-undefined', rule: '`Dimension.getBlock` returns undefined outside the loaded/simulated area; it is not air.', evidence: 'CLAUDE.md "An unloaded block is not air" (Pixel 2026-09-25: an empty car fell 250 blocks)', appliesTo: ['world', 'script-host'], simulated: 'modelled' },
  { id: 'unloaded-entity-invisible', rule: '`world.getEntity` and `getEntities` see only entities in loaded chunks; an entity outside them does not tick.', evidence: 'bedrock-placement-pack.ts undo ("world.getEntity sees only loaded ones"); CLAUDE.md GameTest "Entity being invalid" ~100 blocks out', appliesTo: ['entity', 'script-host'], simulated: 'modelled' },
  { id: 'group-removal-strips-base', rule: 'Removing a component group removes its components from the entity even where the base components declare them.', evidence: 'CLAUDE.md (a size_100 that only removed groups left vehicles unrideable, 2026-09-26)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'float-property-int-literal', rule: 'A `float` actor property written with an integer literal (`"default": 0`) is rejected and the entity loses its WHOLE property component: `getProperty` returns undefined and `setProperty` throws.', evidence: 'CLAUDE.md "Bedrock rejects a float actor property written as an integer literal" (2026-09-21, content log)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'entity-id-leading-digit', rule: 'An entity identifier whose name begins with a digit is refused; the type never exists and every spawn fails.', evidence: 'CLAUDE.md (`craftmatic:10303_cart`, 2026-09-21)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'pushable-dropped', rule: 'Format 1.26.30 dropped `minecraft:pushable`: a definition that declares it fails to parse and the type does not exist.', evidence: 'CLAUDE.md (pinball shipped twice with nothing moving, 2026-09-24)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'form-deletes-percent', rule: 'The form renderer deletes a bare `%` from a form\'s text.', evidence: 'CLAUDE.md "Bedrock\'s form renderer deletes a bare %" (Pixel 2026-09-21)', appliesTo: ['ui'], simulated: 'modelled' },
  { id: 'hover-controller-speed', rule: 'The hover mount controller (`free_camera_controlled` + `movement.hover`) cruises at v ≈ 120·flying_speed + 2.3 blocks/s toward the look direction.', evidence: 'Pixel 2026-09-29: 0.09 → 13.1 blocks/s (round 29d), 0.3 → 38.3 blocks/s (`output/nimbus-pixel-0929/`); Pixel 2026-09-30f: 0.0725 → 10.55 blocks/s (48 samples 10.21-10.61, `output/device-round-2026-09-30f/pixel/_notes.txt`), 0.45 under the line: the fit is good to ~5 % over 0.07-0.3; physics spec §4.6', appliesTo: ['physics'], simulated: 'modelled', values: { blocksPerSecondPerFlyingSpeed: 120, offsetBlocksPerSecond: 2.3 } },
  { id: 'hover-climb-descend', rule: 'On a hover mount Jump climbs ~20-22 blocks/s; the descend group (vertical_movement_action -0.5) sinks ~4 blocks/s.', evidence: 'Saga 2026-09-29 (`output/nimbus-saga-0929/`, climb ~20), Pixel 2026-09-29 (dive ~4 down, climb ~22)', appliesTo: ['physics'], simulated: 'modelled', values: { climbBlocksPerSecond: 21, descendBlocksPerSecond: 4 } },
  { id: 'hover-descend-needs-jump', rule: 'The descend group acts only while Jump is held; look pitch alone does not descend a hover mount.', evidence: 'Saga 26.52 (physics spec §4.6, `FLYER.DIVE_PITCH_DEG`); fix `a754a7de`', appliesTo: ['physics', 'input'], simulated: 'modelled' },
  { id: 'camera-pitch-limit', rule: '`setCamera` takes a pitch within ±90 only; outside it throws.', evidence: 'CLAUDE.md "A Bedrock camera cannot roll per tick" (Pixel 26.51)', appliesTo: ['camera'], simulated: 'modelled' },
  { id: 'camera-roll-animation-only', rule: 'Roll exists only as a `playAnimation` keyframe; keyframes >0.05 s apart, a re-issued animation is never drawn, Euler keys interpolate linearly.', evidence: 'CLAUDE.md camera gotcha (2026-09-24..29, `camprobe`)', appliesTo: ['camera', 'render'], simulated: 'device-only' },
  { id: 'client-entity-lag', rule: 'The client draws entities ~3.5 ticks behind the server.', evidence: 'CLAUDE.md (marker-measured, `camprobe`, `animLag` 3.5)', appliesTo: ['render', 'camera'], simulated: 'device-only', values: { ticks: 3.5 } },
  { id: 'rider-yaw-lag', rule: 'A rider\'s reported yaw is the client\'s and trails its vehicle ~6 ticks.', evidence: 'CLAUDE.md camera gotcha', appliesTo: ['camera', 'input'], simulated: 'device-only', values: { ticks: 6 } },
  // The two cull rows read their numbers FROM the engine constants the LOD plan
  // and the snapshot's `entityRenderCullBlocks` apply, so the registry and the
  // code cannot drift: re-measuring the ceiling changes bedrock-lod-hull.ts.
  { id: 'actor-draw-ceiling', rule: 'On 26.51/26.52 no actor draws past ~70-72 blocks, whatever its collision box.', evidence: 'round 2026-09-26a, `output/device-round-2026-09-26a/pixel/cull_*.png` (CLAUDE.md); applied through `entityRenderCullBlocks` (bedrock-lod-hull.ts) by the snapshot', appliesTo: ['render'], simulated: 'modelled', values: { blocks: ACTOR_DRAW_CEILING_BLOCKS } },
  { id: 'cull-by-collision-box', rule: 'Below the ceiling an actor culls at ≈ 64 × max(1, collision box diagonal) blocks.', evidence: 'CLAUDE.md (2026-09-22); applied through `entityRenderCullBlocks` (bedrock-lod-hull.ts) by the snapshot', appliesTo: ['render'], simulated: 'modelled', values: { blocksPerDiagonal: RENDER_CULL_BLOCKS_PER_UNIT } },
  { id: 'box-uv-sub-unit-faces', rule: 'Bedrock floors a box-UV cube\'s DECLARED size and does not draw a side face whose height floors to 0.', evidence: 'Pixel probe 2026-09-29 (CLAUDE.md; `UvFloorModel`, `_figure_compile_holes.ts`)', appliesTo: ['render'], simulated: 'device-only', gap: 'the snapshot rasteriser draws every face' },
  { id: 'coplanar-hatching', rule: 'Two colours on one plane hatch (z-fight) on the device.', evidence: 'CLAUDE.md "Two colours on one plane hatch on the device" (`_render_fault_audit.ts`)', appliesTo: ['render'], simulated: 'device-only' },
  { id: 'slow-falling-gravity', rule: 'Slow falling lowers gravity to 0.01 blocks/tick² while falling and prevents fall damage.', evidence: 'Pixel 2026-09-29 float-down 89 blocks in 11 s, unharmed (`output/nimbus-pixel-0929/`)', appliesTo: ['physics'], simulated: 'modelled', values: { gravity: 0.01 } },
  { id: 'fill-volume-limit', rule: '`fillBlocks` takes a BlockVolume INSTANCE (a plain {from,to} is rejected) and at most 32768 blocks per call.', evidence: 'test/_placement-host.ts (the stale-collider bug), @minecraft/server 2.x docs', appliesTo: ['script-host', 'world'], simulated: 'modelled', values: { maxBlocks: 32768 } },
  { id: 'structure-load-keeps-states', rule: '`structure load` turned by a rotation moves each block but keeps its states (a custom block\'s shape in its id/state is NOT turned).', evidence: 'bedrock-placement-pack.ts (the clearance-form re-set after a turned load, 2026-09-25)', appliesTo: ['commands', 'world'], simulated: 'partial', gap: 'vanilla direction states (stairs, doors) are not turned either; the game turns those' },
  { id: 'no-dismount-event', rule: '@minecraft/server 2.9 has no dismount event: a runtime polls who is aboard.', evidence: 'physics spec §4.6 (flyer.js polls every 10 ticks)', appliesTo: ['script-host'], simulated: 'modelled' },
  { id: 'dynamic-property-string-limit', rule: 'A string dynamic property holds at most 32,767 characters; a longer one throws.', evidence: 'bedrock-placement-pack.ts undo record chunks (2026-09-25)', appliesTo: ['script-host'], simulated: 'modelled', values: { maxChars: 32767 } },
  { id: 'simulation-distance', rule: 'Chunks within the simulation distance of a player (and inside ticking areas) are loaded; outside them blocks read undefined and entities freeze.', evidence: 'CLAUDE.md "An unloaded block is not air" (a GameTest vehicle ~100 blocks out stopped being readable)', appliesTo: ['world'], simulated: 'partial', values: { chunks: 6 }, gap: 'the phones\' exact simulation distance is not measured; 6 chunks (96 blocks) matches the ~100-block GameTest loss' },
  { id: 'native-mount-bursts', rule: 'A client-driven mount reports ~0 velocity and its server position moves in bursts (CMVT cadence ~4 ticks).', evidence: 'physics spec §4.6 (`DRIVER_SPEED_WINDOW_TICKS`; Saga 2-tick deltas 0/24.9/60.2/99.0 mph)', appliesTo: ['physics'], simulated: 'partial', values: { burstTicks: 4 }, gap: 'the engine moves the mount every tick (smooth); the driver HUD\'s burst averaging is not exercised' },
  { id: 'fly-sound-block-normal', rule: 'Any entity moved through the air (a hover mount, a ride car carried along its path, a figure) raises a `fly` sound event the client resolves through the block-MATERIAL table: with no sound it logs `[Sound][verbose] No sound found for block type \'normal\' and event type \'fly\'`. Only the RP `sounds.json` `interactive_sounds.block_sounds.normal.events.fly` silences it; per-entity entries (`entity_sounds`, `interactive_sounds.entity_sounds`, even naming a real silent sound) do nothing. Whether a pack\'s `normal` replaces or merges into vanilla\'s is unknown, so the pack carries vanilla\'s events verbatim (`flySoundEvents`).', evidence: 'Saga 26.52 A/B 2026-09-29/30 (`output/fly-sound-ab-0929/saga/_notes.txt`, README.md): baseline 355 lines in a 60 s flight and 45-72/min by the orbit alone; variant A (block_sounds.normal + fly "") 0 in every window (orbit idle 3 min, perch, 60 s flight, 3 min mounted idle); variant B (silent sound per entity) 404 in 60 s of flight; the per-entity interactive entry changed nothing on the Pixel (round 29d) or the Saga', appliesTo: ['sound'], simulated: 'device-only', values: { baselineFlyLinesPerFlightMinute: 355, variantAFlyLines: 0, variantBFlyLinesPerFlightMinute: 404 } },
  { id: 'rider-seat-order', rule: '`Rideable.addRider` cannot choose a seat: the new rider takes the first free seat in the definition\'s `seats` order (seat 0, the controlling seat, first).', evidence: 'ASSUMED 2026-09-30 (the hop, web/src/engine/bedrock-ride-hop.ts): Microsoft Learn\'s `Seat` class documents min/max rider counts per seat and nothing about which seat a script-added rider takes; not measured. The hop chooses the front-most free seat across ENTITIES (a train\'s cars) and relies on the compiler listing the driver\'s seat first. A GameTest that adds two players to a two-seat car and reads each rider\'s position would settle it.', appliesTo: ['entity'], simulated: 'partial', gap: 'Pixel round 30f measured only the EMPTY-car case: the rider took seat 0 (feet +1.16 z from the car = seat 0). Which seat a rider takes when seat 0 is held needs a second player (a pig was refused as a rider). The simulator seats in the lowest free index; whether the device compacts riders when one leaves is not modelled' },
  { id: 'add-rider-after-eject', rule: 'A player ejected from one mount (`ejectRider`) can be added to another with `addRider` in the same tick.', evidence: 'Pixel 26.51 round 2026-09-30f (`output/device-round-2026-09-30f/pixel/_notes.txt`): three hops (a cloud onto 10261\'s train on the lift hill, a moving train into a hovering cloud, 10797\'s slide into its parked car) each boarded in the same tick; none fell back to the mount left. The hop still puts a refused rider back on the mount it left.', appliesTo: ['entity', 'script-host'], simulated: 'modelled' },
  { id: 'dynamic-properties-per-pack', rule: 'An entity\'s dynamic properties are visible only to the behaviour pack that wrote them; tags (`addTag`) are shared by every pack\'s scripts.', evidence: 'Script API documentation (jaylydev.github.io/scriptapi-docs "Dynamic Properties": "behavior packs cannot access other behavior packs\' dynamic properties", keyed by the pack\'s header UUID; Microsoft Learn states the storage limits per content pack); applied by the hop (bedrock-ride-hop.ts: a coaster car of one pack tells a plane of another its train and rank by TAGS) 2026-09-30. Not measured on the phones.', appliesTo: ['script-host'], simulated: 'partial', gap: 'the simulator keeps one dynamic-property map per entity, shared by every pack: a script reading another pack\'s property works here and not on the device' },
  { id: 'rider-free-look', rule: 'On a SCRIPTED vehicle\'s seat with `lock_rider_rotation` 181, a touch drag turns the rider\'s look (yaw and pitch, reported by `getRotation` every tick) under the script\'s free camera; the engine does not turn the zero-speed vehicle toward the rider\'s look (the script\'s teleport owns its yaw); a turning vehicle carries its rider\'s yaw round ~6 ticks late (as a coaster car does, `rider-yaw-lag`); `setRotation` on the seated rider applies its yaw, not its pitch.', evidence: 'ASSUMED 2026-09-30 (free look, web/src/engine/vehicle-free-look.ts): Microsoft Learn documents `lock_rider_rotation` as the angle a rider may rotate (181 the default, no limit); the coaster\'s 181 seats report a rider yaw trailing the car ~6 ticks (CLAUDE.md camera gotcha); pinball (Pixel 2026-09-25, a lock-0 seat) measured a drag reporting the pitch every tick and `setRotation` applying yaw only. None of it measured on a scripted vehicle. Device probe: ride 42172 and 7140 with `/scriptevent craftmatic:vehicle_telemetry fast`, drag the screen at rest and while driving: CMCAM `riderYaw` must follow the finger, `yawOff` ease back to 0 within ~2 s of letting go while moving, and CMVT `yaw` must NOT move with the drag at rest (a vehicle the engine turns toward the look would fight the script: jitter). A GameTest cannot drag (a simulated player\'s look is not touch input).', appliesTo: ['entity', 'camera', 'input'], simulated: 'partial', gap: 'the simulator neither carries a rider\'s yaw with its vehicle nor turns a zero-speed mount toward its rider; `freeLookStep` reads a drag the same under both (test/vehicle-free-look.test.ts covers the carried case on the pure model)' },
  { id: 'aabb-is-collision-box', rule: '`Entity.getAABB()` is the entity\'s `minecraft:collision_box` about its feet (width as the x and z diameter, times its scale), centre and half extents.', evidence: 'ASSUMED 2026-09-30 (the hop reads a target\'s box with it): @minecraft/server 2.9 declares `getAABB`; its extent for a rotated, scaled or seat-carrying entity is not measured.', appliesTo: ['entity', 'script-host'], simulated: 'partial', gap: 'the simulator returns the unscaled collision box; a device value past it would only widen the hop\'s reach' },
  { id: 'dismount-free-spot', rule: 'A PLAYER taken off a seat (`Rideable.ejectRider`, `/ride @s stop_riding`) is set on the floor of the first free spot one block from the SEAT ENTITY\'s point, in world order (0,-1), (0,+1), (+1,-1), (+1,+1), (-1,+1) - the diagonals come before the plain x sides - even in the open. A spot is taken when its floor lies within about +0.5 / -1 of the seat entity\'s point and the body fits there; with none, the player is put at the seat entity\'s point 0.2 up and falls. The seat\'s yaw and the rider\'s facing do not change the order; a rider sitting inside a block (a seat sunk 0.1-0.3 into the floor, a block over the seat) is set down the same way.', evidence: 'Pixel GameTest 2026-09-30 (`scripts/_gametest_quirks.ts` quirk_dismount / quirk_dismount2, the moulded seat `seatBehavior`; the rider\'s feet read 0.4 under the seat point): run 2 (output/gametest-quirks-0930/run2/cmgt.log QDM, 14 layouts x eject / stop_riding, identical): open, one or both x sides walled, +z walled, a block overhead, sunk 0.1 / 0.3 -> (0, floor, -1); -z walled -> (0, floor, +1); ring of 4 -> (+1, floor, -1); ring of 8 -> (0, seat + 0.2, 0), then the floor. Run 3 (output/gametest-quirks-0930/run3/cmgt.log): +-z walled (x sides open or one walled) -> (+1, -1); ring of 4 + (+1,-1) -> (+1, +1); + (-1,-1) too -> (+1, +1); + (+1,+1) too -> (-1, +1); a seat off its block centre by (0.3, 0.2) or (-0.3, -0.3) -> (0, -1) from the SEAT; a slab at (0,-1) -> onto the slab (+0.5); a full block or a 1-deep pit at (0,-1) -> (0, +1). Seat yaw 90 / 180 / 270 and a rider facing -z did not change it. `isSneaking = true` on a simulated player does NOT dismount', appliesTo: ['entity', 'physics'], simulated: 'partial', gap: 'the places of (-1,-1), (+1,0) and (-1,0) in the order and the exact floor window (+0.2 taken, +0.7 refused above; -0.3 taken, -1.3 refused below) were not reached (TODO in physics/systems.ts); a real SNEAK is client input a simulated player cannot send, so a sneak is assumed to set down like stop_riding; a MOB rider\'s spot is not measured and the engine leaves it where it sat' },
  { id: 'teleport-into-floor', rule: 'A PLAYER teleported with its box inside a block\'s collision is never lifted onto the top: it falls THROUGH what it overlaps (the sweep ignores a solid the box already overlaps) to the next surface under its feet, the first gravity step 3 ticks after the teleport; feet 0.1-0.5 into a full block (stone or `craftmatic:collider` hi 16) land on the floor under that block, into a bottom slab or a half-height collider on the floor under the slab. While it overlaps, its velocity on the one horizontal axis whose move frees it soonest is SET to 0.1 blocks/tick toward the free side (then ordinary friction: it drifts 0.12-0.34 past free); a player with no free side within reach (the middle of a 3 x 3 pad, 1.8 from free) is not pushed. No damage. The script `teleport` and `/tp` behave the same. A player-sized MOB (no AI) teleported 0.34 into a block or slab is the opposite: lifted onto its top by tick 2.', evidence: 'Pixel GameTest 2026-09-30 (`scripts/_gametest_quirks.ts` quirk_tp, simulated players in Survival, output/gametest-quirks-0930/run1/cmgt.log QTP rows 0-37): centred on a 3 x 3 pad, every depth ends at feet = block bottom (stone/collider: -0.9/-0.8/-0.66/-0.5 from the target; slab/half collider: -0.4/-0.3/-0.16/0), health 20 -> 20; on the edge of a single block with air on +x: pushed +x 0.1/tick for 3 ticks then drift, 0.42-0.64 in all, falling meanwhile; beside a wall form, pushed toward its nearer free side by 0.22-0.62 and never up (re-run after the x-mirror fix, output/gametest-quirks-0930/run3/cmgt.log: +0.22/+0.32/+0.52/+0.62 for 0.1/0.2/0.34/0.5 of overlap); the 0.6 x 1.8 dummy mob at 0.34: +0.34 (onto the top) at tick 2. Agrees with the 29d Pixel read-out (`output/device-round-2026-09-29d/pixel/_notes.txt`: a lift set-down 0.34 inside a slab read one block LOWER and one over in z).', appliesTo: ['physics'], simulated: 'partial', values: { pushBlocksPerTick: 0.1, maxPushBlocks: 1, firstFallTick: 3 }, gap: 'the push bound is 1 block (free at 0.6 was pushed, 1.8 was not; the device\'s exact bound lies between); the 2-tick pause before the fall and the mob lift are not modelled; the probe is a SIMULATED player - a phone player\'s client-side movement was not measured separately, though the 29d read-out agrees' },
  { id: 'block-collision-x-mirrored', rule: 'A custom block\'s `minecraft:collision_box` is MIRRORED in x: a box declared at origin x o, size s stands on world x [8 - o - s, 8 - o] pixels of its block (origin -8 is the block\'s HIGH-x side); y and z are as written. A pack must declare a box meant for world x [x0, x1] at origin x 8 - x1.', evidence: 'Pixel GameTest 2026-09-30 (quirk_bands, output/gametest-quirks-0930/run2/cmgt.log QBANDS): a 0.2-wide pin dropped over each quarter of a pillar landed on `collider_w2` (declared origin -8, size 8) only at x 0.75, on `collider_w5` (declared origin 0) only at x 0.25, on `collider_w9` (declared z origin -8, size 8) only at z 0.25; stone caught all four. Run 1 (output/gametest-quirks-0930/run1/cmgt.log QTP 32-35): players beside `collider_w2` were pushed as a band on x 0.5-1 pushes them. Fixed in `collisionBox` (bedrock-building-shell.ts); packs built before it carry every x-banded clearance form on the wrong half of its block', appliesTo: ['world'], simulated: 'modelled' },
];

const BY_ID = new Map<QuirkId, Quirk>(QUIRKS.map(q => [q.id, q]));

/** A quirk by id (throws for an unknown id: a typo must not silently read no fact). */
export function quirk(id: QuirkId): Quirk {
  const q = BY_ID.get(id);
  if (!q) throw new Error(`unknown quirk ${id}`);
  return q;
}

/** A quirk's measured number. */
export function quirkValue(id: QuirkId, key: string): number {
  const v = quirk(id).values?.[key];
  if (v === undefined) throw new Error(`quirk ${id} has no value ${key}`);
  return v;
}

/** Every registered quirk, in registry order. */
export function allQuirks(): readonly Quirk[] { return QUIRKS; }

/** The quirks an area of the engine cannot simulate: what a scenario touching it must report as device-only. */
export function deviceOnly(area: QuirkArea): Quirk[] { return QUIRKS.filter(q => q.simulated === 'device-only' && q.appliesTo.includes(area)); }
