/**
 * Device-measured facts about Bedrock that no documentation states, each with
 * the evidence it was measured by. The simulator's modules CONSULT this
 * registry (they read their numbers from it and name the quirk they apply),
 * so a fact is written once, next to its proof, and a device round that
 * re-measures it changes one row.
 *
 * `simulated` says what the engine does with a fact:
 *   - `modelled`: the engine behaves this way;
 *   - `partial`: modelled in the common case, with a stated gap;
 *   - `device-only`: the engine cannot show it (rendering, client timing,
 *     touch hardware). A scenario step that depends on it is reported
 *     `device-only`, never passed.
 *
 * Adding a fact: a row here with its evidence (a path under `output/`, a
 * commit, a doc section and the date), then the module that applies it reads
 * `quirk(<id>)`. See docs/sim-engine.md "The quirk registry".
 */

import { ACTOR_DRAW_CEILING_BLOCKS, RENDER_CULL_BLOCKS_PER_UNIT } from '../../engine/bedrock-lod-hull.js';

/** The engine module a quirk bears on. */
export type QuirkArea = 'world' | 'entity' | 'physics' | 'script-host' | 'input' | 'render' | 'camera' | 'ui' | 'commands' | 'sound';

export interface Quirk {
  id: QuirkId;
  /** The fact, as a rule the engine can apply. */
  rule: string;
  /** Where it was measured: evidence path, commit or doc section, and the date. */
  evidence: string;
  appliesTo: readonly QuirkArea[];
  simulated: 'modelled' | 'partial' | 'device-only';
  /** The measured numbers the engine uses (units in the key's name or the rule). */
  values?: Readonly<Record<string, number>>;
  /** For `partial`: what is not modelled. */
  gap?: string;
}

export type QuirkId =
  | 'add-rider-spawn-tick' | 'tp-dismounts' | 'rider-eye-above-seat' | 'seat-z-is-nose' | 'seat-scales-with-entity' | 'sneak-dismounts'
  | 'tap-is-hit' | 'hold-is-interact' | 'no-selection-box-passes-taps' | 'unloaded-block-undefined'
  | 'unloaded-entity-invisible' | 'group-removal-strips-base' | 'float-property-int-literal'
  | 'entity-id-leading-digit' | 'pushable-dropped' | 'form-deletes-percent' | 'hover-controller-speed'
  | 'hover-climb-descend' | 'hover-descend-needs-jump' | 'camera-pitch-limit' | 'camera-roll-animation-only'
  | 'client-entity-lag' | 'rider-yaw-lag' | 'actor-draw-ceiling' | 'cull-by-collision-box' | 'box-uv-sub-unit-faces'
  | 'coplanar-hatching' | 'slow-falling-gravity' | 'fill-volume-limit' | 'structure-load-keeps-states'
  | 'no-dismount-event' | 'dynamic-property-string-limit' | 'simulation-distance' | 'native-mount-bursts' | 'teleport-into-floor' | 'dismount-free-spot'
  | 'fly-sound-block-normal' | 'rider-seat-order' | 'add-rider-after-eject' | 'dynamic-properties-per-pack' | 'aabb-is-collision-box'
  | 'block-collision-x-mirrored' | 'rider-free-look' | 'native-mount-locked-look' | 'hop-invisibility-handoff'
  | 'control-scheme-drag-to-camera' | 'mount-snaps-rider-yaw' | 'cockpit-draw-lag' | 'auto-jump' | 'hover-turn-chase'
  | 'seat-camera-radius-unobserved';

const QUIRKS: readonly Quirk[] = [
  { id: 'add-rider-spawn-tick', rule: '`Rideable.addRider` can refuse a rider in the tick either entity spawned; a retry a couple of ticks later succeeds.', evidence: 'Pixel 2026-09-29: the orbit companion refused at placement and was seated seconds later by rides.js (TASKS-BEDROCK-ADDON.md "Nimbus follow-ups", `SEAT_RETRIES` in bedrock-placement-pack.ts)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'tp-dismounts', rule: 'Teleporting a riding player (`/tp @s ~ ~ ~`, and the script `teleport` of the rider itself) dismounts it; teleporting the RIDDEN entity carries its riders.', evidence: 'Saga 2026-09-29 (TASKS-BEDROCK-ADDON.md "Phones": "/tp @s ~ ~ ~ DISMOUNTS"); rides and coasters carry riders by teleporting the seat (physics spec §4.7)', appliesTo: ['entity', 'commands'], simulated: 'partial', gap: 'the script-API teleport of the rider itself is assumed to behave like /tp (not measured separately)' },
  { id: 'rider-eye-above-seat', rule: 'A riding player\'s eye is 1.12 blocks above its seat position.', evidence: 'CLAUDE.md "A minecraft:rideable seat\'s +Z is the entity\'s NOSE" (measured 2026-09-26); cockpit-seat.ts', appliesTo: ['entity', 'physics'], simulated: 'modelled', values: { eyeAboveSeatBlocks: 1.12 } },
  { id: 'seat-z-is-nose', rule: 'A `minecraft:rideable` seat position is in the entity frame with +Z the nose, turned by the entity yaw.', evidence: 'CLAUDE.md (every compiled seat was mirrored until 2026-09-26)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'seat-scales-with-entity', rule: 'A `minecraft:rideable` seat position is MULTIPLIED by the entity\'s `minecraft:scale` (the seat is declared in the unscaled frame); the rider\'s eye offset over the seat (1.12) is not scaled. A pack that writes a size group\'s seat already scaled puts the rider at scale x scale x the 100 % offset.', evidence: 'Saga round 30k, 2026-10-07 (`output/device-round-2026-10-07k/saga/notes.md` item 8, `r27-strip.jpg`, `r28-mil200-side-zoom.jpg`, `r29-grid.jpg`, `s105-strip.jpg`): 76286 (packs-78e06246) at 100 %, seat (0, 4.58, 3.6): rider eye (0, 5.7, 3.6) = seat + 1.12, in the front cabin; at 200 % by `/summon` + `craftmatic:size_200` and by the wand, seat declared (0, 10.28, 7.2) under `minecraft:scale` 2: eye (0, 21.68, 14.4) = 2 x seat + 1.12, feet (0, 20.16, 14.4) = 2 x seat - 0.4, the player drawn ~6 blocks over the hull and 14 ahead of it. Microsoft\'s `minecraft:scale` page says only "visual size multiplier"; fix: `rideableAtSize` (bedrock-placement-pack.ts) declares every seat divided by its group\'s scale', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'sneak-dismounts', rule: 'Sneak (the touch sneak button) dismounts a rider from a vanilla rideable; there is no dismount event in @minecraft/server 2.9.', evidence: 'TASKS-BEDROCK-ADDON.md Nimbus ("sneak gets off"; a sneak at ALT 169 dropped the Saga rider 229 blocks), physics spec §4.6', appliesTo: ['entity', 'input'], simulated: 'modelled' },
  { id: 'tap-is-hit', rule: 'A touch TAP on an entity fires `entityHitEntity` (the player hits it); it does not fire the interact. The server accepts a hit (`SimulatedPlayer.attack()`, a ray from the head) out to ~7 blocks in Creative and ~3 in Survival; the simulator picks at 5, inside the Creative limit the QA worlds play in.', evidence: 'Pixel round 29c (10788 slide seat: three taps boarded nobody, `/ride` worked); add-on guide "The slide\'s seat could not be boarded by a tap"; pinball measurements. Reach: Pixel GameTest 2026-09-30 (quirk_reach, output/gametest-quirks-0930/run1/cmgt.log QREACH): a 0.5 box moved 0.25 at a time, hit while eye-to-centre <= 7.25 and missed from 7.36 (Creative), hit <= 3.25 and missed from 3.26 (Survival), at floor and at eye height; `attackEntity` hit at 20 blocks (documented reach-free)', appliesTo: ['input'], simulated: 'partial', values: { reachBlocks: 5, serverReachCreativeBlocks: 7, serverReachSurvivalBlocks: 3 }, gap: 'the reach measured is the SERVER\'s for a simulated player; how far a phone\'s touch pick reaches before the server sees it is not measurable by GameTest, so the pick stays at 5 (inside the server\'s Creative 7); a Survival child (server 3) is not modelled' },
  { id: 'hold-is-interact', rule: 'A press held ~0.5 s fires `playerInteractWithEntity`; a vanilla rideable mounts on it. The interact reaches ~5 blocks in both Creative and Survival.', evidence: 'add-on guide "The slide\'s seat could not be boarded by a tap" (2026-09-29); CLAUDE.md "A touch tap is entityHitEntity". Reach: Pixel GameTest 2026-09-30 (quirk_reach, output/gametest-quirks-0930/run1/cmgt.log QREACH): `SimulatedPlayer.interact()` on the moulded seat mounted it while eye-to-centre <= 5.25 (eye height) / 5.16 (on the floor) and not from 5.40, in both modes', appliesTo: ['input', 'entity'], simulated: 'partial', values: { holdTicks: 10, reachBlocks: 5 }, gap: 'the hold time (~0.5 s) is from the pinball rounds; the 5-block reach is the server\'s for a simulated player (a phone\'s own pick is not measurable by GameTest)' },
  { id: 'no-selection-box-passes-taps', rule: 'A block whose `minecraft:selection_box` is false is passed by the tap ray (a tap reaches an entity inside a collider); `playerInteractWithBlock` never fires for it.', evidence: 'add-on guide "The slide\'s seat could not be boarded by a tap"; docs/bedrock-interactivity.md "Taps through walls"', appliesTo: ['input', 'world'], simulated: 'modelled' },
  { id: 'unloaded-block-undefined', rule: '`Dimension.getBlock` returns undefined outside the loaded/simulated area; it is not air.', evidence: 'CLAUDE.md "An unloaded block is not air" (Pixel 2026-09-25: an empty car fell 250 blocks)', appliesTo: ['world', 'script-host'], simulated: 'modelled' },
  { id: 'unloaded-entity-invisible', rule: '`world.getEntity` and `getEntities` see only entities in loaded chunks; an entity outside them does not tick.', evidence: 'bedrock-placement-pack.ts undo ("world.getEntity sees only loaded ones"); CLAUDE.md GameTest "Entity being invalid" ~100 blocks out', appliesTo: ['entity', 'script-host'], simulated: 'modelled' },
  { id: 'group-removal-strips-base', rule: 'Removing a component group removes its components from the entity even where the base components declare them.', evidence: 'CLAUDE.md (a size_100 that only removed groups left vehicles unrideable, 2026-09-26)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'float-property-int-literal', rule: 'A `float` actor property written with an integer literal (`"default": 0`) is rejected and the entity loses its WHOLE property component: `getProperty` returns undefined and `setProperty` throws.', evidence: 'CLAUDE.md "Bedrock rejects a float actor property written as an integer literal" (2026-09-21, content log)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'entity-id-leading-digit', rule: 'An entity identifier whose name begins with a digit is refused; the type never exists and every spawn fails.', evidence: 'CLAUDE.md (`craftmatic:10303_cart`, 2026-09-21)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'pushable-dropped', rule: 'Format 1.26.30 dropped `minecraft:pushable`: a definition that declares it fails to parse and the type does not exist.', evidence: 'CLAUDE.md (pinball shipped twice with nothing moving, 2026-09-24)', appliesTo: ['entity'], simulated: 'modelled' },
  { id: 'form-deletes-percent', rule: 'The form renderer deletes a bare `%` from a form\'s text.', evidence: 'CLAUDE.md "Bedrock\'s form renderer deletes a bare %" (Pixel 2026-09-21)', appliesTo: ['ui'], simulated: 'modelled' },
  { id: 'hover-controller-speed', rule: 'The hover mount controller (`free_camera_controlled` + `movement.hover`) cruises at v ≈ 120·flying_speed + 2.3 blocks/s toward the look direction.', evidence: 'Pixel 2026-09-29: 0.09 → 13.1 blocks/s (round 29d), 0.3 → 38.3 blocks/s (`output/nimbus-pixel-0929/`); Pixel 2026-09-30f: 0.0725 → 10.55 blocks/s (48 samples 10.21-10.61, `output/device-round-2026-09-30f/pixel/_notes.txt`), 0.45 under the line: the fit is good to ~5 % over 0.07-0.3; physics spec §4.6', appliesTo: ['physics'], simulated: 'modelled', values: { blocksPerSecondPerFlyingSpeed: 120, offsetBlocksPerSecond: 2.3 } },
  { id: 'hover-climb-descend', rule: 'On a hover mount Jump climbs ~20-22 blocks/s; the descend group (vertical_movement_action -0.5) sinks ~4 blocks/s.', evidence: 'Saga 2026-09-29 (`output/nimbus-saga-0929/`, climb ~20), Pixel 2026-09-29 (dive ~4 down, climb ~22)', appliesTo: ['physics'], simulated: 'modelled', values: { climbBlocksPerSecond: 21, descendBlocksPerSecond: 4 } },
  { id: 'hover-descend-needs-jump', rule: 'The descend group acts only while Jump is held; look pitch alone does not descend a hover mount.', evidence: 'Saga 26.52 (physics spec §4.6, `FLYER.DIVE_PITCH_DEG`); fix `a754a7de`', appliesTo: ['physics', 'input'], simulated: 'modelled' },
  { id: 'camera-pitch-limit', rule: '`setCamera` takes a pitch within ±90 only; outside it throws.', evidence: 'CLAUDE.md "A Bedrock camera cannot roll per tick" (Pixel 26.51)', appliesTo: ['camera'], simulated: 'modelled' },
  { id: 'camera-roll-animation-only', rule: 'Roll exists only as a `playAnimation` keyframe; keyframes >0.05 s apart, a re-issued animation is never drawn, Euler keys interpolate linearly.', evidence: 'CLAUDE.md camera gotcha (2026-09-24..29, `camprobe`)', appliesTo: ['camera', 'render'], simulated: 'device-only' },
  { id: 'client-entity-lag', rule: 'The client draws entities ~3.5 ticks behind the server.', evidence: 'CLAUDE.md (marker-measured, `camprobe`, `animLag` 3.5)', appliesTo: ['render', 'camera'], simulated: 'device-only', values: { ticks: 3.5 } },
  { id: 'rider-yaw-lag', rule: 'The device turns a lock-181 seat\'s PLAYER rider round with its vehicle - the CARRY: the rider\'s reported yaw (the client\'s) follows every turn of the vehicle 1:1, ~6 ticks late, whoever turned it (the hover controller\'s chase, a script teleport); a script `setRotation` of the vehicle is ASSUMED to carry the same way. A drag therefore changes the look\'s OFFSET from the vehicle and nothing the vehicle does ever closes it.', evidence: 'CLAUDE.md camera gotcha (the coaster, ~6 ticks); Saga 26.52 round 30l (`output/device-round-2026-10-07l/saga/ContentLog-30l-live.txt`): the X-wing turned on the spot by its stick (script teleport, CMCAM 22:40:15-22, 4 degrees/tick) with `riderYaw` trailing `vehicleYaw` by 33 degrees (~8 ticks) through four full turns and meeting it at the end (126.5 / 127); the Nimbus (CMVT 22:01:28-37, native chase, 6.5 degrees/tick) with `riderYaw` 45 AHEAD of the cloud through 3 full turns - the finger\'s 84-degree swipe less 6 ticks x 6.5 of carry; a swipe the other way closed the offset and the cloud stopped (22:01:55-57). Modelled 2026-10-08: `physics/systems.ts` riders system turns a player on a non-zero-lock seat by the vehicle\'s yaw change of `ticks` ago.', appliesTo: ['camera', 'input', 'entity'], simulated: 'partial', values: { ticks: 6 }, gap: 'the carry is applied to every turn of the vehicle, the script\'s `setRotation` included (not separately measured: the driver\'s steering tests for it on the device, `nativeSteerStep` carry test); a lock-0 seat\'s rider is not carried here (on the device its look is held to the seat, pinball); the X-wing read ~8 ticks, the coaster ~6: 6 is kept' },
  // The two cull rows read their numbers FROM the engine constants the LOD plan
  // and the snapshot's `entityRenderCullBlocks` apply, so the registry and the
  // code cannot drift: re-measuring the ceiling changes bedrock-lod-hull.ts.
  { id: 'actor-draw-ceiling', rule: 'On 26.51/26.52 no actor draws past ~70-72 blocks, whatever its collision box.', evidence: 'round 2026-09-26a, `output/device-round-2026-09-26a/pixel/cull_*.png` (CLAUDE.md); applied through `entityRenderCullBlocks` (bedrock-lod-hull.ts) by the snapshot', appliesTo: ['render'], simulated: 'modelled', values: { blocks: ACTOR_DRAW_CEILING_BLOCKS } },
  { id: 'cull-by-collision-box', rule: 'Below the ceiling an actor culls at ≈ 64 × max(1, collision box diagonal) blocks.', evidence: 'CLAUDE.md (2026-09-22); applied through `entityRenderCullBlocks` (bedrock-lod-hull.ts) by the snapshot', appliesTo: ['render'], simulated: 'modelled', values: { blocksPerDiagonal: RENDER_CULL_BLOCKS_PER_UNIT } },
  { id: 'box-uv-sub-unit-faces', rule: 'Bedrock floors a box-UV cube\'s DECLARED size and does not draw a side face whose height floors to 0.', evidence: 'Pixel probe 2026-09-29 (CLAUDE.md; `UvFloorModel`, `_figure_compile_holes.ts`)', appliesTo: ['render'], simulated: 'device-only', gap: 'the snapshot rasteriser draws every face' },
  { id: 'coplanar-hatching', rule: 'Two colours on one plane hatch (z-fight) on the device.', evidence: 'CLAUDE.md "Two colours on one plane hatch on the device" (`_render_fault_audit.ts`)', appliesTo: ['render'], simulated: 'device-only' },
  { id: 'slow-falling-gravity', rule: 'Slow falling lowers gravity to 0.01 blocks/tick² while falling and prevents fall damage.', evidence: 'Pixel 2026-09-29 float-down 89 blocks in 11 s, unharmed (`output/nimbus-pixel-0929/`)', appliesTo: ['physics'], simulated: 'modelled', values: { gravity: 0.01 } },
  { id: 'fill-volume-limit', rule: '`fillBlocks` takes a BlockVolume INSTANCE (a plain {from,to} is rejected) and at most 32768 blocks per call.', evidence: 'test/_placement-host.ts (the stale-collider bug), @minecraft/server 2.x docs', appliesTo: ['script-host', 'world'], simulated: 'modelled', values: { maxBlocks: 32768 } },
  { id: 'structure-load-keeps-states', rule: '`structure load` turned by a rotation moves each block but keeps its states (a custom block\'s shape in its id/state is NOT turned).', evidence: 'bedrock-placement-pack.ts (the clearance-form re-set after a turned load, 2026-09-25)', appliesTo: ['commands', 'world'], simulated: 'partial', gap: 'vanilla direction states (stairs, doors) are not turned either; the game turns those' },
  { id: 'no-dismount-event', rule: '@minecraft/server 2.9 has no dismount event: a runtime polls who is aboard.', evidence: 'physics spec §4.6 (flyer.js polls every 10 ticks)', appliesTo: ['script-host'], simulated: 'modelled' },
  { id: 'dynamic-property-string-limit', rule: 'A string dynamic property holds at most 32,767 characters; a longer one throws.', evidence: 'bedrock-placement-pack.ts undo record chunks (2026-09-25)', appliesTo: ['script-host'], simulated: 'modelled', values: { maxChars: 32767 } },
  { id: 'simulation-distance', rule: 'Chunks within the simulation distance of a player (and inside ticking areas) are loaded; outside them blocks read undefined and entities freeze.', evidence: 'CLAUDE.md "An unloaded block is not air" (a GameTest vehicle ~100 blocks out stopped being readable)', appliesTo: ['world'], simulated: 'partial', values: { chunks: 6 }, gap: 'the phones\' exact simulation distance is not measured; 6 chunks (96 blocks) matches the ~100-block GameTest loss' },
  { id: 'native-mount-bursts', rule: 'A client-driven mount reports ~0 velocity and its server position moves in bursts (CMVT cadence ~4 ticks).', evidence: 'physics spec §4.6 (`DRIVER_SPEED_WINDOW_TICKS`; Saga 2-tick deltas 0/24.9/60.2/99.0 mph)', appliesTo: ['physics'], simulated: 'partial', values: { burstTicks: 4 }, gap: 'the engine moves the mount every tick (smooth); the driver HUD\'s burst averaging is not exercised' },
  { id: 'fly-sound-block-normal', rule: 'Any entity moved through the air (a hover mount, a ride car carried along its path, a figure) raises a `fly` sound event the client resolves through the block-MATERIAL table: with no sound it logs `[Sound][verbose] No sound found for block type \'normal\' and event type \'fly\'`. Only the RP `sounds.json` `interactive_sounds.block_sounds.normal.events.fly` silences it; per-entity entries (`entity_sounds`, `interactive_sounds.entity_sounds`, even naming a real silent sound) do nothing. Whether a pack\'s `normal` replaces or merges into vanilla\'s is unknown, so the pack carries vanilla\'s events verbatim (`flySoundEvents`).', evidence: 'Saga 26.52 A/B 2026-09-29/30 (`output/fly-sound-ab-0929/saga/_notes.txt`, README.md): baseline 355 lines in a 60 s flight and 45-72/min by the orbit alone; variant A (block_sounds.normal + fly "") 0 in every window (orbit idle 3 min, perch, 60 s flight, 3 min mounted idle); variant B (silent sound per entity) 404 in 60 s of flight; the per-entity interactive entry changed nothing on the Pixel (round 29d) or the Saga', appliesTo: ['sound'], simulated: 'device-only', values: { baselineFlyLinesPerFlightMinute: 355, variantAFlyLines: 0, variantBFlyLinesPerFlightMinute: 404 } },
  { id: 'rider-seat-order', rule: '`Rideable.addRider` cannot choose a seat: the new rider takes the first free seat in the definition\'s `seats` order (seat 0, the controlling seat, first).', evidence: 'ASSUMED 2026-09-30 (the hop, web/src/engine/bedrock-ride-hop.ts): Microsoft Learn\'s `Seat` class documents min/max rider counts per seat and nothing about which seat a script-added rider takes; not measured. The hop chooses the front-most free seat across ENTITIES (a train\'s cars) and relies on the compiler listing the driver\'s seat first. A GameTest that adds two players to a two-seat car and reads each rider\'s position would settle it.', appliesTo: ['entity'], simulated: 'partial', gap: 'Pixel round 30f measured only the EMPTY-car case: the rider took seat 0 (feet +1.16 z from the car = seat 0). Which seat a rider takes when seat 0 is held needs a second player (a pig was refused as a rider). The simulator seats in the lowest free index; whether the device compacts riders when one leaves is not modelled' },
  { id: 'add-rider-after-eject', rule: 'A player ejected from one mount (`ejectRider`) can be added to another with `addRider` in the same tick.', evidence: 'Pixel 26.51 round 2026-09-30f (`output/device-round-2026-09-30f/pixel/_notes.txt`): three hops (a cloud onto 10261\'s train on the lift hill, a moving train into a hovering cloud, 10797\'s slide into its parked car) each boarded in the same tick; none fell back to the mount left. The hop still puts a refused rider back on the mount it left.', appliesTo: ['entity', 'script-host'], simulated: 'modelled' },
  { id: 'dynamic-properties-per-pack', rule: 'An entity\'s dynamic properties are visible only to the behaviour pack that wrote them; tags (`addTag`) are shared by every pack\'s scripts.', evidence: 'Script API documentation (jaylydev.github.io/scriptapi-docs "Dynamic Properties": "behavior packs cannot access other behavior packs\' dynamic properties", keyed by the pack\'s header UUID; Microsoft Learn states the storage limits per content pack); applied by the hop (bedrock-ride-hop.ts: a coaster car of one pack tells a plane of another its train and rank by TAGS) 2026-09-30. Not measured on the phones.', appliesTo: ['script-host'], simulated: 'partial', gap: 'the simulator keeps one dynamic-property map per entity, shared by every pack: a script reading another pack\'s property works here and not on the device' },
  { id: 'rider-free-look', rule: 'On a SCRIPTED vehicle\'s seat with `lock_rider_rotation` 181, a touch drag turns the rider\'s look (yaw and pitch, reported by `getRotation` every tick) under the script\'s free camera; the engine does not turn the zero-speed vehicle toward the rider\'s look (the script\'s teleport owns its yaw); a turning vehicle carries its rider\'s yaw round ~6 ticks late (as a coaster car does, `rider-yaw-lag`); `setRotation` on a rider of such a seat changes NOTHING (neither yaw nor pitch), so no script can turn a seated player\'s own view: the cockpit view is a script camera (`cockpitCamera`).', evidence: 'MEASURED Saga 26.52 round 30j (2026-10-07, `output/device-round-2026-10-07j/saga/ContentLog-30j-live.txt` CMCAM): the chase drag orbits, holds at rest and eases back in 2-3 s on 42172, 7140, the 10797 car and 60221 (no twitch); in the old cockpit view (hotbar 9, the rider\'s own first person eased by `setRotation`) `riderYaw` held 11.9 through 15:43:14-41 while the McLaren drove at 19 blocks/s and every ease (`recentring` true for one sample) was undone - the yaw the script set never arrived, its own expected turn then read as an opposite drag - so the view stayed 56 degrees off the nose (X-wing 17) and kept its pitch. ASSUMED before (2026-09-30): Microsoft Learn documents `lock_rider_rotation` as the angle a rider may rotate (181 the default, no limit); the coaster\'s 181 seats report a rider yaw trailing the car ~6 ticks (CLAUDE.md camera gotcha); pinball (Pixel 2026-09-25, a lock-0 seat) measured a drag reporting the pitch every tick and `setRotation` applying yaw only. None of it measured on a scripted vehicle. Device probe: ride 42172 and 7140 with `/scriptevent craftmatic:vehicle_telemetry fast`, drag the screen at rest and while driving: CMCAM `riderYaw` must follow the finger, `yawOff` ease back to 0 within ~2 s of letting go while moving, and CMVT `yaw` must NOT move with the drag at rest (a vehicle the engine turns toward the look would fight the script: jitter). A GameTest cannot drag (a simulated player\'s look is not touch input).', appliesTo: ['entity', 'camera', 'input'], simulated: 'partial', gap: 'the simulator ignores `setRotation` on a player riding a seat whose `lock_rider_rotation` is not 0 (as the Saga did; a lock-0 seat - pinball\'s - still applies the yaw, Pixel 2026-09-25) and does not turn a zero-speed scripted vehicle toward its rider. The carry IS measured and modelled since round 30l (quirk `rider-yaw-lag`: the X-wing\'s rider followed four script-teleported turns ~8 ticks late), so the "carried or not" reading in `freeLookStep` meets the carried case on the device and in the simulator alike. Pitch drag on a scripted vehicle is still unmeasured' },
  { id: 'native-mount-locked-look', rule: 'A NATIVE mount\'s rider (the hover controller: a rotorcraft, a flyer\'s cloud) held in `player_relative` cannot turn its look by a drag, at seat `lock_rider_rotation` 0 AND at 181: the view does not move and `getRotation` changes only with the stick (which turns rider and mount). The cause is the control scheme, not the seat (quirk `control-scheme-drag-to-camera`). Held in the default scheme, a drag is ASSUMED to turn the rider\'s look as on a scripted vehicle\'s 181 seat, which the hover controller flies along (as a vanilla Happy Ghast) and whose pitch reaches the driver\'s "look down + Jump"; the stick\'s left/right then strafes.', evidence: 'Saga 26.52 round 30j (2026-10-07, `output/device-round-2026-10-07j/saga/rec/r30j-nimbus-13.mp4`, ContentLog CMVT 16:00:44-16:01:22): seat lock 0, drags moved neither the view nor `riderYaw`. Round 30k (`output/device-round-2026-10-07k/saga/notes.md` item 6, ContentLog-30k-live.txt CMVT 19:08:26-19:11:35, `r22-grid.jpg`, `r23-strip.jpg`): seat lock 181, mounted by /ride and by the native Mount button, drags (input swipe, root sendevent, two screen areas) left `riderYaw`/`riderPitch` constant (0/-6, 138/0), so look down + Jump CLIMBED; the stick turned it (yaw 0 -> 360 in 2 s, 19:09:44); the same drags turned the X-wing\'s and McLaren\'s riders (CMCAM `dragging` true), whose runtime holds them in the default scheme. Native riders are in the default scheme since 2026-10-07 (vehicle-camera.js `RIDER_SCHEME`). MEASURED Saga round 30l (`output/device-round-2026-10-07l/saga/notes.md` item 6): in the default scheme the drag DOES reach the look (`riderPitch` -36 -> 14 -> 52; at 52 `descending` true and Jump went down; the stick strafed with the yaw fixed), the controller then chased the dragged yaw - and never caught it, because the look is carried round with the mount (quirks `hover-turn-chase`, `rider-yaw-lag`): the spin vehicle-driver.js now steers through.', appliesTo: ['entity', 'camera', 'input'], simulated: 'partial', gap: 'a simulated player\'s look is set directly, not dragged; the simulator fails a rider held in a drag-to-camera scheme (core invariant `rider-drag-reaches-look`); the default scheme\'s drag reaching the hover controller is now device-measured, not shown by the simulator' },
  { id: 'control-scheme-drag-to-camera', rule: 'Under the `player_relative` and `camera_relative` control schemes a touch drag rotates the CAMERA (the Follow Orbit camera), never the player: with a script `minecraft:free` camera it turns nothing at all. Under the default scheme (`/controlscheme @s clear`, locked_player_relative_strafe) a drag turns the player\'s yaw and pitch.', evidence: 'Microsoft Learn, "Control Schemes" (learn.microsoft.com/minecraft/creator/documents/controlschemes, read 2026-10-07): player relative, Touch: "left or right to rotate the player ... Drag on the screen to rotate the camera when using the third-person Follow Orbit camera"; camera relative, Touch: "Drag on the screen to rotate the camera"; locked player relative strafe: "Swiping left or right rotates the player, while swiping up or down makes the player look up or down". Device: Saga 30k item 6 (the Nimbus rider in `player_relative`: drags inert; the X-wing and McLaren riders in the default scheme: drags read), quirk `native-mount-locked-look`', appliesTo: ['input', 'camera'], simulated: 'modelled', gap: 'the simulator does not route a drag by scheme (a simulated look is set directly); it fails a riding player held in one of these schemes (core invariant `rider-drag-reaches-look`, `DRAG_TO_CAMERA_SCHEMES`)' },
  { id: 'mount-snaps-rider-yaw', rule: 'On mounting a seat, the device turns the rider\'s yaw onto the vehicle\'s heading within the first ~4-12 ticks (in one step or eased over a few ticks); the pitch is kept. A script reading the rider\'s look in those ticks sees a turn of up to 180 degrees the child never made.', evidence: 'Saga 26.52 round 30k (`output/device-round-2026-10-07k/saga/ContentLog-30k-live.txt` CMCAM, the first samples of each mount, 4 ticks apart): X-wing at -180: `riderYaw` 0 -> -180 (18:29:30), -128 -> -180 (18:31:41); X-wing at -90: 54.8 -> -82.8 -> -88.6 -> -89.8 -> -90 (18:35:34); X-wing at 0: -180 -> -3.8 -> -0.8 -> 0 (18:33:40); Milano at -180: 45 -> -180 (18:39:46); McLaren at 0: -89 -> -2.5 (18:56:26); `riderPitch` unchanged in every one. The free look read each as a drag (`yawOff` -180, 176.2, -137.5, 86.6), so the chase camera opened where the player had been looking (notes item 4, `s32`, `s50`). The free look settles through it since 2026-10-07 (`FREE_LOOK.MOUNT_SETTLE_TICKS`).', appliesTo: ['entity', 'camera', 'input'], simulated: 'partial', values: { snapTicksMax: 12 }, gap: 'the simulator\'s `addRider` does not turn the rider; the vehicle course emulates the turn 4 ticks after boarding a child who looks away (`cameraRecentre`, invariant `free-look`)' },
  { id: 'cockpit-draw-lag', rule: 'A cockpit camera set every tick (`setCamera` minecraft:free, eased 0.1 s linear) at a script-teleported vehicle\'s eye on the vehicle\'s pose L ticks back is drawn speed/20 x (3 - L) blocks AHEAD of the drawn seat (behind it past L = 3): the eye stays on the seat at L = 3.', evidence: 'Two Saga 26.52 rounds, each frame matched to the offline cockpit picture at eye shifts of half a block (`scripts/_cockpit_view.ts --shift=0,0,<z>`, 2026-10-08). Round 30k (`output/device-round-2026-10-07k/saga/notes.md` item 5, `r19-cmp.jpg`, `r20-strip.jpg`) at L = 1.5: McLaren 42172 at 43 mph (19.2 blocks/s) eye over the hood, +1.5..+2.5 blocks ahead of the seat (the notes\' 2.3-3.0 was high: at +2.5 the picture is sky alone); X-wing 7140 at 40 mph (17.9 blocks/s) +1.5..+2 up the nose; both on the seat at rest. Round 30l (`output/device-round-2026-10-07l/saga/notes.md` item 4, `frames/r17-mcl-ck-sheet.jpg` f007-f011, `frames/r18-xw-ck-sheet.jpg` f007-f014) at L = 4: the McLaren\'s eye BEHIND the seat at 36-43 mph, the view framed by the grey pillars behind the cabin with the hood through the gap (the picture at -1; -0.5 is the dashboard, -1.5 the red engine), the X-wing\'s inside its fuselage (flat grey faces: -1..-1.5), both in the cabin at <= 27 mph and on the seat at rest. Lag that cancels each (`cockpitLagFromLead`): 3.1-4.1 / 2.65-3.3 (McLaren 30k / 30l), 3.05-3.85 / 2.3-2.95 (X-wing): 3 lies inside or at the edge of all four (each read +-0.3 block = +-0.35 tick at 43 mph); 4 and 1.5 each miss two. The coaster\'s per-tick camera keeps its own 1.5 (`COASTER_RIDER_VIEW.tickLag`, a different camera schedule, measured by markers on the Pixel).', appliesTo: ['camera', 'render'], simulated: 'modelled', values: { ticks: 3 }, gap: 'the simulator records the camera\'s target, not the eased draw; the vehicle course judges the target against the pose this many ticks back (invariant `cockpit-eye-on-seat`). The 3 is read off four recordings against offline pictures, a bracket of +-0.4 tick, not a marker measurement; whether the client\'s lag differs between phones (the Pixel\'s coaster read 1.5) is open' },
  { id: 'hop-invisibility-handoff', rule: 'Invisibility is ONE effect per player shared by every pack: a runtime that removes the effect it gave a rider also removes the one another pack\'s runtime gave that rider since. When a hop moves a rider from a pack whose camera hid it (a scripted plane at a size its body does not fit) to a coaster car (whose camera at the eye hides its rider once, on boarding), the effect must be lifted BEFORE the new mount sees the rider, never after.', evidence: 'Saga 26.52 round 30j (2026-10-07, `output/device-round-2026-10-07j/saga/s272-276.jpg`, `rec/r30j-hop-10261.mp4` 5-12 s): after the X-wing (7140, rider hidden at 100 %) was flown into 10261\'s train, the rider\'s own see-through head filled the coaster camera for ~6 s; vehicle-camera.js removed `invisibility` a tick after the coaster added its own. Why the head then faded out after ~6 s is NOT explained (the coaster adds the effect once, for an hour). Fixed 2026-10-07: hop.js lifts the camera\'s invisibility (tag `HOP_TAGS.hidden`) as it boards, the camera script leaves a hopped rider\'s effect alone. Not yet ridden.', appliesTo: ['entity', 'camera', 'script-host'], simulated: 'modelled', gap: 'which pack\'s script runs first in a tick is not known on the device; the simulator runs packs in load order and a pack\'s scripts in its main.js import order; test/bedrock-ride-hop.test.ts "the rider the plane\'s camera hid stays hidden by the coaster after the hop, whichever pack runs first" checks both pack orders with the shipped import order (it fails on the old runtimes). The fade after ~6 s is not modelled' },
  { id: 'aabb-is-collision-box', rule: '`Entity.getAABB()` is the entity\'s `minecraft:collision_box` about its feet (width as the x and z diameter, times its scale), centre and half extents.', evidence: 'ASSUMED 2026-09-30 (the hop reads a target\'s box with it): @minecraft/server 2.9 declares `getAABB`; its extent for a rotated, scaled or seat-carrying entity is not measured.', appliesTo: ['entity', 'script-host'], simulated: 'partial', gap: 'the simulator returns the unscaled collision box; a device value past it would only widen the hop\'s reach' },
  { id: 'dismount-free-spot', rule: 'A PLAYER taken off a seat (`Rideable.ejectRider`, `/ride @s stop_riding`) is set on the floor of the first free spot one block from the SEAT ENTITY\'s point, in world order (0,-1), (0,+1), (+1,-1), (+1,+1), (-1,+1) - the diagonals come before the plain x sides - even in the open. A spot is taken when its floor lies within about +0.5 / -1 of the seat entity\'s point and the body fits there; with none, the player is put at the seat entity\'s point 0.2 up and falls. The seat\'s yaw and the rider\'s facing do not change the order; a rider sitting inside a block (a seat sunk 0.1-0.3 into the floor, a block over the seat) is set down the same way.', evidence: 'Pixel GameTest 2026-09-30 (`scripts/_gametest_quirks.ts` quirk_dismount / quirk_dismount2, the moulded seat `seatBehavior`; the rider\'s feet read 0.4 under the seat point): run 2 (output/gametest-quirks-0930/run2/cmgt.log QDM, 14 layouts x eject / stop_riding, identical): open, one or both x sides walled, +z walled, a block overhead, sunk 0.1 / 0.3 -> (0, floor, -1); -z walled -> (0, floor, +1); ring of 4 -> (+1, floor, -1); ring of 8 -> (0, seat + 0.2, 0), then the floor. Run 3 (output/gametest-quirks-0930/run3/cmgt.log): +-z walled (x sides open or one walled) -> (+1, -1); ring of 4 + (+1,-1) -> (+1, +1); + (-1,-1) too -> (+1, +1); + (+1,+1) too -> (-1, +1); a seat off its block centre by (0.3, 0.2) or (-0.3, -0.3) -> (0, -1) from the SEAT; a slab at (0,-1) -> onto the slab (+0.5); a full block or a 1-deep pit at (0,-1) -> (0, +1). Seat yaw 90 / 180 / 270 and a rider facing -z did not change it. `isSneaking = true` on a simulated player does NOT dismount', appliesTo: ['entity', 'physics'], simulated: 'partial', gap: 'the places of (-1,-1), (+1,0) and (-1,0) in the order and the exact floor window (+0.2 taken, +0.7 refused above; -0.3 taken, -1.3 refused below) were not reached (TODO in physics/systems.ts); a real SNEAK is client input a simulated player cannot send, so a sneak is assumed to set down like stop_riding; a MOB rider\'s spot is not measured and the engine leaves it where it sat' },
  { id: 'teleport-into-floor', rule: 'A PLAYER teleported with its box inside a block\'s collision is never lifted onto the top: it falls THROUGH what it overlaps (the sweep ignores a solid the box already overlaps) to the next surface under its feet, the first gravity step 3 ticks after the teleport; feet 0.1-0.5 into a full block (stone or `craftmatic:collider` hi 16) land on the floor under that block, into a bottom slab or a half-height collider on the floor under the slab. While it overlaps, its velocity on the one horizontal axis whose move frees it soonest is SET to 0.1 blocks/tick toward the free side (then ordinary friction: it drifts 0.12-0.34 past free); a player with no free side within reach (the middle of a 3 x 3 pad, 1.8 from free) is not pushed. No damage. The script `teleport` and `/tp` behave the same. A player-sized MOB (no AI) teleported 0.34 into a block or slab is the opposite: lifted onto its top by tick 2.', evidence: 'Pixel GameTest 2026-09-30 (`scripts/_gametest_quirks.ts` quirk_tp, simulated players in Survival, output/gametest-quirks-0930/run1/cmgt.log QTP rows 0-37): centred on a 3 x 3 pad, every depth ends at feet = block bottom (stone/collider: -0.9/-0.8/-0.66/-0.5 from the target; slab/half collider: -0.4/-0.3/-0.16/0), health 20 -> 20; on the edge of a single block with air on +x: pushed +x 0.1/tick for 3 ticks then drift, 0.42-0.64 in all, falling meanwhile; beside a wall form, pushed toward its nearer free side by 0.22-0.62 and never up (re-run after the x-mirror fix, output/gametest-quirks-0930/run3/cmgt.log: +0.22/+0.32/+0.52/+0.62 for 0.1/0.2/0.34/0.5 of overlap); the 0.6 x 1.8 dummy mob at 0.34: +0.34 (onto the top) at tick 2. Agrees with the 29d Pixel read-out (`output/device-round-2026-09-29d/pixel/_notes.txt`: a lift set-down 0.34 inside a slab read one block LOWER and one over in z).', appliesTo: ['physics'], simulated: 'partial', values: { pushBlocksPerTick: 0.1, maxPushBlocks: 1, firstFallTick: 3 }, gap: 'the push bound is 1 block (free at 0.6 was pushed, 1.8 was not; the device\'s exact bound lies between); the 2-tick pause before the fall and the mob lift are not modelled; the probe is a SIMULATED player - a phone player\'s client-side movement was not measured separately, though the 29d read-out agrees' },
  { id: 'block-collision-x-mirrored', rule: 'A custom block\'s `minecraft:collision_box` is MIRRORED in x: a box declared at origin x o, size s stands on world x [8 - o - s, 8 - o] pixels of its block (origin -8 is the block\'s HIGH-x side); y and z are as written. A pack must declare a box meant for world x [x0, x1] at origin x 8 - x1.', evidence: 'Pixel GameTest 2026-09-30 (quirk_bands, output/gametest-quirks-0930/run2/cmgt.log QBANDS): a 0.2-wide pin dropped over each quarter of a pillar landed on `collider_w2` (declared origin -8, size 8) only at x 0.75, on `collider_w5` (declared origin 0) only at x 0.25, on `collider_w9` (declared z origin -8, size 8) only at z 0.25; stone caught all four. Run 1 (output/gametest-quirks-0930/run1/cmgt.log QTP 32-35): players beside `collider_w2` were pushed as a band on x 0.5-1 pushes them. Fixed in `collisionBox` (bedrock-building-shell.ts); packs built before it carry every x-banded clearance form on the wrong half of its block', appliesTo: ['world'], simulated: 'modelled' },
  { id: 'hover-turn-chase', rule: 'The native hover controller (`free_camera_controlled` + `movement.hover`) turns its mount toward the rider\'s REPORTED look by 0.144 of the offset every tick, at rest as in flight, with no cap seen up to a 74-degree offset (10.6 degrees/tick). With the carry (`rider-yaw-lag`) the offset is constant after a drag, so the chase is a spin that never ends until a swipe the other way closes the offset.', evidence: 'Saga 26.52 round 30l (`output/device-round-2026-10-07l/saga/notes.md` item 6, ContentLog CMVT `dragonball_cloud`, `nimyaw.py`, `rec/r30l-nim200-spin.mp4`, `frames/nim200-spin-sheet.jpg`): at 100 % after one 400-px swipe (22:01:28) the cloud turned 26 degrees per 4 ticks (6.5/tick, 130 degrees/s) at mph 0 with `riderYaw` - `yaw` 45-46 through 3 full turns: 6.5 / 45 = 0.144; at 200 % (21:55) 10.6/tick at a 74-degree lead: 0.143. The steady state is the finger\'s 84 degrees less 6 ticks x 6.5 of carry = 45, which the model reproduces to the degree. Fixed 2026-10-08: vehicle-driver.js writes the heading every tick and turns it by the drag alone (`nativeSteerStep`); the simulator\'s `nimbus-spin-30l` regression reproduces the spin on the 30l pack.', appliesTo: ['physics', 'entity'], simulated: 'modelled', values: { offsetShareTurnedPerTick: 0.144 } },
  { id: 'seat-camera-radius-unobserved', rule: 'A seat\'s `third_person_camera_radius` had no visible effect on the Nimbus\'s camera distance (declared 5 / 10 / 20 at 100 / 200 / 400 %, the rider the same ~120 px wide on screen at every size); whether the device caps it or the pack\'s script free camera (vehicle-camera.js `chase`, which stands in for the native third person on every vehicle) simply overrode it is not separated. Nothing relies on it: the chase boom is the script\'s, scaled by the size (`CHASE_BOOM_MAX_BLOCKS`).', evidence: 'Saga 26.52 round 30l (`output/device-round-2026-10-07l/saga/notes.md` item 2, `r09-nim100-mounted.jpg`, `r08-nim200-chase.jpg`, `r10-nim400-mounted.jpg`); bedrock-placement-pack.ts `rideableAtSize` scales the declared radius with the size group (TODO(seat-camera-radius))', appliesTo: ['camera'], simulated: 'device-only', gap: 'the simulator has no native third-person camera; a pack\'s script camera is what it records' },
  { id: 'auto-jump', rule: 'With auto-jump on (the touch default), a player walking forward jumps an obstacle whose top is more than 0.5 and at most 1.2 blocks over its feet, found by two probes at 0.51 over the feet along its sides reaching 0.7 past the move, when the two block cells over its head are free; a taller one (a 1.25 riser) stops it, though a pressed jump would clear it; never when sneaking or moving backward.', evidence: 'ASSUMED from Java\'s `LocalPlayer.updateAutoJump` (1.10+; minecraft.wiki "Jumping": the player automatically jumps when walking toward the edge of a block); Bedrock\'s code is closed. Consistent with the Pixel 26.52 round 30k (2026-10-07, `output/device-round-2026-10-07k/pixel/notes.md` item 2, rec/cm30k-lifthill.mp4): climbing 10261\'s lift hill at 200 % with auto-jump only, the player stopped at pin + (28.2, 9.88) on three tries; the modelled walk over the same pack stops at exactly that point, in front of a 1.25 riser, while a jump-whenever-blocked walk goes on to 39.7 (`scripts/_walk_line.ts --dir=+x --jump=auto`).', appliesTo: ['physics', 'input'], simulated: 'partial', values: { minRise: 0.5, maxRise: 1.2, probeHeight: 0.51, lookahead: 0.7 }, gap: 'Java\'s rules with one device point in agreement; the 0.5..1.2 window, the headroom cells and the backward cut-off are not measured on Bedrock. The simulator\'s own player (`physics/systems.ts`) does not turn it on: the walks that use it are `_walk_line.ts --jump=auto` and the tread planner\'s lane pass (`colliderLaneWalk`)' },
];

const BY_ID = new Map<QuirkId, Quirk>(QUIRKS.map(q => [q.id, q]));

/** A quirk by id (throws for an unknown id: a typo must not silently read no fact). */
export function quirk(id: QuirkId): Quirk {
  const q = BY_ID.get(id);
  if (!q) throw new Error(`unknown quirk ${id}`);
  return q;
}

/** A quirk's measured number. */
export function quirkValue(id: QuirkId, key: string): number {
  const v = quirk(id).values?.[key];
  if (v === undefined) throw new Error(`quirk ${id} has no value ${key}`);
  return v;
}

/** Every registered quirk, in registry order. */
export function allQuirks(): readonly Quirk[] { return QUIRKS; }

/** The quirks an area of the engine cannot simulate: what a scenario touching it must report as device-only. */
export function deviceOnly(area: QuirkArea): Quirk[] { return QUIRKS.filter(q => q.simulated === 'device-only' && q.appliesTo.includes(area)); }
